package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"ironflyer/apps/orchestrator/internal/graph/model"
)

// Agents is the resolver for the agents field.
func (r *queryResolver) Agents(ctx context.Context) ([]model.Agent, error) {
	panic(fmt.Errorf("not implemented: Agents - agents"))
}

// AgentTelemetry is the resolver for the agentTelemetry field.
func (r *queryResolver) AgentTelemetry(ctx context.Context, limit *int, role *string, provider *string, modelName *string) ([]model.AgentCall, error) {
	panic(fmt.Errorf("not implemented: AgentTelemetry - agentTelemetry"))
}

// BanditRanking is the resolver for the banditRanking field.
func (r *queryResolver) BanditRanking(ctx context.Context, lookback *int) (*model.BanditRanking, error) {
	panic(fmt.Errorf("not implemented: BanditRanking - banditRanking"))
}

// CostStream is the resolver for the costStream field.
func (r *subscriptionResolver) CostStream(ctx context.Context) (<-chan *model.CostDelta, error) {
	panic(fmt.Errorf("not implemented: CostStream - costStream"))
}
