package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"encoding/base64"
	"ironflyer/apps/orchestrator/internal/graph/model"
	"ironflyer/apps/orchestrator/internal/mobile/assets"
	"ironflyer/apps/orchestrator/internal/store"
	"strings"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// GenerateMobileAssets renders the full icon + splash bundle for the
// requested platforms from a single uploaded logo. The resolver:
//
//  1. validates the caller owns the named project,
//  2. base64-decodes the logo,
//  3. dispatches to the per-platform Generator helpers,
//  4. returns the manifest of generated entries (path, dimensions,
//     size, purpose) so the UI can render thumbnails + totals.
func (r *mutationResolver) GenerateMobileAssets(ctx context.Context, input model.GenerateMobileAssetsInput) (*model.GenerateMobileAssetsResult, error) {
	if r.Resolver.Projects == nil {
		return nil, gqlNotConfigured("projects")
	}

	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}

	project, err := r.Resolver.Projects.Get(input.ProjectID)
	if err != nil {
		if err == store.ErrNotFound {
			return nil, gqlerror.Errorf("project %q not found", input.ProjectID)
		}
		return nil, err
	}
	if !project.IsAccessibleBy(u.ID) {
		return nil, errUnauthenticated
	}

	logoBytes, err := base64.StdEncoding.DecodeString(strings.TrimSpace(input.LogoPngBase64))
	if err != nil {
		return nil, gqlerror.Errorf("logoPngBase64: %s", err.Error())
	}
	if len(logoBytes) == 0 {
		return nil, gqlerror.Errorf("logoPngBase64: empty payload")
	}

	in := assets.GenerateInput{
		LogoPNG:         logoBytes,
		BackgroundColor: input.BackgroundColor,
		AppName:         project.Name,
	}
	if input.SplashForegroundColor != nil {
		in.SplashFGColor = *input.SplashForegroundColor
	}

	gen := assets.New(r.Logger.With().Str("subsystem", "mobile-assets").Logger())

	platforms := normalizePlatformList(input.Platforms)

	merged := assets.GenerateResult{Files: map[string][]byte{}}
	for _, plat := range platforms {
		var res *assets.GenerateResult
		switch plat {
		case "android":
			res, err = gen.GenerateAndroid(ctx, in)
		case "ios":
			res, err = gen.GenerateIOS(ctx, in)
		case "expo":
			res, err = gen.GenerateExpo(ctx, in)
		default:
			return nil, gqlerror.Errorf("unknown platform %q", plat)
		}
		if err != nil {
			return nil, gqlerror.Errorf("generate %s: %s", plat, err.Error())
		}
		for k, v := range res.Files {
			merged.Files[k] = v
		}
		merged.Manifest.Entries = append(merged.Manifest.Entries, res.Manifest.Entries...)
		merged.Manifest.GeneratedAt = res.Manifest.GeneratedAt
	}

	total := 0
	out := make([]model.GenerateMobileAssetEntry, 0, len(merged.Manifest.Entries))
	for _, e := range merged.Manifest.Entries {
		total += e.SizeBytes
		out = append(out, model.GenerateMobileAssetEntry{
			Path:      e.Path,
			Width:     e.Width,
			Height:    e.Height,
			SizeBytes: e.SizeBytes,
			Purpose:   e.Purpose,
		})
	}

	r.Logger.Info().
		Str("project_id", input.ProjectID).
		Strs("platforms", platforms).
		Int("files", len(merged.Files)).
		Int("total_bytes", total).
		Msg("mobile-assets generated")

	return &model.GenerateMobileAssetsResult{
		FilesCount:  len(merged.Files),
		TotalBytes:  total,
		GeneratedAt: merged.Manifest.GeneratedAt,
		Entries:     out,
	}, nil
}
