package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"ironflyer/apps/orchestrator/internal/auditexport"
	"ironflyer/apps/orchestrator/internal/graph/model"
	"time"
)

// AuditExportPreview resolves the metadata-only surface clients query
// before pulling the actual stream over the REST exception. The
// signedURL is stubbed today (see compromises in package doc); a
// future agent wires real HMAC signing into auditexport.Config.
func (r *queryResolver) AuditExportPreview(ctx context.Context, filter model.AuditExportFilter) (*model.AuditExportPreview, error) {
	if r.AuditExporter == nil {
		return nil, fmt.Errorf("audit export not configured")
	}
	f := auditexport.Filter{
		TenantID:     filter.TenantID,
		Since:        filter.Since,
		Until:        filter.Until,
		Format:       parseFormat(filter.Format),
		IncludeAttrs: derefBool(filter.IncludeAttrs),
	}
	if len(filter.EventTypes) > 0 {
		f.EventTypes = append(f.EventTypes, filter.EventTypes...)
	}
	// Reject the platform-operator wildcard unless the caller has the
	// platform_operator scope — surfaced as a permission error so the
	// client knows to escalate, not retry.
	if f.TenantID == auditexport.TenantWildcard && !callerIsPlatformOperator(ctx) {
		return nil, fmt.Errorf("audit export: platform_operator scope required for cross-tenant exports")
	}

	// Preview counts: we run the streamer into a discard sink to get
	// an exact entry count without re-implementing the filter logic.
	// For very large windows this is intentionally O(N) — the client
	// is expected to keep windows narrow.
	counter := &countingWriter{}
	if err := r.AuditExporter.Stream(ctx, counter, f); err != nil {
		return nil, err
	}

	cfg := r.AuditExportConfig
	if cfg.SignedURLTTL == 0 {
		cfg = auditexport.DefaultConfig()
	}
	// BuildDownloadURL now HMAC-signs (tenant, format, expiry) into
	// the URL itself — see auditexport/signer.go. The download REST
	// exception must Signer.Verify the token before streaming.
	url, expires, err := cfg.BuildDownloadURL(f.TenantID, f.Format)
	if err != nil {
		return nil, err
	}
	formatStr := string(f.Format)
	if formatStr == "" {
		formatStr = string(auditexport.FormatCSV)
	}
	return &model.AuditExportPreview{
		EstimatedEntryCount: counter.lines,
		EstimatedBytes:      counter.bytes,
		Format:              formatStr,
		SignedURL:           &url,
		ExpiresAt:           &expires,
	}, nil
}

// AuditChainProof returns the chain-of-custody proof for the [since,
// until] window. brokenLinks is empty when verified=true.
func (r *queryResolver) AuditChainProof(ctx context.Context, since time.Time, until time.Time) (*model.AuditChainProof, error) {
	if r.AuditExporter == nil {
		return nil, fmt.Errorf("audit export not configured")
	}
	proof, err := r.AuditExporter.ChainProof(ctx, since, until)
	if err != nil {
		return nil, err
	}
	broken := make([]model.BrokenAuditLink, 0, len(proof.BrokenLinks))
	for _, b := range proof.BrokenLinks {
		broken = append(broken, model.BrokenAuditLink{
			AtEntryID:        b.AtEntryID,
			ExpectedPrevHash: b.ExpectedPrevHash,
			ActualPrevHash:   b.ActualPrevHash,
		})
	}
	return &model.AuditChainProof{
		WindowStart: proof.From,
		WindowEnd:   proof.To,
		EntryCount:  proof.EntryCount,
		StartHash:   proof.StartHash,
		EndHash:     proof.EndHash,
		Verified:    proof.Verified,
		BrokenLinks: broken,
	}, nil
}
