package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"ironflyer/apps/orchestrator/internal/graph/model"
)

// Audit is the resolver for the audit field.
func (r *queryResolver) Audit(ctx context.Context, query *model.AuditQueryInput) ([]model.AuditEntry, error) {
	panic(fmt.Errorf("not implemented: Audit - audit"))
}

// VerifyAudit is the resolver for the verifyAudit field.
func (r *queryResolver) VerifyAudit(ctx context.Context) (*model.AuditVerifyResult, error) {
	panic(fmt.Errorf("not implemented: VerifyAudit - verifyAudit"))
}

// AuditExportCSVURL is the resolver for the auditExportCsvUrl field.
func (r *queryResolver) AuditExportCSVURL(ctx context.Context, query *model.AuditQueryInput) (string, error) {
	panic(fmt.Errorf("not implemented: AuditExportCSVURL - auditExportCsvUrl"))
}

// AuditExportPDFURL is the resolver for the auditExportPdfUrl field.
func (r *queryResolver) AuditExportPDFURL(ctx context.Context, query *model.AuditQueryInput) (string, error) {
	panic(fmt.Errorf("not implemented: AuditExportPDFURL - auditExportPdfUrl"))
}
