package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"ironflyer/apps/orchestrator/internal/auth"
	"ironflyer/apps/orchestrator/internal/graph/model"
	"time"
)

// SignUp resolves the signUp mutation. Creates a new user + issues a
// JWT in one call.
func (r *mutationResolver) SignUp(ctx context.Context, input model.SignUpInput) (*model.Session, error) {
	if r.Auth == nil {
		return nil, gqlNotConfigured("auth")
	}
	name := ""
	if input.Name != nil {
		name = *input.Name
	}
	u, token, err := r.Auth.Signup(ctx, auth.SignupInput{
		Email:    input.Email,
		Name:     name,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}
	exp := time.Now().Add(r.Auth.TTL()).UTC()
	return &model.Session{
		User:      *toModelUser(u),
		Token:     token,
		ExpiresAt: &exp,
	}, nil
}

// SignIn resolves the signIn mutation. Verifies password + issues a
// JWT. Returns ErrBadPassword as a typed GraphQL error so the client
// can render a friendly message.
func (r *mutationResolver) SignIn(ctx context.Context, input model.SignInInput) (*model.Session, error) {
	if r.Auth == nil {
		return nil, gqlNotConfigured("auth")
	}
	u, token, err := r.Auth.Login(ctx, input.Email, input.Password)
	if err != nil {
		if errors.Is(err, auth.ErrBadPassword) {
			return nil, errors.New("invalid email or password")
		}
		return nil, err
	}
	exp := time.Now().Add(r.Auth.TTL()).UTC()
	return &model.Session{
		User:      *toModelUser(u),
		Token:     token,
		ExpiresAt: &exp,
	}, nil
}

// SignOut is a no-op in the V22 minimal auth (stateless JWT). The
// client is responsible for dropping its token. Returning ok=true is
// the canonical "signed out" response so the SPA can update its UI.
func (r *mutationResolver) SignOut(ctx context.Context) (*model.OperationResult, error) {
	msg := "signed out"
	return &model.OperationResult{Ok: true, Message: &msg}, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, token string) (*model.Session, error) {
	return nil, gqlNotConfigured("email_verification")
}

// ResendVerificationEmail is the resolver for the resendVerificationEmail field.
func (r *mutationResolver) ResendVerificationEmail(ctx context.Context) (*model.OperationResult, error) {
	return nil, gqlNotConfigured("email_verification")
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, email string) (*model.OperationResult, error) {
	// Always-OK probe-safe response (don't leak existence).
	msg := "if an account with that email exists, you'll receive a reset link"
	return &model.OperationResult{Ok: true, Message: &msg}, nil
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, token string, newPassword string) (*model.Session, error) {
	return nil, gqlNotConfigured("password_reset")
}

// RevokeSession is the resolver for the revokeSession field.
func (r *mutationResolver) RevokeSession(ctx context.Context, jti string) (*model.OperationResult, error) {
	return nil, gqlNotConfigured("sessions")
}

// RevokeAllOtherSessions is the resolver for the revokeAllOtherSessions field.
func (r *mutationResolver) RevokeAllOtherSessions(ctx context.Context) (*model.OperationResult, error) {
	return nil, gqlNotConfigured("sessions")
}

// RequestEmailChange is the resolver for the requestEmailChange field.
func (r *mutationResolver) RequestEmailChange(ctx context.Context, input model.EmailChangeInput) (*model.OperationResult, error) {
	return nil, gqlNotConfigured("email_change")
}

// ConfirmEmailChange is the resolver for the confirmEmailChange field.
func (r *mutationResolver) ConfirmEmailChange(ctx context.Context, token string) (*model.OperationResult, error) {
	return nil, gqlNotConfigured("email_change")
}

// SetTelemetryPreference flips the telemetry opt-out on the current
// user. Available even in V22 minimal since the store backs it.
func (r *mutationResolver) SetTelemetryPreference(ctx context.Context, input model.TelemetryPreferenceInput) (*model.User, error) {
	if r.Auth == nil {
		return nil, gqlNotConfigured("auth")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.Auth.SetTelemetryOptOut(ctx, u.ID, input.OptOut); err != nil {
		return nil, err
	}
	refreshed, err := r.Auth.GetByID(ctx, u.ID)
	if err != nil {
		return nil, err
	}
	return toModelUser(refreshed), nil
}

// Me returns the authenticated user, or nil for anonymous callers.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	u, err := currentUser(ctx)
	if err != nil {
		// Anonymous — return nil per GraphQL convention for "no
		// session", not an error.
		return nil, nil
	}
	if r.Auth != nil {
		// Refresh from the store so plan / email-verified flips show
		// up without forcing a sign-out.
		if refreshed, refErr := r.Auth.GetByID(ctx, u.ID); refErr == nil {
			return toModelUser(refreshed), nil
		}
	}
	return toModelUser(u), nil
}

// MySessions returns the list of active sessions for the caller. In
// V22 minimal there is no session store wired, so we return a single
// synthetic row for the current bearer token so the UI's "active
// sessions" panel still has something to render.
func (r *queryResolver) MySessions(ctx context.Context) ([]model.Session, error) {
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	current := true
	return []model.Session{
		{
			User:    *toModelUser(u),
			Token:   "",
			Current: &current,
		},
	}, nil
}
