package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"ironflyer/apps/orchestrator/internal/blueprints"
	"ironflyer/apps/orchestrator/internal/graph/model"
)

// Blueprints is the resolver for the blueprints field.
func (r *queryResolver) Blueprints(ctx context.Context) ([]model.Blueprint, error) {
	if r.BlueprintsReg == nil {
		return nil, gqlNotConfigured("blueprints")
	}
	rows := r.BlueprintsReg.List()
	out := make([]model.Blueprint, 0, len(rows))
	for _, b := range rows {
		out = append(out, *blueprintToGraphQL(b))
	}
	return out, nil
}

// Blueprint is the resolver for the blueprint field.
func (r *queryResolver) Blueprint(ctx context.Context, id string) (*model.Blueprint, error) {
	if r.BlueprintsReg == nil {
		return nil, gqlNotConfigured("blueprints")
	}
	b, ok := r.BlueprintsReg.Get(id)
	if !ok {
		return nil, nil
	}
	return blueprintToGraphQL(b), nil
}

// BlueprintStats is the resolver for the blueprintStats field.
func (r *queryResolver) BlueprintStats(ctx context.Context, id string) (*model.BlueprintStats, error) {
	if r.BlueprintStatsSvc == nil {
		return nil, gqlNotConfigured("blueprint_stats")
	}
	s, err := r.BlueprintStatsSvc.Get(ctx, id)
	if err != nil {
		if errors.Is(err, blueprints.ErrNoStats) {
			return nil, nil
		}
		return nil, err
	}
	return blueprintStatsToGraphQL(s), nil
}

// BlueprintRanking is the resolver for the blueprintRanking field.
func (r *queryResolver) BlueprintRanking(ctx context.Context, byMetric *string, limit *int) ([]model.BlueprintStats, error) {
	if r.BlueprintStatsSvc == nil {
		return nil, gqlNotConfigured("blueprint_stats")
	}
	metric := "executions"
	if byMetric != nil && *byMetric != "" {
		metric = *byMetric
	}
	lim := 10
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	rows, err := r.BlueprintStatsSvc.Top(ctx, metric, lim)
	if err != nil {
		return nil, err
	}
	out := make([]model.BlueprintStats, 0, len(rows))
	for _, s := range rows {
		out = append(out, *blueprintStatsToGraphQL(s))
	}
	return out, nil
}
