package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"ironflyer/apps/orchestrator/internal/graph/model"
)

// StartCheckout is the resolver for the startCheckout field.
func (r *mutationResolver) StartCheckout(ctx context.Context, input model.StartCheckoutInput) (*model.StripeCheckoutSession, error) {
	panic(fmt.Errorf("not implemented: StartCheckout - startCheckout"))
}

// Plans is the resolver for the plans field.
func (r *queryResolver) Plans(ctx context.Context) ([]model.Plan, error) {
	panic(fmt.Errorf("not implemented: Plans - plans"))
}

// Rates is the resolver for the rates field.
func (r *queryResolver) Rates(ctx context.Context) ([]model.Rate, error) {
	panic(fmt.Errorf("not implemented: Rates - rates"))
}

// Vault is the resolver for the vault field.
func (r *queryResolver) Vault(ctx context.Context) (*model.VaultSnapshot, error) {
	panic(fmt.Errorf("not implemented: Vault - vault"))
}

// MyBudget is the resolver for the myBudget field.
func (r *queryResolver) MyBudget(ctx context.Context) (*model.BudgetSummary, error) {
	panic(fmt.Errorf("not implemented: MyBudget - myBudget"))
}
