package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"ironflyer/apps/orchestrator/internal/graph/model"
)

// AcceptInlineCompletion is the resolver for the acceptInlineCompletion field.
func (r *mutationResolver) AcceptInlineCompletion(ctx context.Context, requestID string) (*model.OperationResult, error) {
	panic(fmt.Errorf("not implemented: AcceptInlineCompletion - acceptInlineCompletion"))
}

// InlineCompletion is the resolver for the inlineCompletion field.
func (r *subscriptionResolver) InlineCompletion(ctx context.Context, input model.InlineInput) (<-chan model.InlineDelta, error) {
	panic(fmt.Errorf("not implemented: InlineCompletion - inlineCompletion"))
}
