package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/apps/orchestrator/internal/graph/model"
	"time"
)

// ProfitDashboard is the resolver for the profitDashboard field.
func (r *queryResolver) ProfitDashboard(ctx context.Context, since time.Time, until time.Time) (*model.ProfitDashboard, error) {
	if r.Dashboards == nil {
		return nil, gqlNotConfigured("dashboards")
	}
	d, err := r.Dashboards.Profit(ctx, since, until)
	if err != nil {
		return nil, err
	}
	return &model.ProfitDashboard{
		WindowStart:       d.WindowStart,
		WindowEnd:         d.WindowEnd,
		RevenueUsd:        d.RevenueUSD,
		ProviderCostUsd:   d.ProviderCostUSD,
		SandboxCostUsd:    d.SandboxCostUSD,
		OtherCostUsd:      d.OtherCostUSD,
		GrossProfitUsd:    d.GrossProfitUSD,
		GrossMarginPct:    d.GrossMarginPct,
		ActiveExecutions:  d.ActiveExecutions,
		BlockedExecutions: d.BlockedExecutions,
		RefundCount:       d.RefundCount,
		TopUpRate:         d.TopUpRate,
	}, nil
}

// ScaleDashboard is the resolver for the scaleDashboard field.
func (r *queryResolver) ScaleDashboard(ctx context.Context) (*model.ScaleDashboard, error) {
	if r.Dashboards == nil {
		return nil, gqlNotConfigured("dashboards")
	}
	d, err := r.Dashboards.ScaleDashboard(ctx)
	if err != nil {
		return nil, err
	}
	return &model.ScaleDashboard{
		ActiveExecutions:     d.ActiveExecutions,
		QueuedExecutions:     d.QueuedExecutions,
		QueueWaitSec:         d.QueueWaitSec,
		SandboxCapacity:      d.SandboxCapacity,
		WorkerUtilizationPct: d.WorkerUtilizationPct,
		ScaleHealth:          d.ScaleHealth,
	}, nil
}

// CohortDashboard is the resolver for the cohortDashboard field.
func (r *queryResolver) CohortDashboard(ctx context.Context, sinceMonth time.Time) (*model.CohortDashboard, error) {
	if r.Dashboards == nil {
		return nil, gqlNotConfigured("dashboards")
	}
	d, err := r.Dashboards.Cohort(ctx, sinceMonth)
	if err != nil {
		return nil, err
	}
	out := make([]model.Cohort, 0, len(d.Cohorts))
	for _, c := range d.Cohorts {
		out = append(out, model.Cohort{
			Month:                 c.Month,
			NewPayingUsers:        c.NewPayingUsers,
			SecondExecutionUsers:  c.SecondExecutionUsers,
			Day7RepeatUsers:       c.Day7RepeatUsers,
			Day30RepeatUsers:      c.Day30RepeatUsers,
			AvgSpendUsd:           c.AvgSpendUSD,
			GrossMarginPct:        c.GrossMarginPct,
			CompletionRate:        c.CompletionRate,
			RefundRate:            c.RefundRate,
			SupportTicketsPerExec: c.SupportTicketsPerExec,
		})
	}
	return &model.CohortDashboard{Cohorts: out}, nil
}

// BlueprintDashboard is the resolver for the blueprintDashboard field.
func (r *queryResolver) BlueprintDashboard(ctx context.Context) (*model.BlueprintDashboard, error) {
	if r.Dashboards == nil {
		return nil, gqlNotConfigured("dashboards")
	}
	d, err := r.Dashboards.BlueprintDashboard(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]model.DashboardBlueprintStats, 0, len(d.Blueprints))
	for _, b := range d.Blueprints {
		out = append(out, model.DashboardBlueprintStats{
			BlueprintID:        b.BlueprintID,
			Executions:         b.Executions,
			AvgRevenueUsd:      b.AvgRevenueUSD,
			AvgCostUsd:         b.AvgCostUSD,
			GrossMarginPct:     b.GrossMarginPct,
			PreviewSuccess:     b.PreviewSuccess,
			Refunds:            b.Refunds,
			RepairCount:        b.RepairCount,
			AvgCompletionScore: b.AvgCompletionScore,
		})
	}
	return &model.BlueprintDashboard{Blueprints: out}, nil
}
