package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"ironflyer/apps/orchestrator/internal/deploy"
	"ironflyer/apps/orchestrator/internal/graph/model"
	"time"
)

// PlanDeploy is the resolver for the planDeploy field.
func (r *mutationResolver) PlanDeploy(ctx context.Context, input model.PlanDeployInput) (*model.Deploy, error) {
	if r.DeploySvc == nil {
		return nil, gqlNotConfigured("deploy")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	tenant := tenantFor(u)
	in := deploy.PlanInput{
		TenantID:    tenant,
		ProjectID:   input.ProjectID,
		Target:      deploy.Target(input.Target),
		Environment: deploy.Environment(input.Environment),
		ArtifactRef: input.ArtifactRef,
		DiffHash:    input.DiffHash,
	}
	if input.ExecutionID != nil {
		in.ExecutionID = *input.ExecutionID
	}
	if input.BlueprintID != nil {
		in.BlueprintID = *input.BlueprintID
	}
	if input.Metadata != nil {
		// artifact_hash, when supplied inside metadata, is promoted by
		// the Service onto the deploys.artifact_hash column so audit
		// queries don't have to dig into the JSON blob.
		in.Metadata = map[string]any(input.Metadata)
	}
	d, err := r.DeploySvc.Plan(ctx, in)
	if err != nil {
		return nil, err
	}
	return deployToGraphQL(d), nil
}

// BuildDeployPreview is the resolver for the buildDeployPreview field.
func (r *mutationResolver) BuildDeployPreview(ctx context.Context, deployID string) (*model.Deploy, error) {
	if r.DeploySvc == nil {
		return nil, gqlNotConfigured("deploy")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	d, err := r.DeploySvc.BuildPreview(ctx, deployID)
	if err != nil {
		return nil, err
	}
	return deployToGraphQL(d), nil
}

// RequestDeployApproval is the resolver for the requestDeployApproval field.
func (r *mutationResolver) RequestDeployApproval(ctx context.Context, deployID string, expiresInMinutes *int) (*model.DeployApproval, error) {
	if r.DeploySvc == nil {
		return nil, gqlNotConfigured("deploy")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	by := deploy.UserRef{UserID: u.ID, TenantID: tenantFor(u)}
	var ttl time.Duration
	if expiresInMinutes != nil && *expiresInMinutes > 0 {
		ttl = time.Duration(*expiresInMinutes) * time.Minute
	}
	a, err := r.DeploySvc.RequestApproval(ctx, deployID, by, ttl)
	if err != nil {
		return nil, err
	}
	return approvalToGraphQL(a), nil
}

// DecideDeployApproval is the resolver for the decideDeployApproval field.
func (r *mutationResolver) DecideDeployApproval(ctx context.Context, approvalID string, approve bool, note *string) (*model.DeployApproval, error) {
	if r.DeploySvc == nil {
		return nil, gqlNotConfigured("deploy")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	by := deploy.UserRef{UserID: u.ID, TenantID: tenantFor(u)}
	decision := deploy.DecisionApprove
	if !approve {
		decision = deploy.DecisionReject
	}
	noteStr := ""
	if note != nil {
		noteStr = *note
	}
	a, err := r.DeploySvc.Decide(ctx, approvalID, by, decision, noteStr)
	if err != nil {
		return nil, err
	}
	return approvalToGraphQL(a), nil
}

// PromoteDeploy is the resolver for the promoteDeploy field.
func (r *mutationResolver) PromoteDeploy(ctx context.Context, deployID string) (*model.Deploy, error) {
	if r.DeploySvc == nil {
		return nil, gqlNotConfigured("deploy")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	d, err := r.DeploySvc.Promote(ctx, deployID)
	if err != nil {
		return nil, err
	}
	return deployToGraphQL(d), nil
}

// RollbackDeploy is the resolver for the rollbackDeploy field.
func (r *mutationResolver) RollbackDeploy(ctx context.Context, deployID string, reason string) (*model.Deploy, error) {
	if r.DeploySvc == nil {
		return nil, gqlNotConfigured("deploy")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	d, err := r.DeploySvc.Rollback(ctx, deployID, reason)
	if err != nil {
		return nil, err
	}
	return deployToGraphQL(d), nil
}

// CancelDeploy is the resolver for the cancelDeploy field.
func (r *mutationResolver) CancelDeploy(ctx context.Context, deployID string, reason string) (*model.Deploy, error) {
	if r.DeploySvc == nil {
		return nil, gqlNotConfigured("deploy")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	d, err := r.DeploySvc.Cancel(ctx, deployID, reason)
	if err != nil {
		return nil, err
	}
	return deployToGraphQL(d), nil
}

// Deploy is the resolver for the deploy field.
func (r *queryResolver) Deploy(ctx context.Context, id string) (*model.Deploy, error) {
	if r.DeploySvc == nil {
		return nil, gqlNotConfigured("deploy")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	d, err := r.DeploySvc.Get(ctx, id)
	if err != nil {
		if errors.Is(err, deploy.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	// Resolver-level tenant ownership check per
	// ARCHITECTURE_POLICY_SECURITY.md "Tenant Isolation": never
	// leak a deploy row across tenants. Mirror Get's 404 contract
	// when ownership mismatches.
	if d.TenantID != tenantFor(u) {
		return nil, nil
	}
	return deployToGraphQL(d), nil
}

// Deploys is the resolver for the deploys field.
func (r *queryResolver) Deploys(ctx context.Context, limit *int, offset *int) ([]model.Deploy, error) {
	if r.DeploySvc == nil {
		return nil, gqlNotConfigured("deploy")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	lim := 50
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	off := 0
	if offset != nil && *offset > 0 {
		off = *offset
	}
	rows, err := r.DeploySvc.List(ctx, tenantFor(u), lim, off)
	if err != nil {
		return nil, err
	}
	out := make([]model.Deploy, 0, len(rows))
	for i := range rows {
		out = append(out, *deployToGraphQL(rows[i]))
	}
	return out, nil
}

// PendingDeployApprovals is the resolver for the pendingDeployApprovals field.
func (r *queryResolver) PendingDeployApprovals(ctx context.Context) ([]model.DeployApproval, error) {
	if r.DeploySvc == nil {
		return nil, gqlNotConfigured("deploy")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := r.DeploySvc.PendingApprovals(ctx, tenantFor(u))
	if err != nil {
		return nil, err
	}
	out := make([]model.DeployApproval, 0, len(rows))
	for i := range rows {
		out = append(out, *approvalToGraphQL(rows[i]))
	}
	return out, nil
}

// DeployFeed is the resolver for the deployFeed field.
func (r *subscriptionResolver) DeployFeed(ctx context.Context, id string) (<-chan *model.DeployEvent, error) {
	if r.DeploySvc == nil {
		return nil, gqlNotConfigured("deploy")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	// Tenant check before opening the stream.
	d, err := r.DeploySvc.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	if d.TenantID != tenantFor(u) {
		return nil, nil
	}

	upstream, err := r.DeploySvc.SubscribeEvents(ctx, id)
	if err != nil {
		return nil, err
	}
	out := make(chan *model.DeployEvent, 16)
	go func() {
		defer close(out)
		for ev := range upstream {
			payload := ev.Payload
			if payload == nil {
				payload = map[string]any{}
			}
			select {
			case <-ctx.Done():
				return
			case out <- &model.DeployEvent{
				DeployID:  ev.DeployID,
				EventType: ev.EventType,
				Payload:   model.JSON(payload),
				CreatedAt: ev.CreatedAt,
			}:
			}
		}
	}()
	return out, nil
}
