package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"encoding/json"
	"ironflyer/apps/orchestrator/internal/domain"
	"ironflyer/apps/orchestrator/internal/execution"
	"ironflyer/apps/orchestrator/internal/graph/model"
	"ironflyer/apps/orchestrator/internal/ledger"
	"ironflyer/apps/orchestrator/internal/wallet"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// CreatePaidExecution is the resolver for the createPaidExecution field.
//
// Law 1: the wallet hold runs BEFORE the execution is admitted. If the
// hold fails the user gets INSUFFICIENT_FUNDS + a topUpURL; no
// execution row is written, no provider call is ever made.
func (r *mutationResolver) CreatePaidExecution(ctx context.Context, input model.CreatePaidExecutionInput) (*model.Execution, error) {
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	if r.WalletSvc == nil {
		return nil, gqlNotConfigured("wallet")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	tenant := tenantFor(u)
	budgetDec := decimal.NewFromFloat(input.BudgetUsd)

	// Hold first — law 1.
	if err := r.WalletSvc.Hold(ctx, tenant, budgetDec); err != nil {
		if err == wallet.ErrInsufficient {
			return nil, gqlInsufficientFunds(r.WebBaseURL)
		}
		return nil, err
	}

	// If the caller passed a blueprintID but no projectID, materialise a
	// project from the blueprint so the finisher has a workspace to
	// drive. Mirrors describeIdea's project-create step. The customer
	// promise of `createPaidExecution` is "I paid → finish my product";
	// without a project the engine has nothing to act on and the
	// execution stays admitted forever.
	autoProjectID := ""
	if (input.ProjectID == nil || strings.TrimSpace(*input.ProjectID) == "") && input.BlueprintID != nil && strings.TrimSpace(*input.BlueprintID) != "" && r.Projects != nil {
		bpID := strings.TrimSpace(*input.BlueprintID)
		title := "Execution " + time.Now().UTC().Format("2006-01-02 15:04")
		idea := ""
		if input.PromptSummary != nil {
			idea = strings.TrimSpace(*input.PromptSummary)
		}
		if idea == "" {
			idea = "Synthesised from blueprint " + bpID
		}
		now := time.Now().UTC()
		project, perr := r.Projects.Create(domain.Project{
			ID:          uuid.NewString(),
			Name:        title,
			Description: idea,
			Status:      "ready",
			OwnerID:     u.ID,
			Spec:        domain.ProductSpec{Idea: idea},
			Files:       []domain.FileNode{},
			Gates:       map[domain.GateName]domain.GateState{},
			CreatedAt:   now,
			UpdatedAt:   now,
		})
		if perr != nil {
			_ = r.WalletSvc.Release(ctx, tenant, budgetDec)
			return nil, perr
		}
		autoProjectID = project.ID
	}

	createIn := execution.CreateInput{
		TenantID:  tenant,
		BudgetUSD: budgetDec,
	}
	if input.ProjectID != nil && strings.TrimSpace(*input.ProjectID) != "" {
		createIn.ProjectID = *input.ProjectID
	} else if autoProjectID != "" {
		createIn.ProjectID = autoProjectID
	}
	if input.BlueprintID != nil {
		createIn.BlueprintID = *input.BlueprintID
	}
	if input.PromptSummary != nil {
		createIn.PromptSummary = *input.PromptSummary
	}
	if input.StopLossUsd != nil {
		stop := decimal.NewFromFloat(*input.StopLossUsd)
		createIn.StopLossUSD = &stop
	}
	if input.Metadata != nil {
		if b, err := json.Marshal(input.Metadata); err == nil {
			createIn.Metadata = b
		}
	}

	exec, err := r.ExecutionSvc.Create(ctx, createIn)
	if err != nil {
		// Roll the hold back so a failed Create doesn't leak the
		// reserved amount.
		_ = r.WalletSvc.Release(ctx, tenant, budgetDec)
		return nil, err
	}
	// Defensive: Create must always return an ID. If it doesn't, abort
	// before we try to Admit/Start with an empty UUID and crash the
	// Postgres FSM in tx_select_for_update (Bug #7).
	if strings.TrimSpace(exec.ID) == "" {
		_ = r.WalletSvc.Release(ctx, tenant, budgetDec)
		r.Logger.Error().Msg("createPaidExecution: execution.Create returned empty ID")
		return nil, gqlNotConfigured("execution")
	}
	if err := r.ExecutionSvc.Admit(ctx, exec.ID); err != nil {
		_ = r.WalletSvc.Release(ctx, tenant, budgetDec)
		return nil, err
	}

	// Stamp reserved_usd on the execution row so the settler can compute
	// release = reserved - spent when the execution closes. Without this
	// the wallet's tenant-wide hold leaks on every paid execution: the
	// settler's release math reads exec.ReservedUSD (always 0) instead
	// of the actual wallet hold and never calls Wallet.Release.
	if err := r.ExecutionSvc.Reserve(ctx, exec.ID, budgetDec); err != nil {
		r.Logger.Warn().Err(err).Str("execution_id", exec.ID).Msg("createPaidExecution: execution.Reserve failed; hold may leak on close")
	}

	// V22 customer promise: a paid execution must actually run, not just
	// admit. Start the FSM and fire-and-forget the finisher engine so
	// the wow-loop output materialises (preview URL, changed files, gate
	// + security + cost reports, next best action). Errors are logged
	// but do not fail the resolver — the hold + admit already succeeded
	// and the user's money is reserved; the engine surfaces failure
	// through the executionFeed subscription.
	if err := r.ExecutionSvc.Start(ctx, exec.ID); err != nil {
		r.Logger.Warn().Err(err).Str("execution_id", exec.ID).Msg("createPaidExecution: execution.Start failed after admit")
	}
	if r.Engine != nil && createIn.ProjectID != "" {
		go func(projID, execID string) {
			bgCtx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
			defer cancel()
			if _, runErr := r.Engine.Run(bgCtx, projID); runErr != nil {
				r.Logger.Warn().Err(runErr).Str("project_id", projID).Str("execution_id", execID).Msg("createPaidExecution: finisher run failed")
			}
		}(createIn.ProjectID, exec.ID)
	}

	// Record the reservation in the ledger so the per-execution
	// timeline shows where the budget came from.
	if r.LedgerSvc != nil {
		tenantUUID := tenantUUIDFor(tenant)
		execUUID, perr := uuid.Parse(exec.ID)
		if perr == nil {
			_, _ = r.LedgerSvc.Write(ctx, ledger.Entry{
				TenantID:    tenantUUID,
				ExecutionID: &execUUID,
				EntryType:   ledger.EntryCreditReservation,
				Direction:   ledger.DebitDirection,
				AmountUSD:   budgetDec,
				Billable:    false,
				Metadata: map[string]any{
					"created_via": "createPaidExecution",
				},
			})
		}
	}

	// Refresh the row so the response carries admitted_at.
	if refreshed, err := r.ExecutionSvc.Get(ctx, exec.ID); err == nil {
		exec = refreshed
	}
	return executionToGraphQL(exec), nil
}

// StopExecution is the resolver for the stopExecution field.
func (r *mutationResolver) StopExecution(ctx context.Context, id string, reason string) (*model.Execution, error) {
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	if err := r.ExecutionSvc.Stop(ctx, id, reason); err != nil {
		return nil, err
	}
	// V22 terminal close-out: release the unused hold, debit the
	// actualised spend, write the credit_release + platform_margin
	// ledger entries, record the blueprint run. Errors are logged
	// but do not fail the stop — the operator already pressed the
	// button.
	if r.ExecutionSettler != nil {
		if settlement, err := r.ExecutionSettler.Close(ctx, id, execution.StatusStopped); err != nil {
			r.Logger.Warn().Err(err).Str("execution_id", id).Msg("execution settler on stop")
		} else {
			r.Logger.Debug().Str("execution_id", id).
				Str("spent_usd", settlement.SpentUSD.String()).
				Str("release_usd", settlement.ReleaseUSD.String()).
				Str("margin_usd", settlement.MarginUSD.String()).
				Msg("execution settled on stop")
		}
	} else if err := commitWalletForExecution(ctx, r, id); err != nil {
		// Back-compat path for partial deployments without the V22
		// settler wired; keeps the historical resolver behaviour.
		r.Logger.Warn().Err(err).Str("execution_id", id).Msg("commit wallet on stop")
	}
	exec, err := r.ExecutionSvc.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return executionToGraphQL(exec), nil
}

// RefundExecution is the resolver for the refundExecution field.
func (r *mutationResolver) RefundExecution(ctx context.Context, id string, amountUsd *float64, reason *string) (*model.Execution, error) {
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	exec, err := r.ExecutionSvc.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	amt := exec.SpentUSD
	if amountUsd != nil && *amountUsd > 0 {
		amt = decimal.NewFromFloat(*amountUsd)
	}
	if err := r.ExecutionSvc.Refund(ctx, id, amt); err != nil {
		return nil, err
	}
	// Credit the wallet back and write a refund ledger entry.
	if r.WalletSvc != nil {
		// Refunds add to balance; we never had a hold beyond the
		// already-debited portion, so TopUp is the right primitive
		// (it's the only "balance += amount" operation on Wallet).
		_ = r.WalletSvc.TopUp(ctx, exec.TenantID, amt, "refund:"+id)
	}
	if r.LedgerSvc != nil {
		execUUID, perr := uuid.Parse(id)
		if perr == nil {
			reasonStr := ""
			if reason != nil {
				reasonStr = *reason
			}
			_, _ = r.LedgerSvc.Write(ctx, ledger.Entry{
				TenantID:    tenantUUIDFor(exec.TenantID),
				ExecutionID: &execUUID,
				EntryType:   ledger.EntryRefund,
				Direction:   ledger.CreditDirection,
				AmountUSD:   amt,
				Metadata:    map[string]any{"reason": reasonStr},
			})
		}
	}
	refreshed, err := r.ExecutionSvc.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return executionToGraphQL(refreshed), nil
}

// Execution is the resolver for the execution field.
func (r *queryResolver) Execution(ctx context.Context, id string) (*model.Execution, error) {
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	exec, err := r.ExecutionSvc.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return executionToGraphQL(exec), nil
}

// Executions is the resolver for the executions field.
func (r *queryResolver) Executions(ctx context.Context, limit *int, offset *int) ([]model.Execution, error) {
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	lim := 50
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	off := 0
	if offset != nil && *offset > 0 {
		off = *offset
	}
	rows, err := r.ExecutionSvc.ListByTenant(ctx, tenantFor(u), lim, off)
	if err != nil {
		return nil, err
	}
	out := make([]model.Execution, 0, len(rows))
	for i := range rows {
		out = append(out, *executionToGraphQL(rows[i]))
	}
	return out, nil
}

// ProjectExecutions is the resolver for the projectExecutions field.
func (r *queryResolver) ProjectExecutions(ctx context.Context, projectID string, limit *int, offset *int) ([]model.Execution, error) {
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	// Authorise the project — non-owner / non-public projects must
	// 404 just like the existing requireProjectAccess pathway. We
	// reuse the projects store directly because the call sits inside
	// the same package boundary.
	if r.Resolver.Projects != nil {
		project, err := r.Resolver.Projects.Get(projectID)
		if err != nil {
			return nil, err
		}
		if !project.IsAccessibleBy(u.ID) {
			return nil, errUnauthenticated
		}
	}
	lim := 50
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	off := 0
	if offset != nil && *offset > 0 {
		off = *offset
	}
	rows, err := r.ExecutionSvc.ListByTenantAndProject(ctx, tenantFor(u), projectID, lim, off)
	if err != nil {
		return nil, err
	}
	out := make([]model.Execution, 0, len(rows))
	for i := range rows {
		out = append(out, *executionToGraphQL(rows[i]))
	}
	return out, nil
}

// ExecutionFeed is the resolver for the executionFeed field.
func (r *subscriptionResolver) ExecutionFeed(ctx context.Context, id string) (<-chan *model.ExecutionEvent, error) {
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	upstream, err := r.ExecutionSvc.SubscribeEvents(ctx, id)
	if err != nil {
		return nil, err
	}
	out := make(chan *model.ExecutionEvent, 16)
	go func() {
		defer close(out)
		for ev := range upstream {
			var payload map[string]any
			if len(ev.Payload) > 0 {
				_ = json.Unmarshal(ev.Payload, &payload)
			}
			select {
			case <-ctx.Done():
				return
			case out <- &model.ExecutionEvent{
				ExecutionID: ev.ExecutionID,
				EventType:   ev.EventType,
				Payload:     model.JSON(payload),
				CreatedAt:   ev.CreatedAt,
			}:
			}
		}
	}()
	return out, nil
}
