package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"encoding/json"
	"ironflyer/apps/orchestrator/internal/execution"
	"ironflyer/apps/orchestrator/internal/graph/model"
	"ironflyer/apps/orchestrator/internal/ledger"
	"ironflyer/apps/orchestrator/internal/wallet"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// CreatePaidExecution is the resolver for the createPaidExecution field.
//
// Law 1: the wallet hold runs BEFORE the execution is admitted. If the
// hold fails the user gets INSUFFICIENT_FUNDS + a topUpURL; no
// execution row is written, no provider call is ever made.
func (r *mutationResolver) CreatePaidExecution(ctx context.Context, input model.CreatePaidExecutionInput) (*model.Execution, error) {
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	if r.WalletSvc == nil {
		return nil, gqlNotConfigured("wallet")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	tenant := tenantFor(u)
	budgetDec := decimal.NewFromFloat(input.BudgetUsd)

	// Hold first — law 1.
	if err := r.WalletSvc.Hold(ctx, tenant, budgetDec); err != nil {
		if err == wallet.ErrInsufficient {
			return nil, gqlInsufficientFunds(r.WebBaseURL)
		}
		return nil, err
	}

	createIn := execution.CreateInput{
		TenantID:  tenant,
		BudgetUSD: budgetDec,
	}
	if input.ProjectID != nil {
		createIn.ProjectID = *input.ProjectID
	}
	if input.BlueprintID != nil {
		createIn.BlueprintID = *input.BlueprintID
	}
	if input.PromptSummary != nil {
		createIn.PromptSummary = *input.PromptSummary
	}
	if input.StopLossUsd != nil {
		stop := decimal.NewFromFloat(*input.StopLossUsd)
		createIn.StopLossUSD = &stop
	}
	if input.Metadata != nil {
		if b, err := json.Marshal(input.Metadata); err == nil {
			createIn.Metadata = b
		}
	}

	exec, err := r.ExecutionSvc.Create(ctx, createIn)
	if err != nil {
		// Roll the hold back so a failed Create doesn't leak the
		// reserved amount.
		_ = r.WalletSvc.Release(ctx, tenant, budgetDec)
		return nil, err
	}
	if err := r.ExecutionSvc.Admit(ctx, exec.ID); err != nil {
		_ = r.WalletSvc.Release(ctx, tenant, budgetDec)
		return nil, err
	}

	// Record the reservation in the ledger so the per-execution
	// timeline shows where the budget came from.
	if r.LedgerSvc != nil {
		tenantUUID := tenantUUIDFor(tenant)
		execUUID, perr := uuid.Parse(exec.ID)
		if perr == nil {
			_, _ = r.LedgerSvc.Write(ctx, ledger.Entry{
				TenantID:    tenantUUID,
				ExecutionID: &execUUID,
				EntryType:   ledger.EntryCreditReservation,
				Direction:   ledger.DebitDirection,
				AmountUSD:   budgetDec,
				Billable:    false,
				Metadata: map[string]any{
					"created_via": "createPaidExecution",
				},
			})
		}
	}

	// Refresh the row so the response carries admitted_at.
	if refreshed, err := r.ExecutionSvc.Get(ctx, exec.ID); err == nil {
		exec = refreshed
	}
	return executionToGraphQL(exec), nil
}

// StopExecution is the resolver for the stopExecution field.
func (r *mutationResolver) StopExecution(ctx context.Context, id string, reason string) (*model.Execution, error) {
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	if err := r.ExecutionSvc.Stop(ctx, id, reason); err != nil {
		return nil, err
	}
	// V22 terminal close-out: release the unused hold, debit the
	// actualised spend, write the credit_release + platform_margin
	// ledger entries, record the blueprint run. Errors are logged
	// but do not fail the stop — the operator already pressed the
	// button.
	if r.ExecutionSettler != nil {
		if settlement, err := r.ExecutionSettler.Close(ctx, id, execution.StatusStopped); err != nil {
			r.Logger.Warn().Err(err).Str("execution_id", id).Msg("execution settler on stop")
		} else {
			r.Logger.Debug().Str("execution_id", id).
				Str("spent_usd", settlement.SpentUSD.String()).
				Str("release_usd", settlement.ReleaseUSD.String()).
				Str("margin_usd", settlement.MarginUSD.String()).
				Msg("execution settled on stop")
		}
	} else if err := commitWalletForExecution(ctx, r, id); err != nil {
		// Back-compat path for partial deployments without the V22
		// settler wired; keeps the historical resolver behaviour.
		r.Logger.Warn().Err(err).Str("execution_id", id).Msg("commit wallet on stop")
	}
	exec, err := r.ExecutionSvc.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return executionToGraphQL(exec), nil
}

// RefundExecution is the resolver for the refundExecution field.
func (r *mutationResolver) RefundExecution(ctx context.Context, id string, amountUsd *float64, reason *string) (*model.Execution, error) {
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	exec, err := r.ExecutionSvc.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	amt := exec.SpentUSD
	if amountUsd != nil && *amountUsd > 0 {
		amt = decimal.NewFromFloat(*amountUsd)
	}
	if err := r.ExecutionSvc.Refund(ctx, id, amt); err != nil {
		return nil, err
	}
	// Credit the wallet back and write a refund ledger entry.
	if r.WalletSvc != nil {
		// Refunds add to balance; we never had a hold beyond the
		// already-debited portion, so TopUp is the right primitive
		// (it's the only "balance += amount" operation on Wallet).
		_ = r.WalletSvc.TopUp(ctx, exec.TenantID, amt, "refund:"+id)
	}
	if r.LedgerSvc != nil {
		execUUID, perr := uuid.Parse(id)
		if perr == nil {
			reasonStr := ""
			if reason != nil {
				reasonStr = *reason
			}
			_, _ = r.LedgerSvc.Write(ctx, ledger.Entry{
				TenantID:    tenantUUIDFor(exec.TenantID),
				ExecutionID: &execUUID,
				EntryType:   ledger.EntryRefund,
				Direction:   ledger.CreditDirection,
				AmountUSD:   amt,
				Metadata:    map[string]any{"reason": reasonStr},
			})
		}
	}
	refreshed, err := r.ExecutionSvc.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return executionToGraphQL(refreshed), nil
}

// Execution is the resolver for the execution field.
func (r *queryResolver) Execution(ctx context.Context, id string) (*model.Execution, error) {
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	exec, err := r.ExecutionSvc.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return executionToGraphQL(exec), nil
}

// Executions is the resolver for the executions field.
func (r *queryResolver) Executions(ctx context.Context, limit *int, offset *int) ([]model.Execution, error) {
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	lim := 50
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	off := 0
	if offset != nil && *offset > 0 {
		off = *offset
	}
	rows, err := r.ExecutionSvc.ListByTenant(ctx, tenantFor(u), lim, off)
	if err != nil {
		return nil, err
	}
	out := make([]model.Execution, 0, len(rows))
	for i := range rows {
		out = append(out, *executionToGraphQL(rows[i]))
	}
	return out, nil
}

// ProjectExecutions is the resolver for the projectExecutions field.
func (r *queryResolver) ProjectExecutions(ctx context.Context, projectID string, limit *int, offset *int) ([]model.Execution, error) {
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	// Authorise the project — non-owner / non-public projects must
	// 404 just like the existing requireProjectAccess pathway. We
	// reuse the projects store directly because the call sits inside
	// the same package boundary.
	if r.Resolver.Projects != nil {
		project, err := r.Resolver.Projects.Get(projectID)
		if err != nil {
			return nil, err
		}
		if !project.IsAccessibleBy(u.ID) {
			return nil, errUnauthenticated
		}
	}
	lim := 50
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	off := 0
	if offset != nil && *offset > 0 {
		off = *offset
	}
	rows, err := r.ExecutionSvc.ListByTenantAndProject(ctx, tenantFor(u), projectID, lim, off)
	if err != nil {
		return nil, err
	}
	out := make([]model.Execution, 0, len(rows))
	for i := range rows {
		out = append(out, *executionToGraphQL(rows[i]))
	}
	return out, nil
}

// ExecutionFeed is the resolver for the executionFeed field.
func (r *subscriptionResolver) ExecutionFeed(ctx context.Context, id string) (<-chan *model.ExecutionEvent, error) {
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	upstream, err := r.ExecutionSvc.SubscribeEvents(ctx, id)
	if err != nil {
		return nil, err
	}
	out := make(chan *model.ExecutionEvent, 16)
	go func() {
		defer close(out)
		for ev := range upstream {
			var payload map[string]any
			if len(ev.Payload) > 0 {
				_ = json.Unmarshal(ev.Payload, &payload)
			}
			select {
			case <-ctx.Done():
				return
			case out <- &model.ExecutionEvent{
				ExecutionID: ev.ExecutionID,
				EventType:   ev.EventType,
				Payload:     model.JSON(payload),
				CreatedAt:   ev.CreatedAt,
			}:
			}
		}
	}()
	return out, nil
}
