package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/apps/orchestrator/internal/forecast"
	"ironflyer/apps/orchestrator/internal/graph/model"
)

// EstimateExecutionCost is the resolver for the estimateExecutionCost
// field. It forwards to the wired Forecaster (memory or postgres)
// and converts decimal money into Float for the GraphQL boundary.
//
// The breakdown map is returned as a JSON scalar (model.JSON) keyed
// by component name ("provider", "sandbox", "storage", "deploy").
func (r *queryResolver) EstimateExecutionCost(ctx context.Context, input model.EstimateInput) (*model.CostEstimate, error) {
	if r.Forecaster == nil {
		return nil, gqlNotConfigured("forecast")
	}
	user, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	tenant := tenantFor(user)

	in := forecast.EstimateInput{
		TenantID: tenant,
	}
	if input.BlueprintID != nil {
		in.BlueprintID = *input.BlueprintID
	}
	if input.Capabilities != nil {
		in.Capabilities = input.Capabilities
	}
	if input.EstimatedDurationSec != nil {
		in.EstimatedDurationSec = *input.EstimatedDurationSec
	}
	if input.PromptSummary != nil {
		in.PromptSummary = *input.PromptSummary
	}

	est, err := r.Forecaster.Estimate(ctx, in)
	if err != nil {
		return nil, err
	}

	breakdown := make(model.JSON, len(est.Breakdown))
	for k, v := range est.Breakdown {
		breakdown[k] = floatOfDecimal(v)
	}

	out := &model.CostEstimate{
		LowUsd:      floatOfDecimal(est.LowUSD),
		MedianUsd:   floatOfDecimal(est.MedianUSD),
		HighUsd:     floatOfDecimal(est.HighUSD),
		P95usd:      floatOfDecimal(est.P95USD),
		Breakdown:   breakdown,
		Confidence:  est.Confidence,
		BasedOnRuns: est.BasedOnRuns,
	}
	if est.Caveat != "" {
		c := est.Caveat
		out.Caveat = &c
	}
	return out, nil
}
