package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/apps/orchestrator/internal/domain"
	"ironflyer/apps/orchestrator/internal/graph/model"
	"ironflyer/apps/orchestrator/internal/store"
	"strings"
)

// RerunGate executes one named gate against the project's current
// tree and returns its verdict. Goes through r.Engine so the gate
// run is audited + emits the same events the finisher emits on a
// full Run.
func (r *mutationResolver) RerunGate(ctx context.Context, input model.RerunGateInput) (*model.GateVerdict, error) {
	if r.Engine == nil {
		return nil, gqlNotConfigured("finisher")
	}
	if r.Resolver.Projects == nil {
		return nil, gqlNotConfigured("projects")
	}
	p, err := r.Resolver.Projects.Get(input.ProjectID)
	if err != nil {
		return nil, err
	}
	userID := ""
	if u, err := currentUser(ctx); err == nil {
		userID = u.ID
	}
	if !p.IsAccessibleBy(userID) {
		return nil, store.ErrNotFound
	}
	gs, err := r.Engine.RunGate(ctx, input.ProjectID, input.Gate)
	if err != nil {
		return nil, err
	}
	v := gateStateToGraphQL(gs.Name, gs)
	return &v, nil
}

// Gates returns the verdict for every registered gate on the
// project. Optional `sub` scopes issues to entries whose path starts
// with the named subproject directory.
func (r *queryResolver) Gates(ctx context.Context, projectID string, sub *string) ([]model.GateVerdict, error) {
	if r.Resolver.Projects == nil {
		return nil, gqlNotConfigured("projects")
	}
	p, err := r.Resolver.Projects.Get(projectID)
	if err != nil {
		if err == store.ErrNotFound {
			return nil, nil
		}
		return nil, err
	}
	userID := ""
	if u, err := currentUser(ctx); err == nil {
		userID = u.ID
	}
	if !p.IsAccessibleBy(userID) {
		return nil, nil
	}
	out := make([]model.GateVerdict, 0, len(domain.AllGates()))
	for _, name := range domain.AllGates() {
		gs, ok := p.Gates[name]
		if !ok {
			gs = domain.GateState{Name: name, Status: domain.GateStatusPending}
		}
		v := gateStateToGraphQL(name, gs)
		if sub != nil && strings.TrimSpace(*sub) != "" {
			v.Issues = filterIssuesBySubproject(v.Issues, p, *sub)
		}
		out = append(out, v)
	}
	return out, nil
}

// Gate returns a single verdict. Returns nil (not an error) when the
// project exists but the gate hasn't run yet OR the caller can't
// see the project.
func (r *queryResolver) Gate(ctx context.Context, projectID string, gate string) (*model.GateVerdict, error) {
	if r.Resolver.Projects == nil {
		return nil, gqlNotConfigured("projects")
	}
	p, err := r.Resolver.Projects.Get(projectID)
	if err != nil {
		if err == store.ErrNotFound {
			return nil, nil
		}
		return nil, err
	}
	userID := ""
	if u, err := currentUser(ctx); err == nil {
		userID = u.ID
	}
	if !p.IsAccessibleBy(userID) {
		return nil, nil
	}
	name := domain.GateName(gate)
	gs, ok := p.Gates[name]
	if !ok {
		gs = domain.GateState{Name: name, Status: domain.GateStatusPending}
	}
	v := gateStateToGraphQL(name, gs)
	return &v, nil
}
