package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"ironflyer/apps/orchestrator/internal/graph/model"
)

// RerunGate is the resolver for the rerunGate field.
func (r *mutationResolver) RerunGate(ctx context.Context, input model.RerunGateInput) (*model.GateVerdict, error) {
	panic(fmt.Errorf("not implemented: RerunGate - rerunGate"))
}

// Gates is the resolver for the gates field.
func (r *queryResolver) Gates(ctx context.Context, projectID string, sub *string) ([]model.GateVerdict, error) {
	panic(fmt.Errorf("not implemented: Gates - gates"))
}

// Gate is the resolver for the gate field.
func (r *queryResolver) Gate(ctx context.Context, projectID string, gate string) (*model.GateVerdict, error) {
	panic(fmt.Errorf("not implemented: Gate - gate"))
}
