package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/apps/orchestrator/internal/graph/model"
	"ironflyer/apps/orchestrator/internal/patch"
	"strings"
	"time"
)

func patchToGraphQL(p patch.Patch) *model.Patch {
	out := &model.Patch{
		ID:        p.ID,
		ProjectID: p.ProjectID,
		Status:    model.PatchStatus(strings.ToUpper(string(p.Status))),
		CreatedAt: p.CreatedAt,
		AppliedAt: p.AppliedAt,
	}
	if p.Title != "" {
		t := p.Title
		out.Title = &t
	}
	if p.Summary != "" {
		s := p.Summary
		out.Summary = &s
	}
	if p.Author != "" {
		a := p.Author
		out.Author = &a
	}
	if p.StageID != "" {
		sid := p.StageID
		out.StageID = &sid
	}
	for _, fc := range p.Changes {
		ch := model.PatchChange{
			Op:   model.PatchChangeOp(strings.ToUpper(string(fc.Op))),
			Path: fc.Path,
		}
		if fc.Content != "" {
			c := fc.Content
			ch.Content = &c
		}
		if fc.Anchor != "" {
			a := fc.Anchor
			ch.Anchor = &a
		}
		if fc.Replacement != "" {
			r := fc.Replacement
			ch.Replacement = &r
		}
		if fc.Symbol != nil && fc.Symbol.Name != "" {
			s := fc.Symbol.Name
			ch.Symbol = &s
		}
		out.Changes = append(out.Changes, ch)
	}
	for _, c := range p.Conflicts {
		out.Conflicts = append(out.Conflicts, model.PatchConflict{
			Path: c.Path, Base: c.Base, Ours: c.Ours, Theirs: c.Theirs, Markers: c.Markers,
		})
	}
	return out
}

func patchStageToGraphQL(s patch.PatchStage) *model.PatchStage {
	out := &model.PatchStage{
		ID:        s.ID,
		ProjectID: s.ProjectID,
		Name:      s.Name,
		PatchIds:  s.PatchIDs,
		Status:    model.PatchStageStatus(strings.ToUpper(string(s.Status))),
		CreatedAt: s.CreatedAt,
		UpdatedAt: s.UpdatedAt,
	}
	if s.Description != "" {
		d := s.Description
		out.Description = &d
	}
	if s.RejectionReason != "" {
		r := s.RejectionReason
		out.RejectionReason = &r
	}
	return out
}

// ProposePatch is the resolver for the proposePatch field.
func (r *mutationResolver) ProposePatch(ctx context.Context, input model.ProposePatchInput) (*model.Patch, error) {
	if r.Patches == nil {
		return nil, gqlNotConfigured("patches")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	p := patch.Patch{
		ProjectID: input.ProjectID,
		CreatedAt: time.Now().UTC(),
	}
	if input.Title != nil {
		p.Title = *input.Title
	}
	if input.Summary != nil {
		p.Summary = *input.Summary
	}
	if input.Author != nil {
		p.Author = *input.Author
	}
	for _, ch := range input.Changes {
		fc := patch.FileChange{
			Op:   patch.Op(strings.ToLower(string(ch.Op))),
			Path: ch.Path,
		}
		if ch.Content != nil {
			fc.Content = *ch.Content
		}
		if ch.Anchor != nil {
			fc.Anchor = *ch.Anchor
		}
		if ch.Replacement != nil {
			fc.Replacement = *ch.Replacement
		}
		if ch.Symbol != nil && *ch.Symbol != "" {
			fc.Symbol = &patch.SymbolRef{Name: *ch.Symbol}
		}
		p.Changes = append(p.Changes, fc)
	}
	proposed, err := r.Patches.Propose(p)
	if err != nil {
		return nil, err
	}
	return patchToGraphQL(proposed), nil
}

// ApplyPatch is the resolver for the applyPatch field.
func (r *mutationResolver) ApplyPatch(ctx context.Context, patchID string) (*model.Patch, error) {
	if r.Patches == nil {
		return nil, gqlNotConfigured("patches")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	applied, err := r.Patches.ApplyCtx(ctx, patchID)
	if err != nil {
		return nil, err
	}
	return patchToGraphQL(applied), nil
}

// RollbackPatch is the resolver for the rollbackPatch field.
func (r *mutationResolver) RollbackPatch(ctx context.Context, patchID string) (model.JSON, error) {
	if r.Patches == nil {
		return nil, gqlNotConfigured("patches")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	p, err := r.Patches.Get(patchID)
	if err != nil {
		return nil, err
	}
	snap, err := r.Patches.Rollback(p.ProjectID, patchID)
	if err != nil {
		return nil, err
	}
	return model.JSON{"snapshotID": snap.ID, "createdAt": snap.CreatedAt}, nil
}

// ProposeSymbolPatch is the resolver for the proposeSymbolPatch field.
func (r *mutationResolver) ProposeSymbolPatch(ctx context.Context, input model.SymbolPatchInput) (*model.Patch, error) {
	if r.Patches == nil {
		return nil, gqlNotConfigured("patches")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	return nil, gqlNotConfigured("symbol-patches: not wired in resolver; use ProposePatch with the symbol op")
}

// RenameSymbol is the resolver for the renameSymbol field.
func (r *mutationResolver) RenameSymbol(ctx context.Context, input model.RenameSymbolInput) (*model.Patch, error) {
	if r.Patches == nil {
		return nil, gqlNotConfigured("patches")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	return nil, gqlNotConfigured("rename-symbol: not wired in resolver")
}

// CreateStage is the resolver for the createStage field.
func (r *mutationResolver) CreateStage(ctx context.Context, input model.CreateStageInput) (*model.PatchStage, error) {
	if r.Patches == nil {
		return nil, gqlNotConfigured("patches")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	desc := ""
	if input.Description != nil {
		desc = *input.Description
	}
	stage, err := r.Patches.CreateStage(input.ProjectID, input.Name, desc, input.PatchIds)
	if err != nil {
		return nil, err
	}
	return patchStageToGraphQL(stage), nil
}

// ApplyStage is the resolver for the applyStage field.
func (r *mutationResolver) ApplyStage(ctx context.Context, stageID string) (model.JSON, error) {
	if r.Patches == nil {
		return nil, gqlNotConfigured("patches")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	res, err := r.Patches.ApplyStage(stageID)
	if err != nil {
		return nil, err
	}
	outcomes := make([]map[string]any, 0, len(res.Outcomes))
	for _, o := range res.Outcomes {
		outcomes = append(outcomes, map[string]any{
			"patchId": o.PatchID,
			"status":  string(o.Status),
			"error":   o.Error,
		})
	}
	return model.JSON{
		"stageId":  res.Stage.ID,
		"status":   string(res.Stage.Status),
		"outcomes": outcomes,
	}, nil
}

// RejectStage is the resolver for the rejectStage field.
func (r *mutationResolver) RejectStage(ctx context.Context, stageID string, reason *string) (*model.PatchStage, error) {
	if r.Patches == nil {
		return nil, gqlNotConfigured("patches")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	r2 := ""
	if reason != nil {
		r2 = *reason
	}
	stage, err := r.Patches.RejectStage(stageID, r2)
	if err != nil {
		return nil, err
	}
	return patchStageToGraphQL(stage), nil
}

// Patches is the resolver for the patches field.
func (r *queryResolver) Patches(ctx context.Context, projectID string) ([]model.Patch, error) {
	if r.Resolver.Patches == nil {
		return nil, gqlNotConfigured("patches")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	list := r.Resolver.Patches.List(projectID)
	out := make([]model.Patch, 0, len(list))
	for _, p := range list {
		out = append(out, *patchToGraphQL(p))
	}
	return out, nil
}

// Patch is the resolver for the patch field.
func (r *queryResolver) Patch(ctx context.Context, id string) (*model.Patch, error) {
	if r.Resolver.Patches == nil {
		return nil, gqlNotConfigured("patches")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	p, err := r.Resolver.Patches.Get(id)
	if err != nil {
		return nil, err
	}
	return patchToGraphQL(p), nil
}

// PatchSnapshots is the resolver for the patchSnapshots field.
func (r *queryResolver) PatchSnapshots(ctx context.Context, projectID string) (model.JSON, error) {
	if r.Resolver.Patches == nil {
		return nil, gqlNotConfigured("patches")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	snaps := r.Resolver.Patches.Snapshots(projectID)
	out := make([]map[string]any, 0, len(snaps))
	for _, s := range snaps {
		out = append(out, map[string]any{
			"id":        s.ID,
			"patchId":   s.PatchID,
			"title":     s.Title,
			"createdAt": s.CreatedAt,
		})
	}
	return model.JSON{"snapshots": out}, nil
}

// Stages is the resolver for the stages field.
func (r *queryResolver) Stages(ctx context.Context, projectID string) ([]model.PatchStage, error) {
	if r.Resolver.Patches == nil {
		return nil, gqlNotConfigured("patches")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	stages, err := r.Resolver.Patches.ListStages(projectID)
	if err != nil {
		return nil, err
	}
	out := make([]model.PatchStage, 0, len(stages))
	for _, s := range stages {
		out = append(out, *patchStageToGraphQL(s))
	}
	return out, nil
}

// Stage is the resolver for the stage field.
func (r *queryResolver) Stage(ctx context.Context, id string) (*model.PatchStage, error) {
	if r.Resolver.Patches == nil {
		return nil, gqlNotConfigured("patches")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	stage, ok, err := r.Resolver.Patches.GetStage(id)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, nil
	}
	return patchStageToGraphQL(stage), nil
}
