package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"ironflyer/apps/orchestrator/internal/graph/model"
)

// ProposePatch is the resolver for the proposePatch field.
func (r *mutationResolver) ProposePatch(ctx context.Context, input model.ProposePatchInput) (*model.Patch, error) {
	panic(fmt.Errorf("not implemented: ProposePatch - proposePatch"))
}

// ApplyPatch is the resolver for the applyPatch field.
func (r *mutationResolver) ApplyPatch(ctx context.Context, patchID string) (*model.Patch, error) {
	panic(fmt.Errorf("not implemented: ApplyPatch - applyPatch"))
}

// RollbackPatch is the resolver for the rollbackPatch field.
func (r *mutationResolver) RollbackPatch(ctx context.Context, patchID string) (model.JSON, error) {
	panic(fmt.Errorf("not implemented: RollbackPatch - rollbackPatch"))
}

// ProposeSymbolPatch is the resolver for the proposeSymbolPatch field.
func (r *mutationResolver) ProposeSymbolPatch(ctx context.Context, input model.SymbolPatchInput) (*model.Patch, error) {
	panic(fmt.Errorf("not implemented: ProposeSymbolPatch - proposeSymbolPatch"))
}

// RenameSymbol is the resolver for the renameSymbol field.
func (r *mutationResolver) RenameSymbol(ctx context.Context, input model.RenameSymbolInput) (*model.Patch, error) {
	panic(fmt.Errorf("not implemented: RenameSymbol - renameSymbol"))
}

// CreateStage is the resolver for the createStage field.
func (r *mutationResolver) CreateStage(ctx context.Context, input model.CreateStageInput) (*model.PatchStage, error) {
	panic(fmt.Errorf("not implemented: CreateStage - createStage"))
}

// ApplyStage is the resolver for the applyStage field.
func (r *mutationResolver) ApplyStage(ctx context.Context, stageID string) (model.JSON, error) {
	panic(fmt.Errorf("not implemented: ApplyStage - applyStage"))
}

// RejectStage is the resolver for the rejectStage field.
func (r *mutationResolver) RejectStage(ctx context.Context, stageID string, reason *string) (*model.PatchStage, error) {
	panic(fmt.Errorf("not implemented: RejectStage - rejectStage"))
}

// Patches is the resolver for the patches field.
func (r *queryResolver) Patches(ctx context.Context, projectID string) ([]model.Patch, error) {
	panic(fmt.Errorf("not implemented: Patches - patches"))
}

// Patch is the resolver for the patch field.
func (r *queryResolver) Patch(ctx context.Context, id string) (*model.Patch, error) {
	panic(fmt.Errorf("not implemented: Patch - patch"))
}

// PatchSnapshots is the resolver for the patchSnapshots field.
func (r *queryResolver) PatchSnapshots(ctx context.Context, projectID string) (model.JSON, error) {
	panic(fmt.Errorf("not implemented: PatchSnapshots - patchSnapshots"))
}

// Stages is the resolver for the stages field.
func (r *queryResolver) Stages(ctx context.Context, projectID string) ([]model.PatchStage, error) {
	panic(fmt.Errorf("not implemented: Stages - stages"))
}

// Stage is the resolver for the stage field.
func (r *queryResolver) Stage(ctx context.Context, id string) (*model.PatchStage, error) {
	panic(fmt.Errorf("not implemented: Stage - stage"))
}
