package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/apps/orchestrator/internal/domain"
	"ironflyer/apps/orchestrator/internal/graph/model"
	"ironflyer/apps/orchestrator/internal/store"
	"time"

	"github.com/google/uuid"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	if r.Resolver.Projects == nil {
		return nil, gqlNotConfigured("projects")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	now := time.Now().UTC()
	id := ""
	if input.ID != nil {
		id = *input.ID
	}
	if id == "" {
		id = uuid.NewString()
	}
	desc := ""
	if input.Description != nil {
		desc = *input.Description
	}
	idea := ""
	if input.Idea != nil {
		idea = *input.Idea
	}
	p, err := r.Resolver.Projects.Create(domain.Project{
		ID:          id,
		Name:        input.Name,
		Description: desc,
		Status:      "ready",
		OwnerID:     u.ID,
		Spec: domain.ProductSpec{
			Idea: idea,
		},
		Files:     []domain.FileNode{},
		Gates:     emptyProjectGates(now),
		CreatedAt: now,
		UpdatedAt: now,
	})
	if err != nil {
		return nil, err
	}
	out := projectToGraphQL(p)
	return &out, nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id string, input model.UpdateProjectInput) (*model.Project, error) {
	if r.Resolver.Projects == nil {
		return nil, gqlNotConfigured("projects")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	existing, err := r.Resolver.Projects.Get(id)
	if err != nil {
		return nil, err
	}
	if !existing.IsAccessibleBy(u.ID) {
		return nil, errUnauthenticated
	}
	p, err := r.Resolver.Projects.Update(id, func(p *domain.Project) {
		if input.Name != nil {
			p.Name = *input.Name
		}
		if input.Description != nil {
			p.Description = *input.Description
		}
		if input.Idea != nil {
			p.Spec.Idea = *input.Idea
		}
		if input.Status != nil {
			p.Status = *input.Status
		}
	})
	if err != nil {
		return nil, err
	}
	out := projectToGraphQL(p)
	return &out, nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (*model.OperationResult, error) {
	if r.Resolver.Projects == nil {
		return nil, gqlNotConfigured("projects")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.Resolver.Projects.Delete(id); err != nil {
		if err == store.ErrNotFound {
			msg := "project not found"
			return &model.OperationResult{Ok: false, Message: &msg}, nil
		}
		return nil, err
	}
	// Agent 30 — cascade the AI Memory Graph cleanup. Fire-and-forget:
	// the canonical project delete already committed and the user-visible
	// response must not block on Surreal/pgvector. The 30s timeout caps
	// pathological backends; failures only land in the orchestrator log.
	r.cascadeProjectGraph(u.ID, id)
	msg := "project deleted"
	return &model.OperationResult{Ok: true, Message: &msg}, nil
}

// BulkDeleteProjects is the resolver for the bulkDeleteProjects field.
func (r *mutationResolver) BulkDeleteProjects(ctx context.Context, ids []string) (*model.OperationResult, error) {
	if r.Resolver.Projects == nil {
		return nil, gqlNotConfigured("projects")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	deleted := 0
	for _, id := range ids {
		if err := r.Resolver.Projects.Delete(id); err == nil {
			deleted++
			r.cascadeProjectGraph(u.ID, id)
		}
	}
	msg := "projects deleted"
	return &model.OperationResult{Ok: true, Message: &msg}, nil
}

// RunFinisher is the resolver for the runFinisher field.
func (r *mutationResolver) RunFinisher(ctx context.Context, id string) (model.JSON, error) {
	if r.Resolver.Engine == nil {
		return nil, gqlNotConfigured("finisher")
	}
	report, err := r.Resolver.Engine.Run(ctx, id)
	if err != nil {
		return nil, err
	}
	return model.JSON{
		"projectID":  report.ProjectID,
		"startedAt":  report.StartedAt,
		"finishedAt": report.FinishedAt,
		"iterations": report.Iterations,
		"completed":  report.Completed,
		"gates":      report.Gates,
		"patchIds":   report.PatchIDs,
	}, nil
}

// PromptPlan is the resolver for the promptPlan field.
func (r *mutationResolver) PromptPlan(ctx context.Context, id string, prompt string) (model.JSON, error) {
	if r.Resolver.Projects == nil {
		return nil, gqlNotConfigured("projects")
	}
	p, err := r.Resolver.Projects.Update(id, func(p *domain.Project) {
		p.Spec.Idea = prompt
	})
	if err != nil {
		return nil, err
	}
	return model.JSON{"project": projectToGraphQL(p)}, nil
}

// Projects is the resolver for the projects field. Owner-scoped: the
// store's ListByOwner narrows to projects accessible to the caller
// (owner-owned plus public seeds) and applies limit/offset before any
// GraphQL projection cost.
func (r *queryResolver) Projects(ctx context.Context, limit *int, offset *int) ([]model.Project, error) {
	if r.Resolver.Projects == nil {
		return nil, gqlNotConfigured("projects")
	}
	userID := ""
	if u, err := currentUser(ctx); err == nil {
		userID = u.ID
	}
	lim := 50
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	off := 0
	if offset != nil && *offset > 0 {
		off = *offset
	}
	projects, err := r.Resolver.Projects.ListByOwner(ctx, userID, lim, off)
	if err != nil {
		return nil, err
	}
	out := make([]model.Project, 0, len(projects))
	for _, p := range projects {
		out = append(out, projectToGraphQL(p))
	}
	return out, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	if r.Resolver.Projects == nil {
		return nil, gqlNotConfigured("projects")
	}
	p, err := r.Resolver.Projects.Get(id)
	if err != nil {
		if err == store.ErrNotFound {
			return nil, nil
		}
		return nil, err
	}
	userID := ""
	if u, err := currentUser(ctx); err == nil {
		userID = u.ID
	}
	if !p.IsAccessibleBy(userID) {
		return nil, nil
	}
	out := projectToGraphQL(p)
	return &out, nil
}

// ProjectFiles is the resolver for the projectFiles field.
func (r *queryResolver) ProjectFiles(ctx context.Context, id string) ([]model.ProjectFile, error) {
	if r.Resolver.Projects == nil {
		return nil, gqlNotConfigured("projects")
	}
	p, err := r.Resolver.Projects.Get(id)
	if err != nil {
		return nil, err
	}
	out := make([]model.ProjectFile, 0, len(p.Files))
	for _, f := range p.Files {
		out = append(out, fileToGraphQL(f))
	}
	return out, nil
}

// RunProject is the resolver for the runProject field.
func (r *subscriptionResolver) RunProject(ctx context.Context, projectID string) (<-chan model.RunEvent, error) {
	if r.Resolver.Engine == nil {
		return nil, gqlNotConfigured("finisher")
	}
	events, cancel := r.Resolver.Engine.Subscribe(projectID)
	out := make(chan model.RunEvent, 64)
	go func() {
		defer close(out)
		defer cancel()
		errCh := make(chan error, 1)
		go func() {
			_, err := r.Resolver.Engine.Run(ctx, projectID)
			errCh <- err
		}()
		for {
			select {
			case <-ctx.Done():
				return
			case err := <-errCh:
				if err != nil {
					out <- model.RunErrorEvent{Ts: time.Now().UTC(), Code: "RUN_FAILED", Message: err.Error()}
				} else {
					out <- model.RunDoneEvent{Ts: time.Now().UTC(), Ok: true, Summary: model.JSON{"projectID": projectID}}
				}
				return
			case ev, ok := <-events:
				if !ok {
					return
				}
				out <- runEventToGraphQL(ev)
			}
		}
	}()
	return out, nil
}
