package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"ironflyer/apps/orchestrator/internal/graph/model"
)

// ExecutionSecurityReport resolves the per-execution security report.
// All aggregation logic lives in securityreport.Builder so the resolver
// stays a thin adapter: shape the input, call the builder, project
// the report into the model types.
func (r *queryResolver) ExecutionSecurityReport(ctx context.Context, executionID string) (*model.SecurityReport, error) {
	if r.SecurityReportBuilder == nil {
		return nil, fmt.Errorf("security report builder not configured")
	}
	report, err := r.SecurityReportBuilder.Build(ctx, executionID)
	if err != nil {
		return nil, err
	}
	findings := make([]model.SecurityReportFinding, 0, len(report.Findings))
	for _, f := range report.Findings {
		findings = append(findings, model.SecurityReportFinding{
			ID:          f.ID,
			Severity:    string(f.Severity),
			RuleID:      f.RuleID,
			Category:    f.Category,
			Path:        f.Path,
			Line:        f.Line,
			Summary:     f.Summary,
			Remediation: f.Remediation,
			DetectedAt:  f.DetectedAt,
		})
	}
	// OWASP coverage projects as a JSON-scalar map so the schema
	// keeps a stable shape even as new OWASP versions add categories.
	coverage := make(map[string]any, len(report.OWASPCoverage))
	for k, v := range report.OWASPCoverage {
		coverage[k] = v
	}
	// Sentinel: when builder degrades to empty (no FindingSource
	// wired) we still return a coherent "no data" report instead of
	// surfacing securityreport.ErrFindingSourceUnconfigured.
	if report.Status == "" {
		report.Status = "pass"
	}
	return &model.SecurityReport{
		ExecutionID:   report.ExecutionID,
		TenantID:      report.TenantID,
		Status:        report.Status,
		OverallScore:  report.OverallScore,
		Findings:      findings,
		SecretsFound:  report.SecretsFound,
		OutdatedDeps:  report.OutdatedDeps,
		OwaspCoverage: coverage,
		GeneratedAt:   report.GeneratedAt,
		BlockedDeploy: report.BlockedDeploy,
	}, nil
}
