package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"ironflyer/apps/orchestrator/internal/domain"
	"ironflyer/apps/orchestrator/internal/execution"
	"ironflyer/apps/orchestrator/internal/graph/model"
	"ironflyer/apps/orchestrator/internal/ideaparser"
	"ironflyer/apps/orchestrator/internal/wallet"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// DescribeIdea is the V22 vibe-builder entrypoint. Flow:
//  1. authenticate + wallet snapshot
//  2. pick a blueprint (first match, falls back to "auto")
//  3. determine budget (override → suggested → wallet ceiling)
//  4. create project (idea = prompt text)
//  5. create + admit + start the paid execution
//  6. place wallet hold (law 1)
//  7. optionally kick the finisher
//
// On wallet shortfall, the resolver returns a typed GraphQL error
// with a top_up_url extension and creates nothing.
func (r *mutationResolver) DescribeIdea(ctx context.Context, input model.DescribeIdeaInput) (*model.StudioBootstrap, error) {
	if r.WalletSvc == nil {
		return nil, gqlNotConfigured("wallet")
	}
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	if r.Projects == nil {
		return nil, gqlNotConfigured("projects")
	}

	text := strings.TrimSpace(input.Text)
	if text == "" {
		return nil, errors.New("describeIdea: text must not be empty")
	}

	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	tenant := tenantFor(u)

	// 1) Wallet snapshot. If empty, fail fast with a 402-style error.
	walletRow, err := r.WalletSvc.Get(ctx, tenant)
	if err != nil {
		return nil, fmt.Errorf("wallet snapshot: %w", err)
	}
	available := walletRow.AvailableUSD()
	if available.LessThanOrEqual(decimal.Zero) {
		return nil, studioInsufficientFunds(r.WebBaseURL)
	}

	// 2) Pick a blueprint. When the IdeaParser is wired (A54), it
	// returns a fully structured Idea (LLM or rules backend); otherwise
	// we fall back to the keyword heuristic below so the studio still
	// boots on air-gapped dev.
	var (
		bp           studioBlueprintRef
		parsedIdea   *ideaparser.Idea
		parsedTitle  string
		parsedTags   []string
		parsedSugBud = decimal.Zero
	)
	if r.IdeaParser != nil {
		maxBud := available
		if input.BudgetUSDOverride != nil && *input.BudgetUSDOverride > 0 {
			cap := decimal.NewFromFloat(*input.BudgetUSDOverride)
			if cap.LessThan(maxBud) {
				maxBud = cap
			}
		}
		idea, perr := r.IdeaParser.Parse(ctx, ideaparser.ParseInput{
			Text:         text,
			TenantID:     tenant,
			UserID:       u.ID,
			MaxBudgetUSD: maxBud,
		})
		if perr == nil && idea.BlueprintID != "" {
			parsedIdea = &idea
			parsedTitle = idea.Title
			parsedTags = idea.Tags
			parsedSugBud = idea.SuggestedBudget
			bp = studioMaybeBlueprint(r.BlueprintsReg, idea.BlueprintID)
			if idea.BlueprintReason != "" {
				bp.Reason = idea.BlueprintReason
			}
			if bp.CostPrior == 0 && idea.SuggestedBudget.IsPositive() {
				bp.CostPrior = idea.SuggestedBudget.InexactFloat64()
			}
			if bp.StopLoss == 0 && idea.StopLossUSD.IsPositive() {
				bp.StopLoss = idea.StopLossUSD.InexactFloat64()
			}
		} else if perr != nil {
			r.Logger.Warn().Err(perr).Msg("studio: idea parser failed; falling back to keyword heuristic")
		}
	}
	if bp.ID == "" {
		bp = studioPickBlueprint(r.BlueprintsReg, text)
	}

	// 3) Budget. Defaults to $2; clamped to wallet available. The
	// caller's explicit override wins over the parser's suggestion.
	budget := decimal.NewFromFloat(defaultStudioBudgetUSD)
	if parsedSugBud.IsPositive() {
		budget = parsedSugBud
	}
	if input.BudgetUSDOverride != nil && *input.BudgetUSDOverride > 0 {
		budget = decimal.NewFromFloat(*input.BudgetUSDOverride)
	}
	if budget.GreaterThan(available) {
		budget = available
	}
	if budget.LessThanOrEqual(decimal.Zero) {
		return nil, studioInsufficientFunds(r.WebBaseURL)
	}
	stopLoss := budget // V22 minimal: stop-loss == budget.
	if parsedIdea != nil && parsedIdea.StopLossUSD.GreaterThan(stopLoss) && parsedIdea.StopLossUSD.LessThanOrEqual(available) {
		stopLoss = parsedIdea.StopLossUSD
	}

	// 4) Project.
	now := time.Now().UTC()
	title := parsedTitle
	if title == "" {
		title = studioTitleFrom(text)
	}
	project, err := r.Projects.Create(domain.Project{
		ID:          uuid.NewString(),
		Name:        title,
		Description: text,
		Status:      "ready",
		OwnerID:     u.ID,
		Spec: domain.ProductSpec{
			Idea: text,
		},
		Files:     []domain.FileNode{},
		Gates:     map[domain.GateName]domain.GateState{},
		CreatedAt: now,
		UpdatedAt: now,
	})
	if err != nil {
		return nil, fmt.Errorf("project create: %w", err)
	}

	// 5) Execution.
	startNow := true
	if input.StartImmediately != nil {
		startNow = *input.StartImmediately
	}
	metaBytes, _ := json.Marshal(map[string]any{
		"source":          "studio.describeIdea",
		"blueprint_id":    bp.ID,
		"blueprint_name":  bp.Name,
		"start_immediate": startNow,
	})
	stopPtr := stopLoss
	exec, err := r.ExecutionSvc.Create(ctx, execution.CreateInput{
		TenantID:      tenant,
		ProjectID:     project.ID,
		BlueprintID:   bp.ID,
		BudgetUSD:     budget,
		StopLossUSD:   &stopPtr,
		PromptSummary: text,
		Metadata:      metaBytes,
	})
	if err != nil {
		return nil, fmt.Errorf("execution create: %w", err)
	}

	// 6) Wallet hold — law 1. Roll back exec on failure.
	if err := r.WalletSvc.Hold(ctx, tenant, budget); err != nil {
		_ = r.ExecutionSvc.Fail(ctx, exec.ID, "wallet_hold_failed")
		if errors.Is(err, wallet.ErrInsufficient) {
			return nil, studioInsufficientFunds(r.WebBaseURL)
		}
		return nil, fmt.Errorf("wallet hold: %w", err)
	}

	// 7) Admit + Start. On admit failure release the hold + fail the
	// execution so the wallet stays consistent.
	if err := r.ExecutionSvc.Admit(ctx, exec.ID); err != nil {
		_ = r.WalletSvc.Release(ctx, tenant, budget)
		_ = r.ExecutionSvc.Fail(ctx, exec.ID, "admit_failed")
		return nil, fmt.Errorf("execution admit: %w", err)
	}
	if startNow {
		if err := r.ExecutionSvc.Start(ctx, exec.ID); err != nil {
			r.Logger.Warn().Err(err).Str("execution_id", exec.ID).Msg("studio: execution.Start failed after admit")
		}
	}

	// Optional finisher kick — best-effort, fire-and-forget.
	if startNow && r.Engine != nil {
		go func(projID string) {
			bgCtx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
			defer cancel()
			if _, runErr := r.Engine.Run(bgCtx, projID); runErr != nil {
				r.Logger.Warn().Err(runErr).Str("project_id", projID).Msg("studio: finisher run failed")
			}
		}(project.ID)
	}

	// Refresh execution so admitted_at / started_at land.
	if refreshed, refErr := r.ExecutionSvc.Get(ctx, exec.ID); refErr == nil {
		exec = refreshed
	}

	gqlProject := projectToGraphQL(project)
	estimate := studioDefaultEstimate(budget.InexactFloat64())
	idea := studioIdeaFor(title, text, bp)
	if len(parsedTags) > 0 {
		idea.Tags = parsedTags
	}
	if parsedIdea != nil {
		if parsedIdea.Summary != "" {
			idea.Summary = parsedIdea.Summary
		}
		if parsedIdea.Confidence > 0 {
			idea.Confidence = parsedIdea.Confidence
		}
		if parsedIdea.SuggestedBudget.IsPositive() {
			idea.SuggestedBudgetUsd = parsedIdea.SuggestedBudget.InexactFloat64()
		}
		if parsedIdea.StopLossUSD.IsPositive() {
			idea.StopLossUsd = parsedIdea.StopLossUSD.InexactFloat64()
		}
	}
	return &model.StudioBootstrap{
		Project:      gqlProject,
		Execution:    *executionToGraphQL(exec),
		Idea:         idea,
		CostEstimate: estimate,
	}, nil
}

// RefineIdea records the message as a studio.refine.v1 event on the
// running execution. The finisher loop picks it up on the next
// iteration. Admission state stays unchanged — refine is additive.
func (r *mutationResolver) RefineIdea(ctx context.Context, executionID string, message string) (*model.StudioBootstrap, error) {
	if r.ExecutionSvc == nil {
		return nil, gqlNotConfigured("execution")
	}
	if r.Projects == nil {
		return nil, gqlNotConfigured("projects")
	}
	msg := strings.TrimSpace(message)
	if msg == "" {
		return nil, errors.New("refineIdea: message must not be empty")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	tenant := tenantFor(u)

	exec, err := r.ExecutionSvc.Get(ctx, executionID)
	if err != nil {
		return nil, err
	}
	if exec.TenantID != tenant {
		return nil, errUnauthenticated
	}

	payload, _ := json.Marshal(map[string]any{
		"message":     msg,
		"user_id":     u.ID,
		"recorded_at": time.Now().UTC().Format(time.RFC3339Nano),
	})
	if err := r.ExecutionSvc.RecordEvent(ctx, executionID, "studio.refine.v1", payload); err != nil {
		return nil, fmt.Errorf("record refine event: %w", err)
	}

	// Best-effort kick the finisher again so the new instruction
	// gets folded into the next iteration. Same pattern as
	// describeIdea — fire-and-forget; the engine emits events on
	// its own bus.
	if r.Engine != nil && exec.ProjectID != "" {
		go func(projID string) {
			bgCtx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
			defer cancel()
			if _, runErr := r.Engine.Run(bgCtx, projID); runErr != nil {
				r.Logger.Warn().Err(runErr).Str("project_id", projID).Msg("studio: finisher rerun (refine) failed")
			}
		}(exec.ProjectID)
	}

	refreshed, _ := r.ExecutionSvc.Get(ctx, executionID)

	var gqlProject model.Project
	if exec.ProjectID != "" {
		if p, getErr := r.Projects.Get(exec.ProjectID); getErr == nil {
			gqlProject = projectToGraphQL(p)
		}
	}
	if gqlProject.ID == "" {
		gqlProject = model.Project{
			ID:        exec.ProjectID,
			Name:      "Untitled",
			Status:    "unknown",
			OwnerID:   u.ID,
			IsPublic:  false,
			CreatedAt: refreshed.CreatedAt,
			UpdatedAt: time.Now().UTC(),
			Files:     []model.ProjectFile{},
			Gates:     []model.GateVerdict{},
		}
	}

	bp := studioMaybeBlueprint(r.BlueprintsReg, exec.BlueprintID)
	estimate := studioDefaultEstimate(exec.BudgetUSD.InexactFloat64())
	idea := studioIdeaFor(gqlProject.Name, exec.PromptSummary, bp)
	return &model.StudioBootstrap{
		Project:      gqlProject,
		Execution:    *executionToGraphQL(refreshed),
		Idea:         idea,
		CostEstimate: estimate,
	}, nil
}
