package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/apps/orchestrator/internal/graph/model"

	"github.com/shopspring/decimal"
)

// WalletCreateTopUp is the resolver for the walletCreateTopUp field.
//
// Provisions a one-shot Stripe Checkout session for the supplied
// amount, stages a pending wallet_topups row, and returns the URL the
// browser should open. The webhook later flips the row to succeeded
// and credits the wallet (see main.go stripeWebhook routing).
func (r *mutationResolver) WalletCreateTopUp(ctx context.Context, amountUsd float64) (*model.WalletCheckoutSession, error) {
	if r.WalletTopper == nil || !r.WalletTopper.Enabled() {
		return nil, gqlNotConfigured("wallet_topper")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	tenant := tenantFor(u)
	amount := decimal.NewFromFloat(amountUsd)
	sess, err := r.WalletTopper.CreateCheckoutSession(ctx, tenant, amount)
	if err != nil {
		return nil, err
	}
	return &model.WalletCheckoutSession{
		URL:       sess.URL,
		SessionID: sess.SessionID,
	}, nil
}

// Wallet is the resolver for the wallet field.
func (r *queryResolver) Wallet(ctx context.Context) (*model.Wallet, error) {
	if r.WalletSvc == nil {
		return nil, gqlNotConfigured("wallet")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	tenant := tenantFor(u)
	w, err := r.WalletSvc.Get(ctx, tenant)
	if err != nil {
		return nil, err
	}
	return &model.Wallet{
		TenantID:         w.TenantID,
		BalanceUsd:       floatOfDecimal(w.BalanceUSD),
		HoldUsd:          floatOfDecimal(w.HoldUSD),
		AvailableUsd:     floatOfDecimal(w.AvailableUSD()),
		LifetimeTopUpUsd: floatOfDecimal(w.LifetimeTopUpUSD),
		LifetimeSpendUsd: floatOfDecimal(w.LifetimeSpendUSD),
		UpdatedAt:        w.UpdatedAt,
	}, nil
}

// WalletTopUps is the resolver for the walletTopUps field.
func (r *queryResolver) WalletTopUps(ctx context.Context, limit *int) ([]model.WalletTopUp, error) {
	if r.WalletSvc == nil {
		return nil, gqlNotConfigured("wallet")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	lim := 50
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	rows, err := r.WalletSvc.ListTopUps(ctx, tenantFor(u), lim)
	if err != nil {
		return nil, err
	}
	out := make([]model.WalletTopUp, 0, len(rows))
	for _, t := range rows {
		out = append(out, model.WalletTopUp{
			ID:          t.ID,
			AmountUsd:   floatOfDecimal(t.AmountUSD),
			Status:      t.Status,
			CreatedAt:   t.CreatedAt,
			CompletedAt: t.CompletedAt,
		})
	}
	return out, nil
}
