package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/apps/orchestrator/internal/graph/generated"
	"ironflyer/apps/orchestrator/internal/graph/model"
	"time"
)

// Empty is the resolver for the _empty field.
func (r *mutationResolver) Empty(ctx context.Context) (*string, error) {
	s := ""
	return &s, nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "ok", nil
}

// Version is the resolver for the version field.
func (r *queryResolver) Version(ctx context.Context) (*model.VersionInfo, error) {
	return &model.VersionInfo{
		Service:   buildServiceName,
		Version:   buildVersion,
		Commit:    buildCommit,
		BuildTime: buildTime,
	}, nil
}

// Heartbeat is the resolver for the _heartbeat field. Emits one tick
// per 15s so clients can keep a websocket warm without subscribing to
// a domain-specific feed. Closes when the context cancels.
func (r *subscriptionResolver) Heartbeat(ctx context.Context) (<-chan *model.HeartbeatEvent, error) {
	out := make(chan *model.HeartbeatEvent, 1)
	go func() {
		defer close(out)
		// Send an immediate tick so the client confirms the
		// subscription is live without waiting one full interval.
		first := "alive"
		select {
		case out <- &model.HeartbeatEvent{Ts: time.Now().UTC(), Message: &first}:
		case <-ctx.Done():
			return
		}
		t := time.NewTicker(15 * time.Second)
		defer t.Stop()
		for {
			select {
			case <-ctx.Done():
				return
			case ts := <-t.C:
				msg := "alive"
				select {
				case out <- &model.HeartbeatEvent{Ts: ts.UTC(), Message: &msg}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
