config:
  ironflyer:region: ams3
  ironflyer:doksNodeSize: s-4vcpu-8gb
  ironflyer:doksNodeCount: "3"
  ironflyer:doksMaxNodes: "12"
  ironflyer:doksRuntimeNodeSize: s-8vcpu-16gb
  ironflyer:doksRuntimeNodeCount: "3"
  ironflyer:doksRuntimeMaxNodes: "20"
  ironflyer:k8sVersion: 1.30.6-do.0
  ironflyer:postgresSize: db-s-4vcpu-8gb
  ironflyer:postgresVersion: "16"
  ironflyer:redisSize: db-s-2vcpu-4gb
  ironflyer:redisVersion: "7"
  ironflyer:enableHA: "true"
  ironflyer:vercelEnabled: "true"
  ironflyer:vercelDomain: app.eu.ironflyer.dev
  ironflyer:rootDomain: ironflyer.dev
  ironflyer:spacesRegion: ams3
