config:
  ironflyer:region: nyc3
  ironflyer:doksNodeSize: s-2vcpu-4gb
  ironflyer:doksNodeCount: "2"
  ironflyer:doksMaxNodes: "4"
  ironflyer:doksRuntimeNodeSize: s-2vcpu-4gb
  ironflyer:doksRuntimeNodeCount: "1"
  ironflyer:doksRuntimeMaxNodes: "3"
  ironflyer:k8sVersion: 1.30.6-do.0
  ironflyer:postgresSize: db-s-1vcpu-1gb
  ironflyer:postgresVersion: "16"
  ironflyer:redisSize: db-s-1vcpu-1gb
  ironflyer:redisVersion: "7"
  ironflyer:enableHA: "false"
  ironflyer:vercelEnabled: "false"
  ironflyer:vercelDomain: app.dev.ironflyer.dev
  ironflyer:rootDomain: dev.ironflyer.dev
  ironflyer:spacesRegion: nyc3
