package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"

	"ironflyer/core/orchestrator/internal/operations/agentteam"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
)

// SaveCustomAgent persists (creates or updates) an owner-scoped custom agent.
func (r *mutationResolver) SaveCustomAgent(ctx context.Context, input model.SaveCustomAgentInput) (*model.CustomAgent, error) {
	if r.AgentTeam == nil {
		return nil, gqlNotConfigured("agent team")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	saved, err := r.AgentTeam.SaveAgent(ctx, customAgentFromInput(u.ID, input))
	if err != nil {
		return nil, err
	}
	out := customAgentToModel(saved)
	return &out, nil
}

// DeleteCustomAgent removes an owner-scoped custom agent and drops it from any
// of the owner's crews.
func (r *mutationResolver) DeleteCustomAgent(ctx context.Context, id string) (bool, error) {
	if r.AgentTeam == nil {
		return false, gqlNotConfigured("agent team")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return false, err
	}
	if err := r.AgentTeam.DeleteAgent(ctx, u.ID, id); err != nil {
		if errors.Is(err, agentteam.ErrNotFound) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// SaveCrew persists (creates or updates) an owner-scoped crew.
func (r *mutationResolver) SaveCrew(ctx context.Context, input model.SaveCrewInput) (*model.Crew, error) {
	if r.AgentTeam == nil {
		return nil, gqlNotConfigured("agent team")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	saved, err := r.AgentTeam.SaveCrew(ctx, crewFromInput(u.ID, input))
	if err != nil {
		return nil, err
	}
	out := crewToModel(saved)
	return &out, nil
}

// DeleteCrew removes an owner-scoped crew.
func (r *mutationResolver) DeleteCrew(ctx context.Context, id string) (bool, error) {
	if r.AgentTeam == nil {
		return false, gqlNotConfigured("agent team")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return false, err
	}
	if err := r.AgentTeam.DeleteCrew(ctx, u.ID, id); err != nil {
		if errors.Is(err, agentteam.ErrNotFound) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// RunCrew dispatches a crew against a project. The heavy lifting (member
// resolution, the wallet hold/settle, and the parallel/sequential/hierarchical
// dispatch via errgroup) lives in agentteam_exec.go so gqlgen's regen can't
// evict it.
func (r *mutationResolver) RunCrew(ctx context.Context, id string, projectID string) (*model.CrewRunResult, error) {
	return r.Resolver.runCrew(ctx, id, projectID)
}

// CustomAgents returns the caller's own custom agents.
func (r *queryResolver) CustomAgents(ctx context.Context) ([]model.CustomAgent, error) {
	if r.AgentTeam == nil {
		return nil, gqlNotConfigured("agent team")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	list, err := r.AgentTeam.ListAgents(ctx, u.ID)
	if err != nil {
		return nil, err
	}
	out := make([]model.CustomAgent, 0, len(list))
	for _, a := range list {
		out = append(out, customAgentToModel(a))
	}
	return out, nil
}

// Crews returns the caller's own crews.
func (r *queryResolver) Crews(ctx context.Context) ([]model.Crew, error) {
	if r.AgentTeam == nil {
		return nil, gqlNotConfigured("agent team")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	list, err := r.AgentTeam.ListCrews(ctx, u.ID)
	if err != nil {
		return nil, err
	}
	out := make([]model.Crew, 0, len(list))
	for _, c := range list {
		out = append(out, crewToModel(c))
	}
	return out, nil
}
