package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/core/orchestrator/internal/ai/providers"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
	"ironflyer/core/orchestrator/internal/operations/operator"
	"sort"
	"strings"
	"time"
)

// Agents returns the static agent catalogue — system prompts +
// capability tags + extended-thinking flag — sourced from the
// in-process registry that loaded agents.yaml at boot.
func (r *queryResolver) Agents(ctx context.Context) ([]model.Agent, error) {
	if r.Resolver.Agents == nil {
		return nil, gqlNotConfigured("agents")
	}
	all := r.Resolver.Agents.All()
	out := make([]model.Agent, 0, len(all))
	for _, a := range all {
		out = append(out, agentToGraphQL(a))
	}
	// Stable order — registry uses a Go map so ranging is randomised;
	// the dashboard's "agents" panel renders cleaner with a fixed
	// order.
	sort.Slice(out, func(i, j int) bool { return out[i].Role < out[j].Role })
	return out, nil
}

// AgentTelemetry returns the most recent calls captured by the
// telemetry sink, with optional role/provider/model filters.
func (r *queryResolver) AgentTelemetry(ctx context.Context, limit *int, role *string, provider *string, modelName *string) ([]model.AgentCall, error) {
	// Names the live vendor + model per call — operator-only.
	if !operator.IsOperator(ctx) {
		return nil, gqlForbiddenOperator()
	}
	if r.Telemetry == nil {
		return nil, gqlNotConfigured("telemetry")
	}
	lim := 100
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	// Pull more than `lim` from the sink so filters that drop most
	// rows still return a meaningful number. Capped at 2k so the
	// caller can't ask for the whole ring buffer accidentally.
	pull := lim * 4
	if pull > 2000 {
		pull = 2000
	}
	if pull < lim {
		pull = lim
	}
	calls := r.Telemetry.Recent(pull)
	out := make([]model.AgentCall, 0, lim)
	for _, c := range calls {
		if role != nil && *role != "" && !strings.EqualFold(c.Role, *role) {
			continue
		}
		if provider != nil && *provider != "" && !strings.EqualFold(c.Provider, *provider) {
			continue
		}
		if modelName != nil && *modelName != "" && !strings.EqualFold(c.Model, *modelName) {
			continue
		}
		out = append(out, telemetryCallToGraphQL(c))
		if len(out) >= lim {
			break
		}
	}
	return out, nil
}

// BanditRanking aggregates the last N telemetry rows into a
// per-capability winners table. Strategy + lastConfidence come from
// the package-global registered bandit so the operator can see what
// the live router is using to pick.
func (r *queryResolver) BanditRanking(ctx context.Context, lookback *int) (*model.BanditRanking, error) {
	// A per-vendor/model leaderboard — operator-only.
	if !operator.IsOperator(ctx) {
		return nil, gqlForbiddenOperator()
	}
	if r.Telemetry == nil {
		return nil, gqlNotConfigured("telemetry")
	}
	lb := 256
	if lookback != nil && *lookback > 0 {
		lb = *lookback
	}
	calls := r.Telemetry.Recent(lb)

	strategy, confidence := providers.ActiveBanditInfo()
	// Aggregate per (capability, provider, model). Capability comes
	// from each call's recorded capability slice; calls without any
	// capability tag land under "general".
	type key struct{ cap, prov, model string }
	type agg struct {
		calls, errors int
		totalReward   float64
		totalCost     float64
		lastUsed      time.Time
	}
	bucket := map[key]*agg{}
	capTotals := map[string]int{}
	for _, c := range calls {
		caps := c.Capabilities
		if len(caps) == 0 {
			caps = []string{"general"}
		}
		for _, capName := range caps {
			k := key{cap: capName, prov: c.Provider, model: c.Model}
			a, ok := bucket[k]
			if !ok {
				a = &agg{}
				bucket[k] = a
			}
			a.calls++
			if c.Error != "" {
				a.errors++
			} else {
				// Cheap reward proxy: 1.0 for success, 0 for error.
				a.totalReward += 1.0
			}
			a.totalCost += c.CostUSD
			if c.StartedAt.After(a.lastUsed) {
				a.lastUsed = c.StartedAt
			}
			capTotals[capName]++
		}
	}

	// Group bucket → capability winners and rank by mean reward.
	capWinners := map[string][]model.BanditWinner{}
	for k, a := range bucket {
		w := model.BanditWinner{
			Provider:   k.prov,
			Share:      0,
			MeanReward: 0,
			AvgCostUsd: 0,
			Calls:      a.calls,
			Errors:     a.errors,
		}
		if k.model != "" {
			m := k.model
			w.Model = &m
		}
		if a.calls > 0 {
			w.MeanReward = a.totalReward / float64(a.calls)
			w.AvgCostUsd = a.totalCost / float64(a.calls)
			if capTotals[k.cap] > 0 {
				w.Share = float64(a.calls) / float64(capTotals[k.cap])
			}
		}
		if !a.lastUsed.IsZero() {
			t := a.lastUsed
			w.LastUsed = &t
		}
		capWinners[k.cap] = append(capWinners[k.cap], w)
	}

	caps := make([]model.BanditCapability, 0, len(capWinners))
	for capName, winners := range capWinners {
		sort.Slice(winners, func(i, j int) bool {
			return winners[i].MeanReward > winners[j].MeanReward
		})
		if len(winners) > 0 {
			winners[0].IsLeader = true
		}
		caps = append(caps, model.BanditCapability{
			Capability: capName,
			Total:      capTotals[capName],
			Winners:    winners,
		})
	}
	sort.Slice(caps, func(i, j int) bool { return caps[i].Capability < caps[j].Capability })

	out := &model.BanditRanking{
		Capabilities: caps,
		Lookback:     lb,
		Sampled:      len(calls),
		Strategy:     strategy,
	}
	if confidence != 0 {
		c := confidence
		out.LastConfidence = &c
	}
	return out, nil
}

// CostStream subscribes to the active telemetry sink and forwards
// every Record as a CostDelta. When the sink is the in-process
// MemorySink we use SubscribeUser so cross-pod ticks are merged in;
// otherwise we degrade to a polling loop that re-reads Recent every
// second so the front-end still sees fresh cost data.
func (r *subscriptionResolver) CostStream(ctx context.Context) (<-chan *model.CostDelta, error) {
	if r.Telemetry == nil {
		return nil, gqlNotConfigured("telemetry")
	}
	out := make(chan *model.CostDelta, 32)

	if mem, ok := r.Telemetry.(*providers.MemorySink); ok {
		userID := ""
		if u, err := currentUser(ctx); err == nil {
			userID = u.ID
		}
		var (
			calls       <-chan providers.AgentCall
			unsubscribe func()
		)
		if userID != "" {
			calls, unsubscribe = mem.SubscribeUser(userID)
		} else {
			calls, unsubscribe = mem.Subscribe()
		}
		go func() {
			defer close(out)
			defer unsubscribe()
			for {
				select {
				case <-ctx.Done():
					return
				case c, ok := <-calls:
					if !ok {
						return
					}
					select {
					case out <- agentCallToCostDelta(c):
					default:
					}
				}
			}
		}()
		return out, nil
	}

	// Generic TelemetrySink — poll the ring buffer once a second and
	// emit only rows we haven't seen yet. Bounded by the sink's own
	// retention so we never duplicate or backfill stale data.
	go func() {
		defer close(out)
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()
		seen := time.Now().UTC()
		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				recent := r.Telemetry.Recent(64)
				// Recent returns newest-first; iterate oldest-first
				// so deltas arrive in order.
				for i := len(recent) - 1; i >= 0; i-- {
					c := recent[i]
					if !c.StartedAt.After(seen) {
						continue
					}
					select {
					case out <- agentCallToCostDelta(c):
					case <-ctx.Done():
						return
					}
					seen = c.StartedAt
				}
			}
		}
	}()
	return out, nil
}
