package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
)

// AppetizeUploadBuild is the resolver for the appetizeUploadBuild field.
//
// The resolver shape is intentionally thin — the orchestrator owns
// per-user isolation (the project lookup) and the appetize.Service
// owns the multipart upload + embed URL synthesis. The artifact byte
// stream is sourced from the runtime workspace by a later integration
// agent; until that wiring lands, this resolver returns a typed
// "not configured" error so the cockpit's CTA degrades cleanly.
func (r *mutationResolver) AppetizeUploadBuild(ctx context.Context, input model.AppetizeUploadInput) (*model.AppetizeApp, error) {
	if r.Appetize == nil {
		return nil, gqlNotConfigured("appetize")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	proj, err := r.Projects.Get(input.ProjectID)
	if err != nil {
		return nil, err
	}
	if !proj.IsAccessibleBy(u.ID) {
		return nil, errors.New("appetize: project not found")
	}
	deviceProfile := ""
	if input.DeviceProfile != nil {
		deviceProfile = *input.DeviceProfile
	}
	// TODO(mobile-runtime-integration): the artifact byte stream
	// must be sourced from the workspace; for now we return a typed
	// error so the cockpit surfaces "configure the runtime stream".
	_ = deviceProfile
	return nil, errors.New("appetize: workspace artifact stream not yet wired through orchestrator")
}

// AppetizeDeleteApp is the resolver for the appetizeDeleteApp field.
func (r *mutationResolver) AppetizeDeleteApp(ctx context.Context, publicKey string) (bool, error) {
	if r.Appetize == nil {
		return false, gqlNotConfigured("appetize")
	}
	if _, err := currentUser(ctx); err != nil {
		return false, err
	}
	if err := r.Appetize.Delete(ctx, publicKey); err != nil {
		return false, err
	}
	return true, nil
}
