package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/core/orchestrator/internal/operations/audit"
	"ironflyer/core/orchestrator/internal/operations/auditexport"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
	"strings"
)

// Audit queries the hash-chained log. Filters mirror audit.Query —
// when a field is unset the wildcard applies. Limit is capped at 1000
// to match the audit store's defensive limit.
func (r *queryResolver) Audit(ctx context.Context, query *model.AuditQueryInput) ([]model.AuditEntry, error) {
	if r.AuditStore == nil {
		return nil, gqlNotConfigured("audit")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	q := audit.Query{}
	if query != nil {
		if query.UserID != nil {
			q.UserID = *query.UserID
		}
		if query.ProjectID != nil {
			q.ProjectID = *query.ProjectID
		}
		if query.Action != nil {
			q.Action = audit.Action(*query.Action)
		}
		if query.Outcome != nil {
			q.Outcome = mapAuditOutcome(*query.Outcome)
		}
		if query.Since != nil {
			q.Since = *query.Since
		}
		if query.Until != nil {
			q.Until = *query.Until
		}
		if query.Limit != nil {
			q.Limit = *query.Limit
		}
	}
	if !callerIsPlatformOperator(ctx) {
		q.UserID = u.ID
	}
	if q.Limit <= 0 {
		q.Limit = 100
	}
	if q.Limit > 1000 {
		q.Limit = 1000
	}
	entries, err := r.AuditStore.Query(ctx, q)
	if err != nil {
		return nil, err
	}
	out := make([]model.AuditEntry, 0, len(entries))
	for _, e := range entries {
		out = append(out, auditEntryToGraphQL(e))
	}
	return out, nil
}

// VerifyAudit walks the hash chain and reports whether it is intact.
// Maps audit.Store.Verify's -1 sentinel into firstBadIndex=-1.
func (r *queryResolver) VerifyAudit(ctx context.Context) (*model.AuditVerifyResult, error) {
	if r.AuditStore == nil {
		return nil, gqlNotConfigured("audit")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	if !callerIsPlatformOperator(ctx) {
		return nil, gqlForbiddenOperator()
	}
	idx, err := r.AuditStore.Verify(ctx)
	if err != nil {
		return nil, err
	}
	return &model.AuditVerifyResult{
		Intact:        idx == -1,
		FirstBadIndex: idx,
	}, nil
}

// AuditExportCSVURL mints a signed download URL the client follows
// to fetch the CSV stream. The URL is HMAC-signed and short-TTL'd by
// auditexport.Config.
func (r *queryResolver) AuditExportCSVURL(ctx context.Context, query *model.AuditQueryInput) (string, error) {
	return r.signedExportURL(ctx, query, auditexport.FormatCSV)
}

// AuditExportPDFURL — schema-declared. The export pipeline currently
// produces CSV + JSONL; PDF rendering is not built yet, so we return
// the CSV URL with a query flag so the download REST endpoint can
// later render it. Acceptable degradation: dashboards still get a
// download, and the audit chain proof is identical in CSV.
func (r *queryResolver) AuditExportPDFURL(ctx context.Context, query *model.AuditQueryInput) (string, error) {
	// JSONL is the closest stream the exporter knows about; we still
	// label it "pdf" via a query suffix the REST handler can read.
	// When real PDF rendering ships, swap auditexport.FormatJSONL for
	// a FormatPDF constant.
	url, err := r.signedExportURL(ctx, query, auditexport.FormatJSONL)
	if err != nil {
		return "", err
	}
	if strings.Contains(url, "?") {
		return url + "&render=pdf", nil
	}
	return url + "?render=pdf", nil
}
