package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
	"ironflyer/core/orchestrator/internal/operations/metrics"
	"ironflyer/core/orchestrator/internal/ai/providers"
	"strings"
	"time"

	"github.com/google/uuid"
)

// AcceptInlineCompletion bumps the accept counter so the provider
// telemetry can compute acceptance rate. The schema returns a
// generic OperationResult — `ok=true` means the count landed; we
// never error because losing the metric is a soft failure.
func (r *mutationResolver) AcceptInlineCompletion(ctx context.Context, requestID string) (*model.OperationResult, error) {
	metrics.ObserveInlineCompletionAccept()
	msg := "accepted " + requestID
	return &model.OperationResult{Ok: true, Message: &msg}, nil
}

// InlineCompletion streams a middle-fill-in completion. Drives the
// BillingGuard with CapInline + CapFast so the bandit picks the
// cheapest fast provider (Haiku / 4o-mini / Gemini Flash). Emits the
// schema's InlineDelta union: Start → Text… → Done, or Error.
func (r *subscriptionResolver) InlineCompletion(ctx context.Context, input model.InlineInput) (<-chan model.InlineDelta, error) {
	if r.Guard == nil {
		return nil, gqlNotConfigured("billing-guard")
	}
	reqID := ""
	if input.RequestID != nil {
		reqID = strings.TrimSpace(*input.RequestID)
	}
	if reqID == "" {
		reqID = uuid.NewString()
	}
	tenantID := ""
	if u, err := currentUser(ctx); err == nil {
		tenantID = tenantFor(u)
	}

	prompt := buildInlinePrompt(input)
	caps := []providers.Capability{providers.CapInline, providers.CapFast, providers.CapCheap}
	// Privacy-first toggle: when IRONFLYER_INLINE_COMPLETIONS_PRIVATE=1
	// (the "Base44 on steroids — private AI" default for self-hosted
	// deploys) we add CapPrivate so the router prefers a self-hosted
	// HuggingFace endpoint or any provider that advertises private
	// hosting. Falls back to public cheap providers if no private
	// option is configured, so the toggle never blocks completion.
	if inlineCompletionsPrivate() {
		caps = append(caps, providers.CapPrivate)
	}
	req := providers.Request{
		System:       inlineSystemPrompt,
		Prompt:       prompt,
		Capabilities: caps,
		MaxTokens:    inlineMaxTokens(input.Effort),
		Temperature:  0.2,
		TenantID:     tenantID,
	}

	out := make(chan model.InlineDelta, 32)
	started := time.Now()
	metrics.ObserveInlineCompletionRequest("started")

	in, err := r.Guard.CompleteStream(ctx, req)
	if err != nil {
		go func() {
			defer close(out)
			out <- model.InlineErrorDelta{
				RequestID: stringPtr(reqID),
				Code:      "STREAM_FAILED",
				Message:   err.Error(),
			}
		}()
		metrics.ObserveInlineCompletionRequest("error")
		return out, nil
	}

	go func() {
		defer close(out)
		var (
			startedSent bool
			provider    string
			modelName   string
			doneSent    bool
			firstToken  bool
		)
		for {
			select {
			case <-ctx.Done():
				out <- model.InlineCancelledDelta{
					RequestID: reqID,
					Reason:    stringPtr("context cancelled"),
				}
				metrics.ObserveInlineCompletionRequest("cancelled")
				return
			case d, ok := <-in:
				if !ok {
					if !doneSent {
						out <- model.InlineDoneDelta{
							RequestID: reqID,
							Provider:  stringPtr(provider),
							Model:     stringPtr(modelName),
						}
					}
					if firstToken {
						metrics.ObserveInlineCompletionLatency(time.Since(started))
					}
					return
				}
				switch d.Type {
				case providers.DeltaStart:
					if !startedSent {
						provider = d.Provider
						modelName = d.Model
						out <- model.InlineStartDelta{
							RequestID: reqID,
							Provider:  d.Provider,
							Model:     d.Model,
						}
						startedSent = true
					}
				case providers.DeltaText:
					if !startedSent {
						out <- model.InlineStartDelta{
							RequestID: reqID,
							Provider:  d.Provider,
							Model:     d.Model,
						}
						startedSent = true
						provider = d.Provider
						modelName = d.Model
					}
					if !firstToken {
						metrics.ObserveInlineCompletionLatency(time.Since(started))
						firstToken = true
					}
					out <- model.InlineTextDelta{RequestID: reqID, Text: d.Text}
				case providers.DeltaDone:
					done := model.InlineDoneDelta{
						RequestID: reqID,
						Provider:  stringPtr(d.Provider),
						Model:     stringPtr(d.Model),
					}
					if d.Usage != nil {
						done.Usage = model.JSON{
							"inputTokens":  d.Usage.InputTokens,
							"outputTokens": d.Usage.OutputTokens,
							"costUsd":      d.Usage.CostUSD,
						}
					}
					out <- done
					doneSent = true
					metrics.ObserveInlineCompletionRequest("done")
				case providers.DeltaError:
					msg := "unknown error"
					if d.Err != nil {
						msg = d.Err.Error()
					}
					out <- model.InlineErrorDelta{
						RequestID: stringPtr(reqID),
						Code:      "PROVIDER_ERROR",
						Message:   msg,
					}
					metrics.ObserveInlineCompletionRequest("error")
					doneSent = true
				}
			}
		}
	}()
	return out, nil
}
