package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"

	"ironflyer/core/orchestrator/internal/business/compliance"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
)

// EnrollCompliance is the resolver for the enrollCompliance field.
//
// Idempotent — re-enrolling the same (tenant, project, framework)
// tuple returns the existing row instead of erroring, so a double-
// click on the Enroll button is a no-op.
func (r *mutationResolver) EnrollCompliance(ctx context.Context, projectID string, framework string) (*model.ComplianceEnrollment, error) {
	if r.Compliance == nil {
		return nil, gqlNotConfigured("compliance")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	row, err := r.Compliance.Enroll(ctx, tenantFor(u), projectID, framework)
	if err != nil {
		return nil, mapComplianceErr(err)
	}
	return complianceEnrollmentToModel(row)
}

// UnenrollCompliance is the resolver for the unenrollCompliance field.
func (r *mutationResolver) UnenrollCompliance(ctx context.Context, enrollmentID string) (bool, error) {
	if r.Compliance == nil {
		return false, gqlNotConfigured("compliance")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return false, err
	}
	if err := r.Compliance.Unenroll(ctx, tenantFor(u), enrollmentID); err != nil {
		return false, mapComplianceErr(err)
	}
	return true, nil
}

// EvaluateCompliance is the resolver for the evaluateCompliance field.
func (r *mutationResolver) EvaluateCompliance(ctx context.Context, projectID string, framework string) ([]model.ComplianceControlResult, error) {
	if r.Compliance == nil {
		return nil, gqlNotConfigured("compliance")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	results, err := r.Compliance.EvaluateAll(ctx, tenantFor(u), projectID, framework)
	if err != nil {
		return nil, mapComplianceErr(err)
	}
	return complianceResultsToModel(results), nil
}

// ExportAuditBundle is the resolver for the exportAuditBundle field.
func (r *mutationResolver) ExportAuditBundle(ctx context.Context, projectID string, framework string) (*model.ComplianceAuditBundle, error) {
	if r.Compliance == nil {
		return nil, gqlNotConfigured("compliance")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	bundle, err := r.Compliance.ExportAuditBundle(ctx, tenantFor(u), projectID, framework)
	if err != nil {
		return nil, mapComplianceErr(err)
	}
	return &model.ComplianceAuditBundle{
		GeneratedAt:    bundle.GeneratedAt,
		Framework:      complianceFrameworkToModel(bundle.Framework),
		DownloadURL:    bundle.DownloadURL,
		AttestationJwt: bundle.AttestationJWT,
	}, nil
}

// ComplianceFrameworks is the resolver for the complianceFrameworks field.
func (r *queryResolver) ComplianceFrameworks(ctx context.Context) ([]model.ComplianceFramework, error) {
	// Static catalogue is always available — no service required so the
	// dashboard can render its pricing panel even when the operator
	// hasn't wired Compliance yet.
	frameworks := compliance.Frameworks()
	out := make([]model.ComplianceFramework, 0, len(frameworks))
	for _, f := range frameworks {
		out = append(out, complianceFrameworkToModel(f))
	}
	return out, nil
}

// ComplianceEnrollments is the resolver for the complianceEnrollments field.
func (r *queryResolver) ComplianceEnrollments(ctx context.Context, projectID *string) ([]model.ComplianceEnrollment, error) {
	if r.Compliance == nil {
		return nil, gqlNotConfigured("compliance")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	pid := ""
	if projectID != nil {
		pid = *projectID
	}
	rows, err := r.Compliance.ListEnrolled(ctx, tenantFor(u), pid)
	if err != nil {
		return nil, mapComplianceErr(err)
	}
	out := make([]model.ComplianceEnrollment, 0, len(rows))
	for _, row := range rows {
		m, cerr := complianceEnrollmentToModel(row)
		if cerr != nil {
			return nil, cerr
		}
		out = append(out, *m)
	}
	return out, nil
}

// ComplianceControlResults is the resolver for the complianceControlResults field.
func (r *queryResolver) ComplianceControlResults(ctx context.Context, projectID string, framework string) ([]model.ComplianceControlResult, error) {
	if r.Compliance == nil {
		return nil, gqlNotConfigured("compliance")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	results, err := r.Compliance.ListResults(ctx, tenantFor(u), projectID, framework)
	if err != nil {
		return nil, mapComplianceErr(err)
	}
	return complianceResultsToModel(results), nil
}

// complianceFrameworkToModel maps the compliance.Framework value to
// the gqlgen-generated model. monthlyPriceUSD travels as a string so
// no float rounding leaks into a price.
func complianceFrameworkToModel(f compliance.Framework) model.ComplianceFramework {
	return model.ComplianceFramework{
		Key:             f.Key,
		Label:           f.Label,
		MonthlyPriceUsd: f.MonthlyPriceUSD.String(),
		ControlCount:    len(f.Gates),
	}
}

// complianceEnrollmentToModel hydrates the nested Framework before
// returning so the resolver doesn't need an extra trip to the
// catalogue. Returns a *model so callers can append or attach without
// a copy.
func complianceEnrollmentToModel(row compliance.EnrolledProject) (*model.ComplianceEnrollment, error) {
	f, err := compliance.LookupFramework(row.FrameworkKey)
	if err != nil {
		return nil, err
	}
	return &model.ComplianceEnrollment{
		ID:              row.ID,
		ProjectID:       row.ProjectID,
		Framework:       complianceFrameworkToModel(f),
		LastVerdict:     string(row.LastVerdict),
		LastEvaluatedAt: row.LastEvaluatedAt,
		NextChargeAt:    row.NextChargeAt,
	}, nil
}

// complianceResultsToModel maps each ControlResult into the generated
// model. Path is optional in GraphQL so empty strings travel as nil.
func complianceResultsToModel(results []compliance.ControlResult) []model.ComplianceControlResult {
	out := make([]model.ComplianceControlResult, 0, len(results))
	for _, r := range results {
		var pathPtr *string
		if r.Path != "" {
			p := r.Path
			pathPtr = &p
		}
		out = append(out, model.ComplianceControlResult{
			ControlKey:  r.ControlKey,
			Status:      string(r.Status),
			Severity:    string(r.Severity),
			Evidence:    r.Evidence,
			Path:        pathPtr,
			EvaluatedAt: r.EvaluatedAt,
		})
	}
	return out
}

// mapComplianceErr converts internal sentinels into typed GraphQL
// errors so the dashboard can render the right empty / error state
// per case.
func mapComplianceErr(err error) error {
	switch {
	case errors.Is(err, compliance.ErrUnknownFramework):
		return err
	case errors.Is(err, compliance.ErrNotFound):
		return err
	case errors.Is(err, compliance.ErrAttestationDisabled):
		return gqlNotConfigured("attestation_secret")
	case errors.Is(err, compliance.ErrInsufficientBalance):
		return gqlInsufficientFunds("")
	}
	return err
}
