package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"ironflyer/core/orchestrator/internal/ai/domain"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
)

// SetCoverageEnabled toggles the test-coverage capability for a user project
// and (optionally) pins its overall-coverage floor. The CoverageGate reads
// Project.Settings on its next run.
func (r *mutationResolver) SetCoverageEnabled(ctx context.Context, projectID string, enabled bool, minPct *float64) (*model.CoverageReport, error) {
	if _, err := r.requireOperateProject(ctx, projectID); err != nil {
		return nil, err
	}
	updated, err := r.Projects.Update(projectID, func(p *domain.Project) {
		p.Settings.CoverageEnabled = enabled
		if minPct != nil {
			p.Settings.CoverageMinPct = *minPct
		}
	})
	if err != nil {
		return nil, err
	}
	return coverageReportModel(updated), nil
}

// CoverageReport returns the project's coverage toggle + the latest stored
// report (empty when coverage has not run yet).
func (r *queryResolver) CoverageReport(ctx context.Context, projectID string) (*model.CoverageReport, error) {
	p, err := r.requireOperateProject(ctx, projectID)
	if err != nil {
		return nil, err
	}
	return coverageReportModel(p), nil
}
