package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
	"ironflyer/core/orchestrator/internal/operations/operator"
	"time"
)

// ProfitDashboard is the resolver for the profitDashboard field.
//
// Per-tenant view (bug #16 fix): the resolver derives the caller's
// tenant id from the authenticated user and passes it through the
// Service so the underlying adapter scopes WHERE tenant_id = $1.
// Unauthenticated callers get UNAUTHENTICATED — never platform-wide
// numbers.
func (r *queryResolver) ProfitDashboard(ctx context.Context, since time.Time, until time.Time) (*model.ProfitDashboard, error) {
	if r.Dashboards == nil {
		return nil, gqlNotConfigured("dashboards")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	d, err := r.Dashboards.Profit(ctx, tenantFor(u), since, until)
	if err != nil {
		return nil, err
	}
	return &model.ProfitDashboard{
		WindowStart:       d.WindowStart,
		WindowEnd:         d.WindowEnd,
		RevenueUsd:        d.RevenueUSD,
		ProviderCostUsd:   d.ProviderCostUSD,
		SandboxCostUsd:    d.SandboxCostUSD,
		OtherCostUsd:      d.OtherCostUSD,
		GrossProfitUsd:    d.GrossProfitUSD,
		GrossMarginPct:    d.GrossMarginPct,
		ActiveExecutions:  d.ActiveExecutions,
		BlockedExecutions: d.BlockedExecutions,
		RefundCount:       d.RefundCount,
		TopUpRate:         d.TopUpRate,
	}, nil
}

// ScaleDashboard is the resolver for the scaleDashboard field.
//
// Operator-only: scale data is platform-wide (queue depth, sandbox
// capacity, utilization across all pools) and has no per-tenant
// meaning. Non-operator callers get FORBIDDEN.
func (r *queryResolver) ScaleDashboard(ctx context.Context) (*model.ScaleDashboard, error) {
	if r.Dashboards == nil {
		return nil, gqlNotConfigured("dashboards")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	if !operator.IsOperator(ctx) {
		return nil, gqlForbiddenOperator()
	}
	d, err := r.Dashboards.ScaleDashboard(ctx)
	if err != nil {
		return nil, err
	}
	return &model.ScaleDashboard{
		ActiveExecutions:     d.ActiveExecutions,
		QueuedExecutions:     d.QueuedExecutions,
		QueueWaitSec:         d.QueueWaitSec,
		SandboxCapacity:      d.SandboxCapacity,
		WorkerUtilizationPct: d.WorkerUtilizationPct,
		ScaleHealth:          d.ScaleHealth,
	}, nil
}

// CohortDashboard is the resolver for the cohortDashboard field.
//
// Per-tenant view: cohort rows are built only from the caller's own
// executions (bug #16 fix). Unauthenticated callers get
// UNAUTHENTICATED — never platform-wide cohorts.
func (r *queryResolver) CohortDashboard(ctx context.Context, sinceMonth time.Time) (*model.CohortDashboard, error) {
	if r.Dashboards == nil {
		return nil, gqlNotConfigured("dashboards")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	d, err := r.Dashboards.Cohort(ctx, tenantFor(u), sinceMonth)
	if err != nil {
		return nil, err
	}
	out := make([]model.Cohort, 0, len(d.Cohorts))
	for _, c := range d.Cohorts {
		out = append(out, model.Cohort{
			Month:                 c.Month,
			NewPayingUsers:        c.NewPayingUsers,
			SecondExecutionUsers:  c.SecondExecutionUsers,
			Day7RepeatUsers:       c.Day7RepeatUsers,
			Day30RepeatUsers:      c.Day30RepeatUsers,
			AvgSpendUsd:           c.AvgSpendUSD,
			GrossMarginPct:        c.GrossMarginPct,
			CompletionRate:        c.CompletionRate,
			RefundRate:            c.RefundRate,
			SupportTicketsPerExec: c.SupportTicketsPerExec,
		})
	}
	return &model.CohortDashboard{Cohorts: out}, nil
}

// BlueprintDashboard is the resolver for the blueprintDashboard field.
//
// Per-tenant view: blueprint stats are rolled up only from the
// caller's own blueprint_runs (bug #16 fix). The platform-wide
// rollup never reaches a signed-in customer's dashboard.
func (r *queryResolver) BlueprintDashboard(ctx context.Context) (*model.BlueprintDashboard, error) {
	if r.Dashboards == nil {
		return nil, gqlNotConfigured("dashboards")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	d, err := r.Dashboards.BlueprintDashboard(ctx, tenantFor(u))
	if err != nil {
		return nil, err
	}
	out := make([]model.DashboardBlueprintStats, 0, len(d.Blueprints))
	for _, b := range d.Blueprints {
		out = append(out, model.DashboardBlueprintStats{
			BlueprintID:        b.BlueprintID,
			Executions:         b.Executions,
			AvgRevenueUsd:      b.AvgRevenueUSD,
			AvgCostUsd:         b.AvgCostUSD,
			GrossMarginPct:     b.GrossMarginPct,
			PreviewSuccess:     b.PreviewSuccess,
			Refunds:            b.Refunds,
			RepairCount:        b.RepairCount,
			AvgCompletionScore: b.AvgCompletionScore,
		})
	}
	return &model.BlueprintDashboard{Blueprints: out}, nil
}

// HealthDashboard is the resolver for the healthDashboard field. It
// composes Capability Atlas Stats, the architecture manifest, and the
// configured Anti-Bloat report files into a single HealthMetrics
// payload. The resolver requires an authenticated caller — Code
// Health is operator-facing today and never carries cross-tenant
// signal.
func (r *queryResolver) HealthDashboard(ctx context.Context) (*model.HealthMetrics, error) {
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}

	out := &model.HealthMetrics{
		ReuseRate:            -1,
		DedupRate:            -1,
		DeadCodeCount:        -1,
		DependencyCycles:     -1,
		ComplexityHistogram:  []model.ComplexityBucket{},
		DuplicationByDir:     []model.DirDup{},
		BundleByRoute:        []model.RouteBundle{},
		AtlasCapabilityCount: 0,
		LocPerCapability:     0,
		Architecture:         model.Architecture{Layers: []string{}, Rules: []model.ArchRule{}, Cycles: ""},
	}

	// Atlas snapshot — counts + last-indexed timestamp.
	if r.AtlasStore != nil {
		if stats, err := r.AtlasStore.Stats(ctx); err == nil {
			out.AtlasCapabilityCount = stats.Total
			if !stats.LastIndexed.IsZero() {
				t := stats.LastIndexed
				out.LastIndexedAt = &t
			}
		}
	}

	// Architecture manifest projection — empty layers means the
	// manifest was missing at boot.
	if len(r.ArchManifest.Layers) > 0 {
		layers := make([]string, len(r.ArchManifest.Layers))
		copy(layers, r.ArchManifest.Layers)
		out.Architecture.Layers = layers
	}
	if len(r.ArchManifest.Rules) > 0 {
		rules := make([]model.ArchRule, 0, len(r.ArchManifest.Rules))
		for _, rl := range r.ArchManifest.Rules {
			rules = append(rules, model.ArchRule{From: rl.From, To: rl.To, Allow: rl.Allow})
		}
		out.Architecture.Rules = rules
	}
	if r.ArchManifest.Cycles != "" {
		out.Architecture.Cycles = r.ArchManifest.Cycles
	}

	// Anti-Bloat report projections — each file is optional. Parse
	// failures degrade silently to the sentinel shape rather than
	// surfacing an error to the cockpit.
	if path := r.HealthReportPaths.Dedup; path != "" {
		if rate, dirs, ok := readDedupReport(path); ok {
			out.DedupRate = rate
			out.DuplicationByDir = dirs
		}
	}
	if path := r.HealthReportPaths.Deadcode; path != "" {
		if n, ok := readDeadcodeReport(path); ok {
			out.DeadCodeCount = n
		}
	}
	if path := r.HealthReportPaths.Complexity; path != "" {
		if hist, ok := readComplexityReport(path); ok {
			out.ComplexityHistogram = hist
		}
	}
	if path := r.HealthReportPaths.DepCycle; path != "" {
		if cycles, ok := readDepCycleReport(path); ok {
			out.DependencyCycles = cycles
		}
	}
	if path := r.HealthReportPaths.Bundle; path != "" {
		if routes, ok := readBundleReport(path); ok {
			out.BundleByRoute = routes
		}
	}

	return out, nil
}
