package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
	"ironflyer/core/orchestrator/internal/operations/mobile/devicecloud"
	"strings"
	"time"

	"github.com/google/uuid"
)

// DeviceCloudStartSession is the resolver for the deviceCloudStartSession field.
// Allocates a real-device session against the chosen Pro-tier provider,
// writes an opening ledger entry, and returns the embeddable session
// URL the cockpit drops into an <iframe>.
//
// Per-user isolation: projectID is resolved through the store with an
// owner check before the provider call so a logged-in user can never
// fan a session out against a project they don't own.
func (r *mutationResolver) DeviceCloudStartSession(ctx context.Context, input model.DeviceCloudStartInput) (*model.DeviceCloudSession, error) {
	if r.DeviceCloud == nil {
		return nil, gqlNotConfigured("device cloud")
	}
	user, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	project, err := r.Projects.Get(input.ProjectID)
	if err != nil {
		return nil, fmt.Errorf("device cloud: load project: %w", err)
	}
	if !project.IsAccessibleBy(user.ID) {
		return nil, errors.New("device cloud: project not found")
	}

	provider := devicecloud.Provider(strings.ToLower(strings.TrimSpace(input.Provider)))
	if provider != devicecloud.ProviderBrowserStack && provider != devicecloud.ProviderAWSDeviceFarm {
		return nil, fmt.Errorf("device cloud: unsupported provider %q", input.Provider)
	}

	length := 30 * time.Minute
	if input.SessionLengthMinutes != nil && *input.SessionLengthMinutes > 0 {
		length = time.Duration(*input.SessionLengthMinutes) * time.Minute
	}

	tenantID := mobileTenantUUID(project)
	sess, err := r.DeviceCloud.StartInteractiveSession(ctx, tenantID, project.ID, input.WorkspaceID, devicecloud.StartSessionRequest{
		AppURL:        input.AppURL,
		DeviceID:      input.DeviceID,
		SessionLength: length,
	}, provider)
	if err != nil {
		return nil, err
	}
	return deviceCloudSessionToGraphQL(sess), nil
}

// DeviceCloudEndSession is the resolver for the deviceCloudEndSession field.
// Tears down the provider session and writes the reconciling ledger
// entry. The provider argument is required because session IDs are not
// globally unique across vendors.
func (r *mutationResolver) DeviceCloudEndSession(ctx context.Context, sessionID string, provider string) (bool, error) {
	if r.DeviceCloud == nil {
		return false, gqlNotConfigured("device cloud")
	}
	if _, err := currentUser(ctx); err != nil {
		return false, err
	}
	p := devicecloud.Provider(strings.ToLower(strings.TrimSpace(provider)))
	// projectID + workspaceID are best-effort metadata for the ledger
	// here — the Manager carries the started-at clock so the reconcile
	// math is correct even without them. Tenant is uuid.Nil because the
	// EndSession mutation only carries the session id; the opening
	// ledger row already tagged the tenant.
	if err := r.DeviceCloud.EndSession(ctx, uuid.Nil, "", "", sessionID, p); err != nil {
		return false, err
	}
	return true, nil
}

// DeviceCloudDevices is the resolver for the deviceCloudDevices field.
// Fans the catalogue across every registered provider. platform is
// "android" or "ios"; an empty string returns everything (the cockpit
// uses this when the picker tab hasn't been chosen yet).
func (r *queryResolver) DeviceCloudDevices(ctx context.Context, platform string) ([]model.DeviceCloudDevice, error) {
	if r.DeviceCloud == nil {
		return []model.DeviceCloudDevice{}, nil
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	devs, err := r.DeviceCloud.ListAllDevices(ctx, platform)
	if err != nil {
		// Don't fail the picker on a single provider 502; the manager
		// already logged it. Return whatever subset succeeded.
		if errors.Is(err, devicecloud.ErrProviderNotConfigured) {
			return []model.DeviceCloudDevice{}, nil
		}
		return nil, err
	}
	out := make([]model.DeviceCloudDevice, 0, len(devs))
	for _, d := range devs {
		out = append(out, deviceCloudDeviceToGraphQL(d))
	}
	return out, nil
}
