package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
	"ironflyer/core/orchestrator/internal/operations/operator"
	"time"
)

// RecentErrors is the resolver for the recentErrors field. Returns the
// aggregated error classes recorded by the diagnostics ring buffer.
// Operator-gated: non-operator principals get an empty slice rather
// than a permission error, mirroring the surface the operator
// dashboard expects (the same UI panel is rendered for every operator;
// permission gating happens at the link to the dashboard).
func (r *queryResolver) RecentErrors(ctx context.Context, limit *int) ([]model.ErrorAggregate, error) {
	if r.Diagnostics == nil {
		return []model.ErrorAggregate{}, nil
	}
	if err := operator.RequireOperator(ctx); err != nil {
		return []model.ErrorAggregate{}, nil
	}
	n := 50
	if limit != nil && *limit > 0 {
		n = *limit
	}
	rows := r.Diagnostics.RecentErrors(n)
	out := make([]model.ErrorAggregate, 0, len(rows))
	for _, a := range rows {
		entry := model.ErrorAggregate{
			Class:       a.Class,
			Count:       a.Count,
			LastSeen:    a.LastSeen,
			LastMessage: a.LastMessage,
			LastLevel:   a.LastLevel,
		}
		if a.SampleRequestID != "" {
			s := a.SampleRequestID
			entry.SampleRequestID = &s
		}
		out = append(out, entry)
	}
	return out, nil
}

// RecentLogs is the resolver for the recentLogs field. Walks the
// diagnostics ring buffer for entries newer than `since`, filtered by
// minLevel (default warn). Operator-gated like RecentErrors.
func (r *queryResolver) RecentLogs(ctx context.Context, since *time.Time, limit *int, minLevel *string) ([]model.LogEntry, error) {
	if r.Diagnostics == nil {
		return []model.LogEntry{}, nil
	}
	if err := operator.RequireOperator(ctx); err != nil {
		return []model.LogEntry{}, nil
	}
	var sinceT time.Time
	if since != nil {
		sinceT = *since
	}
	n := 200
	if limit != nil && *limit > 0 {
		n = *limit
	}
	level := "warn"
	if minLevel != nil && *minLevel != "" {
		level = *minLevel
	}
	rows := r.Diagnostics.RecentLogs(sinceT, n, level)
	out := make([]model.LogEntry, 0, len(rows))
	for _, e := range rows {
		entry := model.LogEntry{
			Time:    e.Time,
			Level:   e.Level,
			Message: e.Message,
			Fields:  toJSONFields(e.Fields),
		}
		if e.RequestID != "" {
			rid := e.RequestID
			entry.RequestID = &rid
		}
		if e.TenantID != "" {
			tid := e.TenantID
			entry.TenantID = &tid
		}
		if e.ExecutionID != "" {
			eid := e.ExecutionID
			entry.ExecutionID = &eid
		}
		out = append(out, entry)
	}
	return out, nil
}
