package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"ironflyer/core/orchestrator/internal/operations/graph/model"
	"ironflyer/core/orchestrator/internal/suppliers/figma"
)

// ImportFigma is the resolver for the importFigma field.
func (r *mutationResolver) ImportFigma(ctx context.Context, fileKey string) (*model.FigmaExtract, error) {
	if r.Figma == nil {
		return nil, gqlNotConfigured("figma")
	}
	extract, err := r.Figma.Extract(ctx, fileKey)
	if err != nil {
		return nil, err
	}
	return figmaExtractToGraph(extract), nil
}

func figmaExtractToGraph(extract *figma.Extract) *model.FigmaExtract {
	if extract == nil {
		return nil
	}
	out := &model.FigmaExtract{
		FileKey:    extract.FileKey,
		Name:       extract.Name,
		Colors:     make([]model.FigmaColorToken, 0, len(extract.Colors)),
		Typography: make([]model.FigmaTypographyToken, 0, len(extract.Typography)),
		Spacing:    append([]float64(nil), extract.Spacing...),
		Radii:      append([]float64(nil), extract.Radii...),
		Components: make([]model.FigmaComponent, 0, len(extract.Components)),
		Frames:     make([]model.FigmaFrame, 0, len(extract.Frames)),
	}
	for _, color := range extract.Colors {
		out.Colors = append(out.Colors, model.FigmaColorToken{
			Hex:   color.Hex,
			Alpha: color.Alpha,
		})
	}
	for _, typ := range extract.Typography {
		out.Typography = append(out.Typography, model.FigmaTypographyToken{
			FontFamily: typ.FontFamily,
			FontSize:   typ.FontSize,
			FontWeight: typ.FontWeight,
			LineHeight: typ.LineHeight,
		})
	}
	for _, component := range extract.Components {
		out.Components = append(out.Components, model.FigmaComponent{
			ID:         component.ID,
			Name:       component.Name,
			Type:       component.Type,
			LayoutMode: stringPtrIfSet(component.LayoutMode),
			Width:      component.Width,
			Height:     component.Height,
			Children:   component.Children,
		})
	}
	for _, frame := range extract.Frames {
		out.Frames = append(out.Frames, model.FigmaFrame{
			ID:       frame.ID,
			Name:     frame.Name,
			Width:    frame.Width,
			Height:   frame.Height,
			ImageURL: stringPtrIfSet(frame.ImageURL),
		})
	}
	return out
}

func stringPtrIfSet(v string) *string {
	if v == "" {
		return nil
	}
	return &v
}
