package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"

	"github.com/shopspring/decimal"

	"ironflyer/core/orchestrator/internal/business/guild"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
)

// UpsertFinisherProfile is the resolver for the upsertFinisherProfile field.
func (r *mutationResolver) UpsertFinisherProfile(ctx context.Context, displayName string, skills []string, hourlyRateUsd string) (*model.FinisherProfile, error) {
	if r.GuildCoord == nil {
		return nil, gqlNotConfigured("guild")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	rate, err := decimal.NewFromString(hourlyRateUsd)
	if err != nil {
		return nil, guild.ErrInvalidAmount
	}
	p, err := r.GuildCoord.Service().UpsertFinisherProfile(ctx, guild.FinisherProfile{
		UserID:        u.ID,
		DisplayName:   displayName,
		Skills:        skills,
		HourlyRateUSD: rate,
	})
	if err != nil {
		return nil, err
	}
	out := profileToGraphQL(p)
	return &out, nil
}

// CreateGuildTask is the resolver for the createGuildTask field.
func (r *mutationResolver) CreateGuildTask(ctx context.Context, projectID string, title string, description string, priceUSDFloor string, slaHours int) (*model.GuildTask, error) {
	if r.GuildCoord == nil {
		return nil, gqlNotConfigured("guild")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	// Owner-check via projects store — non-owners 404.
	project, err := r.requireOwnedProject(projectID, u.ID)
	if err != nil {
		return nil, err
	}
	floor, err := decimal.NewFromString(priceUSDFloor)
	if err != nil {
		return nil, guild.ErrInvalidAmount
	}
	t, err := r.GuildCoord.CreateTask(ctx, projectID, tenantFor(u), title, description, floor, slaHours)
	if err != nil {
		return nil, err
	}
	out := r.taskToGraphQL(ctx, t, project)
	return &out, nil
}

// PlaceBid is the resolver for the placeBid field.
func (r *mutationResolver) PlaceBid(ctx context.Context, taskID string, priceUsd string, estimatedHours int, note string) (*model.Bid, error) {
	if r.GuildCoord == nil {
		return nil, gqlNotConfigured("guild")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	profile, err := r.GuildCoord.Service().GetFinisherProfileByUser(ctx, u.ID)
	if err != nil {
		if errors.Is(err, guild.ErrNotFound) {
			return nil, guild.ErrForbidden
		}
		return nil, err
	}
	price, err := decimal.NewFromString(priceUsd)
	if err != nil {
		return nil, guild.ErrInvalidAmount
	}
	b, err := r.GuildCoord.PlaceBid(ctx, taskID, profile.ID, price, estimatedHours, note)
	if err != nil {
		return nil, err
	}
	out, err := r.bidToGraphQL(ctx, b)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// AcceptBid is the resolver for the acceptBid field.
func (r *mutationResolver) AcceptBid(ctx context.Context, bidID string) (*model.GuildTask, error) {
	if r.GuildCoord == nil {
		return nil, gqlNotConfigured("guild")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	bid, err := r.GuildCoord.Service().GetBid(ctx, bidID)
	if err != nil {
		return nil, err
	}
	task, err := r.GuildCoord.Service().GetTask(ctx, bid.TaskID)
	if err != nil {
		return nil, err
	}
	project, err := r.requireOwnedProject(task.ProjectID, u.ID)
	if err != nil {
		return nil, err
	}
	updated, err := r.GuildCoord.AcceptBid(ctx, bidID)
	if err != nil {
		return nil, err
	}
	out := r.taskToGraphQL(ctx, updated, project)
	return &out, nil
}

// RejectTask is the resolver for the rejectTask field.
func (r *mutationResolver) RejectTask(ctx context.Context, taskID string, reason string) (*model.GuildTask, error) {
	if r.GuildCoord == nil {
		return nil, gqlNotConfigured("guild")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	task, err := r.GuildCoord.Service().GetTask(ctx, taskID)
	if err != nil {
		return nil, err
	}
	project, err := r.requireOwnedProject(task.ProjectID, u.ID)
	if err != nil {
		return nil, err
	}
	updated, err := r.GuildCoord.RejectTask(ctx, taskID, reason)
	if err != nil {
		return nil, err
	}
	out := r.taskToGraphQL(ctx, updated, project)
	return &out, nil
}

// InstallTemplate is the resolver for the installTemplate field.
func (r *mutationResolver) InstallTemplate(ctx context.Context, slug string, projectID string) (*model.Template, error) {
	if r.GuildCoord == nil {
		return nil, gqlNotConfigured("guild")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	if _, err := r.requireOwnedProject(projectID, u.ID); err != nil {
		return nil, err
	}
	t, err := r.GuildCoord.InstallTemplate(ctx, slug, projectID, tenantFor(u))
	if err != nil {
		return nil, err
	}
	out, err := r.templateToGraphQL(ctx, t)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MyFinisherProfile is the resolver for the myFinisherProfile field.
func (r *queryResolver) MyFinisherProfile(ctx context.Context) (*model.FinisherProfile, error) {
	if r.GuildCoord == nil {
		return nil, gqlNotConfigured("guild")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	p, err := r.GuildCoord.Service().GetFinisherProfileByUser(ctx, u.ID)
	if err != nil {
		if errors.Is(err, guild.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	out := profileToGraphQL(p)
	return &out, nil
}

// GuildTasks is the resolver for the guildTasks field.
func (r *queryResolver) GuildTasks(ctx context.Context, status *string, mine *bool) ([]model.GuildTask, error) {
	if r.GuildCoord == nil {
		return nil, gqlNotConfigured("guild")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	filter := guild.TaskFilter{}
	if status != nil {
		filter.Status = *status
	}
	if mine != nil && *mine {
		filter.TenantID = tenantFor(u)
	}
	rows, err := r.GuildCoord.Service().ListTasks(ctx, filter)
	if err != nil {
		return nil, err
	}
	out := make([]model.GuildTask, 0, len(rows))
	for _, t := range rows {
		project, perr := r.lookupProject(t.ProjectID)
		if perr != nil {
			continue
		}
		out = append(out, r.taskToGraphQL(ctx, t, project))
	}
	return out, nil
}

// GuildTask is the resolver for the guildTask field.
func (r *queryResolver) GuildTask(ctx context.Context, id string) (*model.GuildTask, error) {
	if r.GuildCoord == nil {
		return nil, gqlNotConfigured("guild")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	t, err := r.GuildCoord.Service().GetTask(ctx, id)
	if err != nil {
		if errors.Is(err, guild.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	if t.TenantID != tenantFor(u) {
		// Unleakable existence — 404, not 403.
		return nil, nil
	}
	project, err := r.lookupProject(t.ProjectID)
	if err != nil {
		return nil, nil
	}
	out := r.taskToGraphQL(ctx, t, project)
	return &out, nil
}

// Templates is the resolver for the templates field.
func (r *queryResolver) Templates(ctx context.Context, verifiedOnly *bool) ([]model.Template, error) {
	if r.GuildCoord == nil {
		return nil, gqlNotConfigured("guild")
	}
	v := true
	if verifiedOnly != nil {
		v = *verifiedOnly
	}
	rows, err := r.GuildCoord.Service().ListTemplates(ctx, v)
	if err != nil {
		return nil, err
	}
	out := make([]model.Template, 0, len(rows))
	for _, t := range rows {
		m, err := r.templateToGraphQL(ctx, t)
		if err != nil {
			continue
		}
		out = append(out, m)
	}
	return out, nil
}

// Template is the resolver for the template field.
func (r *queryResolver) Template(ctx context.Context, slug string) (*model.Template, error) {
	if r.GuildCoord == nil {
		return nil, gqlNotConfigured("guild")
	}
	t, err := r.GuildCoord.Service().GetTemplateBySlug(ctx, slug)
	if err != nil {
		if errors.Is(err, guild.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	out, err := r.templateToGraphQL(ctx, t)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
