package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
	"ironflyer/core/orchestrator/internal/business/ledger"
	"time"

	"github.com/google/uuid"
)

// Ledger is the resolver for the ledger field.
func (r *queryResolver) Ledger(ctx context.Context, filter *model.LedgerFilter) ([]model.WalletLedgerEntry, error) {
	if r.LedgerSvc == nil {
		return nil, gqlNotConfigured("ledger")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	tenantUUID, err := uuid.Parse(tenantFor(u))
	if err != nil {
		// Fallback for non-UUID tenant ids (memory dev): synthesise a
		// stable UUIDv5 so the ledger service still has a typed key.
		tenantUUID = uuid.NewSHA1(uuid.NameSpaceURL, []byte(tenantFor(u)))
	}

	f := ledger.Filter{Limit: 100}
	if filter != nil {
		if filter.Since != nil {
			f.Since = *filter.Since
		}
		if filter.Until != nil {
			f.Until = *filter.Until
		}
		if filter.Limit != nil && *filter.Limit > 0 {
			f.Limit = *filter.Limit
		}
		if filter.Offset != nil && *filter.Offset > 0 {
			f.Offset = *filter.Offset
		}
		if filter.ExecutionID != nil && *filter.ExecutionID != "" {
			eid, perr := uuid.Parse(*filter.ExecutionID)
			if perr == nil {
				f.ExecutionID = &eid
			}
		}
		for _, t := range filter.Types {
			et := ledger.EntryType(t)
			if et.IsValid() {
				f.EntryTypes = append(f.EntryTypes, et)
			}
		}
	}

	rows, err := r.LedgerSvc.ListByTenant(ctx, tenantUUID, f)
	if err != nil {
		return nil, err
	}
	return ledgerRowsToGraphQL(rows), nil
}

// LedgerRollup is the resolver for the ledgerRollup field.
//
// TODO(mobile-costs): the rollup computed by r.LedgerSvc.TenantRollup
// now carries five mobile-cost legs (MobileBuildCostUSD,
// EmulatorCostUSD, MacWorkspaceCostUSD, EASBuildCostUSD,
// AppetizeCostUSD) plus a MobileCostUSD aggregate. These fields are
// NOT yet wired into the GraphQL LedgerRollup type — extending
// core/orchestrator/internal/graph/schema/ledger.graphql and running
// gqlgen is its own ticket. Until then the legs are computed inside
// the orchestrator and visible via direct ledger access only.
func (r *queryResolver) LedgerRollup(ctx context.Context, since time.Time, until time.Time) (*model.LedgerRollup, error) {
	if r.LedgerSvc == nil {
		return nil, gqlNotConfigured("ledger")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	tenantUUID, err := uuid.Parse(tenantFor(u))
	if err != nil {
		tenantUUID = uuid.NewSHA1(uuid.NameSpaceURL, []byte(tenantFor(u)))
	}
	roll, err := r.LedgerSvc.TenantRollup(ctx, tenantUUID, since, until)
	if err != nil {
		return nil, err
	}
	return &model.LedgerRollup{
		RevenueUsd:              floatOfDecimal(roll.RevenueUSD),
		ProviderCostUsd:         floatOfDecimal(roll.ProviderCostUSD),
		SandboxCostUsd:          floatOfDecimal(roll.SandboxCostUSD),
		StorageCostUsd:          floatOfDecimal(roll.StorageCostUSD),
		DeploymentCostUsd:       floatOfDecimal(roll.DeploymentCostUSD),
		PremiumReasoningCostUsd: floatOfDecimal(roll.PremiumReasoningCostUSD),
		RefundsUsd:              floatOfDecimal(roll.RefundsUSD),
		PlatformMarginUsd:       floatOfDecimal(roll.PlatformMarginUSD),
		GrossMarginPct:          floatOfDecimal(roll.GrossMarginPct),
	}, nil
}

// ExecutionLedger is the resolver for the executionLedger field.
// Owner-scoped: the caller must own the execution's tenant. We fetch
// the execution first so the per-tenant check lands before any
// ledger read, then slice the oldest-first feed by limit/offset
// before projecting. The underlying ledger.Service.ListByExecution
// already returns ASC chronological order; pagination here is a
// Go-side window so we don't have to expand the service signature
// (additive-only constraint).
func (r *queryResolver) ExecutionLedger(ctx context.Context, executionID string, limit *int, offset *int) ([]model.WalletLedgerEntry, error) {
	if r.LedgerSvc == nil {
		return nil, gqlNotConfigured("ledger")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	eid, err := uuid.Parse(executionID)
	if err != nil {
		return nil, err
	}
	// Owner check via the execution row's tenant. ExecutionSvc may be
	// unwired on stripped-down dev boots; in that case we fall back to
	// the ledger fetch without the tenant gate so the dev surface
	// keeps working. Production always wires ExecutionSvc.
	if r.ExecutionSvc != nil {
		exec, gerr := r.ExecutionSvc.Get(ctx, executionID)
		if gerr != nil {
			return nil, gerr
		}
		if exec.TenantID != "" && exec.TenantID != tenantFor(u) {
			return nil, errUnauthenticated
		}
	}
	rows, err := r.LedgerSvc.ListByExecution(ctx, eid)
	if err != nil {
		return nil, err
	}
	lim := 100
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	off := 0
	if offset != nil && *offset > 0 {
		off = *offset
	}
	if off >= len(rows) {
		return []model.WalletLedgerEntry{}, nil
	}
	end := off + lim
	if end > len(rows) {
		end = len(rows)
	}
	return ledgerRowsToGraphQL(rows[off:end]), nil
}

// TenantProfitToday is the resolver for the tenantProfitToday field.
//
// Returns the same shape as LedgerRollup but pinned to today's UTC
// window — answers "are we currently making money on this tenant?"
// without forcing the caller to construct a DateTime range. The
// projection mirrors LedgerRollup exactly; any divergence between
// the two is a bug.
func (r *queryResolver) TenantProfitToday(ctx context.Context) (*model.LedgerRollup, error) {
	if r.LedgerSvc == nil {
		return nil, gqlNotConfigured("ledger")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	tenantUUID, err := uuid.Parse(tenantFor(u))
	if err != nil {
		tenantUUID = uuid.NewSHA1(uuid.NameSpaceURL, []byte(tenantFor(u)))
	}
	now := time.Now().UTC()
	startOfDay := time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.UTC)
	roll, err := r.LedgerSvc.TenantRollup(ctx, tenantUUID, startOfDay, now)
	if err != nil {
		return nil, err
	}
	return &model.LedgerRollup{
		RevenueUsd:              floatOfDecimal(roll.RevenueUSD),
		ProviderCostUsd:         floatOfDecimal(roll.ProviderCostUSD),
		SandboxCostUsd:          floatOfDecimal(roll.SandboxCostUSD),
		StorageCostUsd:          floatOfDecimal(roll.StorageCostUSD),
		DeploymentCostUsd:       floatOfDecimal(roll.DeploymentCostUSD),
		PremiumReasoningCostUsd: floatOfDecimal(roll.PremiumReasoningCostUSD),
		RefundsUsd:              floatOfDecimal(roll.RefundsUSD),
		PlatformMarginUsd:       floatOfDecimal(roll.PlatformMarginUSD),
		GrossMarginPct:          floatOfDecimal(roll.GrossMarginPct),
	}, nil
}
