package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
)

// McpEnable is the resolver for the mcpEnable field.
func (r *mutationResolver) McpEnable(ctx context.Context, projectID string, serverID string) (*model.MCPRunningServer, error) {
	panic(fmt.Errorf("not implemented: McpEnable - mcpEnable"))
}

// McpDisable is the resolver for the mcpDisable field.
func (r *mutationResolver) McpDisable(ctx context.Context, projectID string, serverID string) (bool, error) {
	panic(fmt.Errorf("not implemented: McpDisable - mcpDisable"))
}

// McpCatalog is the resolver for the mcpCatalog field.
func (r *queryResolver) McpCatalog(ctx context.Context) ([]model.MCPServerSpec, error) {
	panic(fmt.Errorf("not implemented: McpCatalog - mcpCatalog"))
}

// McpEnabled is the resolver for the mcpEnabled field.
func (r *queryResolver) McpEnabled(ctx context.Context, projectID string) ([]model.MCPRunningServer, error) {
	panic(fmt.Errorf("not implemented: McpEnabled - mcpEnabled"))
}
