package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
	"ironflyer/core/orchestrator/internal/operations/mobile/eas"
	"strings"
	"time"
)

// MobileTriggerBuild is the resolver for the mobileTriggerBuild field.
//
// EAS builds are dispatched from the workspace shell via the
// `eas build --no-wait` runtime path (see core/runtime/internal/mobile/
// expo_build.go). The orchestrator-side trigger here picks up the most
// recent non-terminal build for the requested platform and registers
// it with the background poller so the subscription + ledger + artifact
// flow take over.
func (r *mutationResolver) MobileTriggerBuild(ctx context.Context, input model.MobileTriggerBuildInput) (*model.MobileBuild, error) {
	client, project, err := r.mobileClientForProject(ctx, input.ProjectID)
	if err != nil {
		return nil, err
	}
	platform := strings.ToLower(strings.TrimSpace(input.Platform))
	if platform != "ios" && platform != "android" {
		return nil, fmt.Errorf("mobile: invalid platform %q (want ios|android)", input.Platform)
	}
	easProjectID := mobileEASProjectID(project)
	if easProjectID == "" {
		return nil, errors.New("mobile: project has no EAS project id (set MobileStack.EAS.ProjectID)")
	}
	builds, err := client.ListBuilds(ctx, easProjectID, eas.ListBuildsOpts{
		Platform: platform,
		Limit:    10,
	})
	if err != nil {
		return nil, fmt.Errorf("mobile: list builds: %w", err)
	}
	var pick *eas.Build
	for _, b := range builds {
		if b == nil {
			continue
		}
		if !b.Status.Terminal() {
			pick = b
			break
		}
	}
	if pick == nil {
		return nil, errors.New("mobile: no in-flight EAS build to track — dispatch via the workspace shell first")
	}
	if r.EASPoller != nil {
		r.EASPoller.Track(eas.TrackOpts{
			BuildID:   pick.ID,
			ProjectID: project.ID,
			TenantID:  mobileTenantUUID(project),
		})
	}
	return mobileBuildToGraphQL(pick), nil
}

// MobileCancelBuild is the resolver for the mobileCancelBuild field.
func (r *mutationResolver) MobileCancelBuild(ctx context.Context, buildID string) (bool, error) {
	if r.EAS == nil || !r.EAS.HasToken() {
		return false, gqlNotConfigured("mobile")
	}
	if _, err := currentUser(ctx); err != nil {
		return false, err
	}
	if err := r.EAS.CancelBuild(ctx, buildID); err != nil {
		return false, err
	}
	if r.EASPoller != nil {
		r.EASPoller.Untrack(buildID)
	}
	return true, nil
}

// MobileSubmitToStore is the resolver for the mobileSubmitToStore field.
func (r *mutationResolver) MobileSubmitToStore(ctx context.Context, input model.MobileSubmitInput) (*model.MobileSubmission, error) {
	client, project, err := r.mobileClientForProject(ctx, input.ProjectID)
	if err != nil {
		return nil, err
	}
	easProjectID := mobileEASProjectID(project)
	if easProjectID == "" {
		return nil, errors.New("mobile: project has no EAS project id (set MobileStack.EAS.ProjectID)")
	}
	platform := strings.ToLower(strings.TrimSpace(input.Platform))
	opts := eas.StoreSubmitOpts{
		Platform:  platform,
		ProjectID: easProjectID,
	}
	switch platform {
	case "ios":
		opts.IOSAppleID = strDeref(input.IosAppleID)
		opts.IOSASCAppID = strDeref(input.IosAscAppID)
		opts.IOSAppleTeamID = strDeref(input.IosAppleTeamID)
		opts.IOSSKU = strDeref(input.IosSku)
		opts.IOSCompanyName = strDeref(input.IosCompanyName)
	case "android":
		opts.AndroidTrack = strDeref(input.AndroidTrack)
		opts.AndroidReleaseStatus = strDeref(input.AndroidReleaseStatus)
		if k := strDeref(input.AndroidServiceAccountKey); k != "" {
			raw, decErr := base64.StdEncoding.DecodeString(k)
			if decErr != nil {
				return nil, fmt.Errorf("mobile: decode androidServiceAccountKey: %w", decErr)
			}
			opts.AndroidServiceAccountKey = raw
		}
	default:
		return nil, fmt.Errorf("mobile: invalid platform %q (want ios|android)", input.Platform)
	}
	sub, err := client.SubmitBuildToStore(ctx, input.BuildID, opts)
	if err != nil {
		return nil, err
	}
	return mobileSubmissionToGraphQL(sub), nil
}

// MobilePublishUpdate is the resolver for the mobilePublishUpdate field.
func (r *mutationResolver) MobilePublishUpdate(ctx context.Context, input model.MobilePublishUpdateInput) (*model.MobileUpdate, error) {
	client, _, err := r.mobileClientForProject(ctx, input.ProjectID)
	if err != nil {
		return nil, err
	}
	branch := strDeref(input.Branch)
	if branch == "" {
		branch = "main"
	}
	message := strDeref(input.Message)
	var extra map[string]any
	if len(input.ManifestExtra) > 0 {
		extra = map[string]any(input.ManifestExtra)
	}
	upd, err := client.PublishOTAUpdate(ctx, input.Channel, branch, message, input.RuntimeVersion, extra)
	if err != nil {
		return nil, err
	}
	return mobileUpdateToGraphQL(upd), nil
}

// MobileBuilds is the resolver for the mobileBuilds field.
func (r *queryResolver) MobileBuilds(ctx context.Context, projectID string) ([]model.MobileBuild, error) {
	client, project, err := r.mobileClientForProject(ctx, projectID)
	if err != nil {
		return nil, err
	}
	easProjectID := mobileEASProjectID(project)
	if easProjectID == "" {
		return []model.MobileBuild{}, nil
	}
	builds, err := client.ListBuilds(ctx, easProjectID, eas.ListBuildsOpts{Limit: 50})
	if err != nil {
		return nil, err
	}
	out := make([]model.MobileBuild, 0, len(builds))
	for _, b := range builds {
		if b == nil {
			continue
		}
		if m := mobileBuildToGraphQL(b); m != nil {
			out = append(out, *m)
		}
	}
	return out, nil
}

// MobileBuild is the resolver for the mobileBuild field.
func (r *queryResolver) MobileBuild(ctx context.Context, buildID string) (*model.MobileBuild, error) {
	if r.EAS == nil || !r.EAS.HasToken() {
		return nil, gqlNotConfigured("mobile")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	b, err := r.EAS.GetBuild(ctx, buildID)
	if err != nil {
		return nil, err
	}
	return mobileBuildToGraphQL(b), nil
}

// MobileSubmissions is the resolver for the mobileSubmissions field.
//
// EAS does not currently expose a per-project submissions list under
// /v2/projects/{id}/submissions in the public REST surface — the
// resolver returns an empty list when the project carries no recent
// submission cache and surfaces the per-submission lookup via
// GetSubmission for clients that hold the id. Once the upstream
// endpoint stabilises, fan-out is a one-line change here.
func (r *queryResolver) MobileSubmissions(ctx context.Context, projectID string) ([]model.MobileSubmission, error) {
	if _, _, err := r.mobileClientForProject(ctx, projectID); err != nil {
		return nil, err
	}
	return []model.MobileSubmission{}, nil
}

// MobileBuildStatus is the resolver for the mobileBuildStatus field.
// Polls GetBuild every 10s on the subscription's lifetime and emits a
// snapshot every time the status changes. Closes on terminal status.
func (r *subscriptionResolver) MobileBuildStatus(ctx context.Context, buildID string) (<-chan *model.MobileBuild, error) {
	if r.EAS == nil || !r.EAS.HasToken() {
		return nil, gqlNotConfigured("mobile")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	out := make(chan *model.MobileBuild, 4)
	go func() {
		defer close(out)
		// First emit — clients see the current state without waiting
		// for a status transition.
		first, err := r.EAS.GetBuild(ctx, buildID)
		if err != nil {
			return
		}
		select {
		case out <- mobileBuildToGraphQL(first):
		case <-ctx.Done():
			return
		}
		if first.Status.Terminal() {
			return
		}
		lastStatus := first.Status
		t := time.NewTicker(10 * time.Second)
		defer t.Stop()
		for {
			select {
			case <-ctx.Done():
				return
			case <-t.C:
				b, err := r.EAS.GetBuild(ctx, buildID)
				if err != nil {
					return
				}
				if b.Status == lastStatus {
					continue
				}
				lastStatus = b.Status
				select {
				case out <- mobileBuildToGraphQL(b):
				case <-ctx.Done():
					return
				}
				if b.Status.Terminal() {
					return
				}
			}
		}
	}()
	return out, nil
}
