package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
	"time"
)

// OperatorPendingApprovals is the resolver for the operatorPendingApprovals field.
func (r *queryResolver) OperatorPendingApprovals(ctx context.Context, tenantID *string) ([]model.DeployApproval, error) {
	if r.Operator == nil {
		return nil, gqlNotConfigured("operator")
	}
	tid := ""
	if tenantID != nil {
		tid = *tenantID
	}
	rows, err := r.Operator.PendingApprovals(ctx, tid)
	if err != nil {
		return nil, operatorErrorToGQL(err)
	}
	out := make([]model.DeployApproval, 0, len(rows))
	for i := range rows {
		out = append(out, *approvalToGraphQL(rows[i]))
	}
	return out, nil
}

// OperatorAbuseScore is the resolver for the operatorAbuseScore field.
func (r *queryResolver) OperatorAbuseScore(ctx context.Context, tenantID string, userID string) (*model.AbuseScoreResult, error) {
	if r.Operator == nil {
		return nil, gqlNotConfigured("operator")
	}
	score, tier, err := r.Operator.AbuseScore(ctx, tenantID, userID)
	if err != nil {
		return nil, operatorErrorToGQL(err)
	}
	return &model.AbuseScoreResult{
		TenantID: tenantID,
		UserID:   userID,
		Score:    score,
		Tier:     tier,
	}, nil
}

// OperatorScaleSnapshot is the resolver for the operatorScaleSnapshot field.
func (r *queryResolver) OperatorScaleSnapshot(ctx context.Context) (*model.OperatorScaleSnapshot, error) {
	if r.Operator == nil {
		return nil, gqlNotConfigured("operator")
	}
	snap, err := r.Operator.ScaleSnapshot(ctx)
	if err != nil {
		return nil, operatorErrorToGQL(err)
	}
	return &model.OperatorScaleSnapshot{
		ActiveExecutions:     snap.ActiveExecutions,
		QueuedExecutions:     snap.QueuedExecutions,
		SandboxCapacity:      snap.SandboxCapacity,
		WorkerUtilizationPct: snap.WorkerUtilizationPct,
	}, nil
}

// OperatorWalletSnapshot is the resolver for the operatorWalletSnapshot field.
func (r *queryResolver) OperatorWalletSnapshot(ctx context.Context, tenantID string) (*model.OperatorWalletSnapshot, error) {
	if r.Operator == nil {
		return nil, gqlNotConfigured("operator")
	}
	snap, err := r.Operator.WalletSnapshot(ctx, tenantID)
	if err != nil {
		return nil, operatorErrorToGQL(err)
	}
	return &model.OperatorWalletSnapshot{
		TenantID:         snap.TenantID,
		BalanceUsd:       decToFloat(snap.BalanceUSD),
		HoldUsd:          decToFloat(snap.HoldUSD),
		LifetimeTopUpUsd: decToFloat(snap.LifetimeTopUpUSD),
		LifetimeSpendUsd: decToFloat(snap.LifetimeSpendUSD),
	}, nil
}

// OperatorAuditCursor is the resolver for the operatorAuditCursor field.
func (r *queryResolver) OperatorAuditCursor(ctx context.Context, since time.Time, limit *int) ([]model.OperatorAuditEntry, error) {
	if r.Operator == nil {
		return nil, gqlNotConfigured("operator")
	}
	n := 100
	if limit != nil {
		n = *limit
	}
	rows, err := r.Operator.AuditCursor(ctx, since, n)
	if err != nil {
		return nil, operatorErrorToGQL(err)
	}
	out := make([]model.OperatorAuditEntry, 0, len(rows))
	for _, e := range rows {
		out = append(out, model.OperatorAuditEntry{
			ID:        e.ID,
			Timestamp: e.Timestamp,
			Action:    e.Action,
			Outcome:   e.Outcome,
			Hash:      e.Hash,
		})
	}
	return out, nil
}
