package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
)

// ProfitGuardDecisions is the resolver for the profitGuardDecisions field.
func (r *queryResolver) ProfitGuardDecisions(ctx context.Context, executionID *string, limit *int) ([]model.ProfitGuardDecision, error) {
	if r.ProfitGuardStore == nil {
		return nil, gqlNotConfigured("profitguard")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}
	lim := 100
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	var rows []model.ProfitGuardDecision
	if executionID != nil && *executionID != "" {
		records, err := r.ProfitGuardStore.ListByExecution(ctx, *executionID)
		if err != nil {
			return nil, err
		}
		rows = make([]model.ProfitGuardDecision, 0, len(records))
		for _, rec := range records {
			d := model.ProfitGuardDecision{
				ID:                      itoaInt64(rec.ID),
				ExecutionID:             rec.ExecutionID,
				EnforcementPoint:        string(rec.EnforcementPoint),
				Decision:                string(rec.Decision),
				Reason:                  rec.Reason,
				SpentUsd:                floatOfDecimal(rec.SpentUSD),
				ReservedUsd:             floatOfDecimal(rec.ReservedUSD),
				EstimatedStepCostUsd:    floatOfDecimal(rec.EstimatedStepCostUSD),
				ExpectedCompletionDelta: rec.ExpectedCompletionDelta,
				CreatedAt:               rec.CreatedAt,
			}
			d.ExpectedMarginPct = rec.ExpectedMarginPct
			d.RiskScore = rec.RiskScore
			if rec.RecommendedProvider != "" {
				p := rec.RecommendedProvider
				d.RecommendedProvider = &p
			}
			rows = append(rows, d)
		}
		return rows, nil
	}
	records, err := r.ProfitGuardStore.Recent(ctx, lim)
	if err != nil {
		return nil, err
	}
	rows = make([]model.ProfitGuardDecision, 0, len(records))
	for _, rec := range records {
		d := model.ProfitGuardDecision{
			ID:                      itoaInt64(rec.ID),
			ExecutionID:             rec.ExecutionID,
			EnforcementPoint:        string(rec.EnforcementPoint),
			Decision:                string(rec.Decision),
			Reason:                  rec.Reason,
			SpentUsd:                floatOfDecimal(rec.SpentUSD),
			ReservedUsd:             floatOfDecimal(rec.ReservedUSD),
			EstimatedStepCostUsd:    floatOfDecimal(rec.EstimatedStepCostUSD),
			ExpectedCompletionDelta: rec.ExpectedCompletionDelta,
			CreatedAt:               rec.CreatedAt,
		}
		d.ExpectedMarginPct = rec.ExpectedMarginPct
		d.RiskScore = rec.RiskScore
		if rec.RecommendedProvider != "" {
			p := rec.RecommendedProvider
			d.RecommendedProvider = &p
		}
		rows = append(rows, d)
	}
	return rows, nil
}
