package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
)

// ProvisionResource is the resolver for the provisionResource field.
func (r *mutationResolver) ProvisionResource(ctx context.Context, projectID string, kind string) (*model.ProvisionedResource, error) {
	panic(fmt.Errorf("not implemented: ProvisionResource - provisionResource"))
}

// SuspendResource is the resolver for the suspendResource field.
func (r *mutationResolver) SuspendResource(ctx context.Context, id string) (*model.ProvisionedResource, error) {
	panic(fmt.Errorf("not implemented: SuspendResource - suspendResource"))
}

// ProvisionedResources is the resolver for the provisionedResources field.
func (r *queryResolver) ProvisionedResources(ctx context.Context, projectID string) ([]model.ProvisionedResource, error) {
	panic(fmt.Errorf("not implemented: ProvisionedResources - provisionedResources"))
}

// RevenueEvents is the resolver for the revenueEvents field.
func (r *queryResolver) RevenueEvents(ctx context.Context, resourceID string, limit *int) ([]model.RevenueEvent, error) {
	panic(fmt.Errorf("not implemented: RevenueEvents - revenueEvents"))
}

// AvailableConnectors is the resolver for the availableConnectors field.
func (r *queryResolver) AvailableConnectors(ctx context.Context) ([]model.ConnectorInfo, error) {
	panic(fmt.Errorf("not implemented: AvailableConnectors - availableConnectors"))
}
