package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
)

// PurchaseInsurance is the resolver for the purchaseInsurance field.
func (r *mutationResolver) PurchaseInsurance(ctx context.Context, projectID string, capUsd float64, hours int, requestID *string) (*model.InsurancePolicy, error) {
	panic(fmt.Errorf("not implemented: PurchaseInsurance - purchaseInsurance"))
}

// SentinelForecast is the resolver for the sentinelForecast field.
func (r *queryResolver) SentinelForecast(ctx context.Context, projectID string) (*model.SentinelForecast, error) {
	panic(fmt.Errorf("not implemented: SentinelForecast - sentinelForecast"))
}

// SentinelReroutes is the resolver for the sentinelReroutes field.
func (r *queryResolver) SentinelReroutes(ctx context.Context, projectID string) ([]model.SentinelReroute, error) {
	panic(fmt.Errorf("not implemented: SentinelReroutes - sentinelReroutes"))
}

// InsuranceQuote is the resolver for the insuranceQuote field.
func (r *queryResolver) InsuranceQuote(ctx context.Context, projectID string, capUsd float64, hours int) (*model.InsuranceQuote, error) {
	panic(fmt.Errorf("not implemented: InsuranceQuote - insuranceQuote"))
}

// ActiveInsurance is the resolver for the activeInsurance field.
func (r *queryResolver) ActiveInsurance(ctx context.Context, projectID string) (*model.InsurancePolicy, error) {
	panic(fmt.Errorf("not implemented: ActiveInsurance - activeInsurance"))
}
