package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
)

// PurchaseShipPass is the resolver for the purchaseShipPass field.
func (r *mutationResolver) PurchaseShipPass(ctx context.Context, projectID string, tierKey string, requestID *string) (*model.ShipPass, error) {
	panic(fmt.Errorf("not implemented: PurchaseShipPass - purchaseShipPass"))
}

// CancelShipPass is the resolver for the cancelShipPass field.
func (r *mutationResolver) CancelShipPass(ctx context.Context, passID string) (*model.ShipPass, error) {
	panic(fmt.Errorf("not implemented: CancelShipPass - cancelShipPass"))
}

// ShipPassTiers is the resolver for the shipPassTiers field.
func (r *queryResolver) ShipPassTiers(ctx context.Context) ([]model.ShipPassTier, error) {
	panic(fmt.Errorf("not implemented: ShipPassTiers - shipPassTiers"))
}

// ShipPassQuote is the resolver for the shipPassQuote field.
func (r *queryResolver) ShipPassQuote(ctx context.Context, projectID string, tierKey string) (*model.ShipPassQuote, error) {
	panic(fmt.Errorf("not implemented: ShipPassQuote - shipPassQuote"))
}

// ActiveShipPass is the resolver for the activeShipPass field.
func (r *queryResolver) ActiveShipPass(ctx context.Context, projectID string) (*model.ShipPass, error) {
	panic(fmt.Errorf("not implemented: ActiveShipPass - activeShipPass"))
}

// ShipPasses is the resolver for the shipPasses field.
func (r *queryResolver) ShipPasses(ctx context.Context, limit *int) ([]model.ShipPass, error) {
	panic(fmt.Errorf("not implemented: ShipPasses - shipPasses"))
}

// ShipPassProgress is the resolver for the shipPassProgress field.
func (r *queryResolver) ShipPassProgress(ctx context.Context, passID string) ([]model.ShipPassGateProgress, error) {
	panic(fmt.Errorf("not implemented: ShipPassProgress - shipPassProgress"))
}

// ShipPassStats is the resolver for the shipPassStats field.
func (r *queryResolver) ShipPassStats(ctx context.Context) (*model.ShipPassLifetimeStats, error) {
	panic(fmt.Errorf("not implemented: ShipPassStats - shipPassStats"))
}
