package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"ironflyer/core/orchestrator/internal/business/wallet"
	"ironflyer/core/orchestrator/internal/operations/graph/model"

	"github.com/shopspring/decimal"
)

// WalletCreateTopUp is the resolver for the walletCreateTopUp field.
//
// Provisions a one-shot hosted checkout for the supplied amount + provider,
// stages a pending wallet_topups row, and returns the URL the browser should
// open. The webhook later flips the row to succeeded and credits the wallet.
// provider is optional — when null we use the configured primary so existing
// clients (pre-multi-provider) keep working without a schema bump.
func (r *mutationResolver) WalletCreateTopUp(ctx context.Context, amountUsd float64, provider *string) (*model.WalletCheckoutSession, error) {
	if r.WalletToppers == nil || !r.WalletToppers.Enabled() {
		return nil, gqlNotConfigured("wallet_topper")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	tenant := tenantFor(u)
	amount := decimal.NewFromFloat(amountUsd)
	var name string
	if provider != nil {
		name = *provider
	}
	topper, err := r.WalletToppers.ByName(name)
	if err != nil {
		if errors.Is(err, wallet.ErrTopperDisabled) {
			return nil, gqlNotConfigured("wallet_topper")
		}
		return nil, err
	}
	sess, err := topper.CreateCheckoutSession(ctx, tenant, amount)
	if err != nil {
		return nil, err
	}
	return &model.WalletCheckoutSession{
		URL:       sess.URL,
		SessionID: sess.SessionID,
		Provider:  sess.Provider,
	}, nil
}

// Wallet is the resolver for the wallet field.
func (r *queryResolver) Wallet(ctx context.Context) (*model.Wallet, error) {
	if r.WalletSvc == nil {
		return nil, gqlNotConfigured("wallet")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	tenant := tenantFor(u)
	w, err := r.WalletSvc.Get(ctx, tenant)
	if err != nil {
		return nil, err
	}
	return &model.Wallet{
		TenantID:         w.TenantID,
		BalanceUsd:       floatOfDecimal(w.BalanceUSD),
		HoldUsd:          floatOfDecimal(w.HoldUSD),
		AvailableUsd:     floatOfDecimal(w.AvailableUSD()),
		LifetimeTopUpUsd: floatOfDecimal(w.LifetimeTopUpUSD),
		LifetimeSpendUsd: floatOfDecimal(w.LifetimeSpendUSD),
		UpdatedAt:        w.UpdatedAt,
	}, nil
}

// WalletTopUps is the resolver for the walletTopUps field.
func (r *queryResolver) WalletTopUps(ctx context.Context, limit *int) ([]model.WalletTopUp, error) {
	if r.WalletSvc == nil {
		return nil, gqlNotConfigured("wallet")
	}
	u, err := currentUser(ctx)
	if err != nil {
		return nil, err
	}
	lim := 50
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	rows, err := r.WalletSvc.ListTopUps(ctx, tenantFor(u), lim)
	if err != nil {
		return nil, err
	}
	out := make([]model.WalletTopUp, 0, len(rows))
	for _, t := range rows {
		prov := t.Provider
		if prov == "" {
			// Legacy rows pre-migration default to stripe — the
			// migration backfills the column but the in-memory
			// backend may still emit blank strings in dev.
			prov = wallet.ProviderStripe
		}
		out = append(out, model.WalletTopUp{
			ID:          t.ID,
			Provider:    prov,
			AmountUsd:   floatOfDecimal(t.AmountUSD),
			Status:      t.Status,
			CreatedAt:   t.CreatedAt,
			CompletedAt: t.CompletedAt,
		})
	}
	return out, nil
}

// WalletAvailableProviders is the resolver for the walletAvailableProviders
// field. Returns the enabled set of payment providers, primary first, so the
// /wallet/topup page can render the right CTA + alternative-checkout links.
// Empty list when nothing is configured (dev boots).
func (r *queryResolver) WalletAvailableProviders(ctx context.Context) ([]model.WalletProvider, error) {
	if r.WalletToppers == nil {
		return []model.WalletProvider{}, nil
	}
	active := r.WalletToppers.Active()
	out := make([]model.WalletProvider, 0, len(active))
	primary := r.WalletToppers.Primary()
	var primaryName string
	if primary != nil {
		primaryName = primary.Name()
	}
	for _, t := range active {
		out = append(out, model.WalletProvider{
			Name:      t.Name(),
			Label:     t.Label(),
			IsPrimary: t.Name() == primaryName,
		})
	}
	return out, nil
}
