package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ironflyer/core/orchestrator/internal/operations/graph/model"
)

// ExecutionSupportBundle is the resolver for the executionSupportBundle
// field.
func (r *queryResolver) ExecutionSupportBundle(ctx context.Context, executionID string) (*model.SupportBundle, error) {
	if r.WowLoopBuilder == nil {
		return nil, gqlNotConfigured("wowloop")
	}
	if _, err := currentUser(ctx); err != nil {
		return nil, err
	}

	bundle, err := r.WowLoopBuilder.Build(ctx, executionID)
	if err != nil {
		return nil, err
	}

	stages := make([]model.GateStage, 0, len(bundle.GateReport.Stages))
	for _, s := range bundle.GateReport.Stages {
		stages = append(stages, model.GateStage{
			Name:        s.Name,
			Status:      s.Status,
			IssuesCount: s.IssuesCount,
		})
	}

	findings := make([]model.SupportSecurityFinding, 0, len(bundle.SecurityReport.Findings))
	for _, f := range bundle.SecurityReport.Findings {
		findings = append(findings, model.SupportSecurityFinding{
			Severity: f.Severity,
			RuleID:   f.RuleID,
			Path:     f.Path,
			Line:     f.Line,
			Summary:  f.Summary,
		})
	}

	out := &model.SupportBundle{
		ExecutionID:  bundle.ExecutionID,
		TenantID:     bundle.TenantID,
		Status:       bundle.Status,
		ChangedFiles: append([]string(nil), bundle.ChangedFiles...),
		PatchCount:   bundle.PatchCount,
		GateReport: model.GateReport{
			Stages:          stages,
			CompletionScore: bundle.GateReport.CompletionScore,
		},
		SecurityReport: model.SupportSecurityReport{
			Findings:      findings,
			PassRate:      bundle.SecurityReport.PassRate,
			BlockedDeploy: bundle.SecurityReport.BlockedDeploy,
		},
		CostReport: model.CostReport{
			RevenueUsd:        floatOfDecimal(bundle.CostReport.RevenueUSD),
			ProviderCostUsd:   floatOfDecimal(bundle.CostReport.ProviderCostUSD),
			SandboxCostUsd:    floatOfDecimal(bundle.CostReport.SandboxCostUSD),
			StorageCostUsd:    floatOfDecimal(bundle.CostReport.StorageCostUSD),
			DeploymentCostUsd: floatOfDecimal(bundle.CostReport.DeploymentCostUSD),
			GrossMarginPct:    floatOfDecimal(bundle.CostReport.GrossMarginPct),
		},
		NextBestAction: model.NextAction{
			Kind:   bundle.NextBestAction.Kind,
			Title:  bundle.NextBestAction.Title,
			Reason: bundle.NextBestAction.Reason,
		},
		GeneratedAt: bundle.GeneratedAt,
	}
	if bundle.PreviewURL != "" {
		u := bundle.PreviewURL
		out.PreviewURL = &u
	}
	if bundle.ProductionURL != "" {
		u := bundle.ProductionURL
		out.ProductionURL = &u
	}
	if bundle.NextBestAction.CTA != "" {
		c := bundle.NextBestAction.CTA
		out.NextBestAction.Cta = &c
	}
	return out, nil
}
