// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package gql

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/Khan/genqlient/graphql"
	"github.com/shopspring/decimal"
)

// AddMemoryAddMemoryMemoryRecord includes the requested fields of the GraphQL type MemoryRecord.
type AddMemoryAddMemoryMemoryRecord struct {
	Id        string     `json:"id"`
	Kind      MemoryKind `json:"kind"`
	UserId    string     `json:"userId"`
	ProjectId string     `json:"projectId"`
	GateName  string     `json:"gateName"`
	Title     string     `json:"title"`
	Body      string     `json:"body"`
	Tags      []string   `json:"tags"`
	CreatedAt time.Time  `json:"createdAt"`
}

// GetId returns AddMemoryAddMemoryMemoryRecord.Id, and is useful for accessing the field via an interface.
func (v *AddMemoryAddMemoryMemoryRecord) GetId() string { return v.Id }

// GetKind returns AddMemoryAddMemoryMemoryRecord.Kind, and is useful for accessing the field via an interface.
func (v *AddMemoryAddMemoryMemoryRecord) GetKind() MemoryKind { return v.Kind }

// GetUserId returns AddMemoryAddMemoryMemoryRecord.UserId, and is useful for accessing the field via an interface.
func (v *AddMemoryAddMemoryMemoryRecord) GetUserId() string { return v.UserId }

// GetProjectId returns AddMemoryAddMemoryMemoryRecord.ProjectId, and is useful for accessing the field via an interface.
func (v *AddMemoryAddMemoryMemoryRecord) GetProjectId() string { return v.ProjectId }

// GetGateName returns AddMemoryAddMemoryMemoryRecord.GateName, and is useful for accessing the field via an interface.
func (v *AddMemoryAddMemoryMemoryRecord) GetGateName() string { return v.GateName }

// GetTitle returns AddMemoryAddMemoryMemoryRecord.Title, and is useful for accessing the field via an interface.
func (v *AddMemoryAddMemoryMemoryRecord) GetTitle() string { return v.Title }

// GetBody returns AddMemoryAddMemoryMemoryRecord.Body, and is useful for accessing the field via an interface.
func (v *AddMemoryAddMemoryMemoryRecord) GetBody() string { return v.Body }

// GetTags returns AddMemoryAddMemoryMemoryRecord.Tags, and is useful for accessing the field via an interface.
func (v *AddMemoryAddMemoryMemoryRecord) GetTags() []string { return v.Tags }

// GetCreatedAt returns AddMemoryAddMemoryMemoryRecord.CreatedAt, and is useful for accessing the field via an interface.
func (v *AddMemoryAddMemoryMemoryRecord) GetCreatedAt() time.Time { return v.CreatedAt }

type AddMemoryInput struct {
	Kind      MemoryKind `json:"kind"`
	ProjectId string     `json:"projectId"`
	StoryId   string     `json:"storyId"`
	GateName  string     `json:"gateName"`
	Title     string     `json:"title"`
	Body      string     `json:"body"`
	Tags      []string   `json:"tags"`
}

// GetKind returns AddMemoryInput.Kind, and is useful for accessing the field via an interface.
func (v *AddMemoryInput) GetKind() MemoryKind { return v.Kind }

// GetProjectId returns AddMemoryInput.ProjectId, and is useful for accessing the field via an interface.
func (v *AddMemoryInput) GetProjectId() string { return v.ProjectId }

// GetStoryId returns AddMemoryInput.StoryId, and is useful for accessing the field via an interface.
func (v *AddMemoryInput) GetStoryId() string { return v.StoryId }

// GetGateName returns AddMemoryInput.GateName, and is useful for accessing the field via an interface.
func (v *AddMemoryInput) GetGateName() string { return v.GateName }

// GetTitle returns AddMemoryInput.Title, and is useful for accessing the field via an interface.
func (v *AddMemoryInput) GetTitle() string { return v.Title }

// GetBody returns AddMemoryInput.Body, and is useful for accessing the field via an interface.
func (v *AddMemoryInput) GetBody() string { return v.Body }

// GetTags returns AddMemoryInput.Tags, and is useful for accessing the field via an interface.
func (v *AddMemoryInput) GetTags() []string { return v.Tags }

// AddMemoryResponse is returned by AddMemory on success.
type AddMemoryResponse struct {
	AddMemory AddMemoryAddMemoryMemoryRecord `json:"addMemory"`
}

// GetAddMemory returns AddMemoryResponse.AddMemory, and is useful for accessing the field via an interface.
func (v *AddMemoryResponse) GetAddMemory() AddMemoryAddMemoryMemoryRecord { return v.AddMemory }

// AgentTelemetryAgentTelemetryAgentCall includes the requested fields of the GraphQL type AgentCall.
type AgentTelemetryAgentTelemetryAgentCall struct {
	Id               string          `json:"id"`
	Ts               time.Time       `json:"ts"`
	Role             string          `json:"role"`
	Provider         string          `json:"provider"`
	Model            string          `json:"model"`
	PromptTokens     int             `json:"promptTokens"`
	CompletionTokens int             `json:"completionTokens"`
	CostUsd          decimal.Decimal `json:"costUsd"`
	DurationMs       int             `json:"durationMs"`
	Error            string          `json:"error"`
}

// GetId returns AgentTelemetryAgentTelemetryAgentCall.Id, and is useful for accessing the field via an interface.
func (v *AgentTelemetryAgentTelemetryAgentCall) GetId() string { return v.Id }

// GetTs returns AgentTelemetryAgentTelemetryAgentCall.Ts, and is useful for accessing the field via an interface.
func (v *AgentTelemetryAgentTelemetryAgentCall) GetTs() time.Time { return v.Ts }

// GetRole returns AgentTelemetryAgentTelemetryAgentCall.Role, and is useful for accessing the field via an interface.
func (v *AgentTelemetryAgentTelemetryAgentCall) GetRole() string { return v.Role }

// GetProvider returns AgentTelemetryAgentTelemetryAgentCall.Provider, and is useful for accessing the field via an interface.
func (v *AgentTelemetryAgentTelemetryAgentCall) GetProvider() string { return v.Provider }

// GetModel returns AgentTelemetryAgentTelemetryAgentCall.Model, and is useful for accessing the field via an interface.
func (v *AgentTelemetryAgentTelemetryAgentCall) GetModel() string { return v.Model }

// GetPromptTokens returns AgentTelemetryAgentTelemetryAgentCall.PromptTokens, and is useful for accessing the field via an interface.
func (v *AgentTelemetryAgentTelemetryAgentCall) GetPromptTokens() int { return v.PromptTokens }

// GetCompletionTokens returns AgentTelemetryAgentTelemetryAgentCall.CompletionTokens, and is useful for accessing the field via an interface.
func (v *AgentTelemetryAgentTelemetryAgentCall) GetCompletionTokens() int { return v.CompletionTokens }

// GetCostUsd returns AgentTelemetryAgentTelemetryAgentCall.CostUsd, and is useful for accessing the field via an interface.
func (v *AgentTelemetryAgentTelemetryAgentCall) GetCostUsd() decimal.Decimal { return v.CostUsd }

// GetDurationMs returns AgentTelemetryAgentTelemetryAgentCall.DurationMs, and is useful for accessing the field via an interface.
func (v *AgentTelemetryAgentTelemetryAgentCall) GetDurationMs() int { return v.DurationMs }

// GetError returns AgentTelemetryAgentTelemetryAgentCall.Error, and is useful for accessing the field via an interface.
func (v *AgentTelemetryAgentTelemetryAgentCall) GetError() string { return v.Error }

// AgentTelemetryResponse is returned by AgentTelemetry on success.
type AgentTelemetryResponse struct {
	AgentTelemetry []AgentTelemetryAgentTelemetryAgentCall `json:"agentTelemetry"`
}

// GetAgentTelemetry returns AgentTelemetryResponse.AgentTelemetry, and is useful for accessing the field via an interface.
func (v *AgentTelemetryResponse) GetAgentTelemetry() []AgentTelemetryAgentTelemetryAgentCall {
	return v.AgentTelemetry
}

// ApplyPatchApplyPatch includes the requested fields of the GraphQL type Patch.
type ApplyPatchApplyPatch struct {
	Id        string      `json:"id"`
	Status    PatchStatus `json:"status"`
	AppliedAt time.Time   `json:"appliedAt"`
}

// GetId returns ApplyPatchApplyPatch.Id, and is useful for accessing the field via an interface.
func (v *ApplyPatchApplyPatch) GetId() string { return v.Id }

// GetStatus returns ApplyPatchApplyPatch.Status, and is useful for accessing the field via an interface.
func (v *ApplyPatchApplyPatch) GetStatus() PatchStatus { return v.Status }

// GetAppliedAt returns ApplyPatchApplyPatch.AppliedAt, and is useful for accessing the field via an interface.
func (v *ApplyPatchApplyPatch) GetAppliedAt() time.Time { return v.AppliedAt }

// ApplyPatchResponse is returned by ApplyPatch on success.
type ApplyPatchResponse struct {
	ApplyPatch ApplyPatchApplyPatch `json:"applyPatch"`
}

// GetApplyPatch returns ApplyPatchResponse.ApplyPatch, and is useful for accessing the field via an interface.
func (v *ApplyPatchResponse) GetApplyPatch() ApplyPatchApplyPatch { return v.ApplyPatch }

type AuditOutcome string

const (
	AuditOutcomeSuccess AuditOutcome = "SUCCESS"
	AuditOutcomeFailure AuditOutcome = "FAILURE"
	AuditOutcomeBlocked AuditOutcome = "BLOCKED"
	AuditOutcomeSkipped AuditOutcome = "SKIPPED"
)

var AllAuditOutcome = []AuditOutcome{
	AuditOutcomeSuccess,
	AuditOutcomeFailure,
	AuditOutcomeBlocked,
	AuditOutcomeSkipped,
}

type AuditQueryInput struct {
	UserId    string       `json:"userId"`
	ProjectId string       `json:"projectId"`
	Action    string       `json:"action"`
	Outcome   AuditOutcome `json:"outcome"`
	Since     time.Time    `json:"since"`
	Until     time.Time    `json:"until"`
	Limit     int          `json:"limit"`
}

// GetUserId returns AuditQueryInput.UserId, and is useful for accessing the field via an interface.
func (v *AuditQueryInput) GetUserId() string { return v.UserId }

// GetProjectId returns AuditQueryInput.ProjectId, and is useful for accessing the field via an interface.
func (v *AuditQueryInput) GetProjectId() string { return v.ProjectId }

// GetAction returns AuditQueryInput.Action, and is useful for accessing the field via an interface.
func (v *AuditQueryInput) GetAction() string { return v.Action }

// GetOutcome returns AuditQueryInput.Outcome, and is useful for accessing the field via an interface.
func (v *AuditQueryInput) GetOutcome() AuditOutcome { return v.Outcome }

// GetSince returns AuditQueryInput.Since, and is useful for accessing the field via an interface.
func (v *AuditQueryInput) GetSince() time.Time { return v.Since }

// GetUntil returns AuditQueryInput.Until, and is useful for accessing the field via an interface.
func (v *AuditQueryInput) GetUntil() time.Time { return v.Until }

// GetLimit returns AuditQueryInput.Limit, and is useful for accessing the field via an interface.
func (v *AuditQueryInput) GetLimit() int { return v.Limit }

// BulkDeleteProjectsBulkDeleteProjectsOperationResult includes the requested fields of the GraphQL type OperationResult.
type BulkDeleteProjectsBulkDeleteProjectsOperationResult struct {
	Ok      bool   `json:"ok"`
	Message string `json:"message"`
}

// GetOk returns BulkDeleteProjectsBulkDeleteProjectsOperationResult.Ok, and is useful for accessing the field via an interface.
func (v *BulkDeleteProjectsBulkDeleteProjectsOperationResult) GetOk() bool { return v.Ok }

// GetMessage returns BulkDeleteProjectsBulkDeleteProjectsOperationResult.Message, and is useful for accessing the field via an interface.
func (v *BulkDeleteProjectsBulkDeleteProjectsOperationResult) GetMessage() string { return v.Message }

// BulkDeleteProjectsResponse is returned by BulkDeleteProjects on success.
type BulkDeleteProjectsResponse struct {
	BulkDeleteProjects BulkDeleteProjectsBulkDeleteProjectsOperationResult `json:"bulkDeleteProjects"`
}

// GetBulkDeleteProjects returns BulkDeleteProjectsResponse.BulkDeleteProjects, and is useful for accessing the field via an interface.
func (v *BulkDeleteProjectsResponse) GetBulkDeleteProjects() BulkDeleteProjectsBulkDeleteProjectsOperationResult {
	return v.BulkDeleteProjects
}

// CreateProjectCreateProject includes the requested fields of the GraphQL type Project.
type CreateProjectCreateProject struct {
	Id          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"createdAt"`
}

// GetId returns CreateProjectCreateProject.Id, and is useful for accessing the field via an interface.
func (v *CreateProjectCreateProject) GetId() string { return v.Id }

// GetName returns CreateProjectCreateProject.Name, and is useful for accessing the field via an interface.
func (v *CreateProjectCreateProject) GetName() string { return v.Name }

// GetDescription returns CreateProjectCreateProject.Description, and is useful for accessing the field via an interface.
func (v *CreateProjectCreateProject) GetDescription() string { return v.Description }

// GetStatus returns CreateProjectCreateProject.Status, and is useful for accessing the field via an interface.
func (v *CreateProjectCreateProject) GetStatus() string { return v.Status }

// GetCreatedAt returns CreateProjectCreateProject.CreatedAt, and is useful for accessing the field via an interface.
func (v *CreateProjectCreateProject) GetCreatedAt() time.Time { return v.CreatedAt }

// CreateProjectResponse is returned by CreateProject on success.
type CreateProjectResponse struct {
	CreateProject CreateProjectCreateProject `json:"createProject"`
}

// GetCreateProject returns CreateProjectResponse.CreateProject, and is useful for accessing the field via an interface.
func (v *CreateProjectResponse) GetCreateProject() CreateProjectCreateProject { return v.CreateProject }

// DeleteMemoryDeleteMemoryOperationResult includes the requested fields of the GraphQL type OperationResult.
type DeleteMemoryDeleteMemoryOperationResult struct {
	Ok      bool   `json:"ok"`
	Message string `json:"message"`
}

// GetOk returns DeleteMemoryDeleteMemoryOperationResult.Ok, and is useful for accessing the field via an interface.
func (v *DeleteMemoryDeleteMemoryOperationResult) GetOk() bool { return v.Ok }

// GetMessage returns DeleteMemoryDeleteMemoryOperationResult.Message, and is useful for accessing the field via an interface.
func (v *DeleteMemoryDeleteMemoryOperationResult) GetMessage() string { return v.Message }

// DeleteMemoryResponse is returned by DeleteMemory on success.
type DeleteMemoryResponse struct {
	DeleteMemory DeleteMemoryDeleteMemoryOperationResult `json:"deleteMemory"`
}

// GetDeleteMemory returns DeleteMemoryResponse.DeleteMemory, and is useful for accessing the field via an interface.
func (v *DeleteMemoryResponse) GetDeleteMemory() DeleteMemoryDeleteMemoryOperationResult {
	return v.DeleteMemory
}

type DeployStatus string

const (
	DeployStatusPending   DeployStatus = "PENDING"
	DeployStatusPlanning  DeployStatus = "PLANNING"
	DeployStatusBuilding  DeployStatus = "BUILDING"
	DeployStatusTesting   DeployStatus = "TESTING"
	DeployStatusShipping  DeployStatus = "SHIPPING"
	DeployStatusSuccess   DeployStatus = "SUCCESS"
	DeployStatusFailed    DeployStatus = "FAILED"
	DeployStatusCancelled DeployStatus = "CANCELLED"
)

var AllDeployStatus = []DeployStatus{
	DeployStatusPending,
	DeployStatusPlanning,
	DeployStatusBuilding,
	DeployStatusTesting,
	DeployStatusShipping,
	DeployStatusSuccess,
	DeployStatusFailed,
	DeployStatusCancelled,
}

// DeployStreamDeployStreamDeployErrorEvent includes the requested fields of the GraphQL type DeployErrorEvent.
type DeployStreamDeployStreamDeployErrorEvent struct {
	Typename string `json:"__typename"`
	DeployId string `json:"deployId"`
	Code     string `json:"code"`
	Message  string `json:"message"`
}

// GetTypename returns DeployStreamDeployStreamDeployErrorEvent.Typename, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployErrorEvent) GetTypename() string { return v.Typename }

// GetDeployId returns DeployStreamDeployStreamDeployErrorEvent.DeployId, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployErrorEvent) GetDeployId() string { return v.DeployId }

// GetCode returns DeployStreamDeployStreamDeployErrorEvent.Code, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployErrorEvent) GetCode() string { return v.Code }

// GetMessage returns DeployStreamDeployStreamDeployErrorEvent.Message, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployErrorEvent) GetMessage() string { return v.Message }

// DeployStreamDeployStreamDeployEvent includes the requested fields of the GraphQL interface DeployEvent.
//
// DeployStreamDeployStreamDeployEvent is implemented by the following types:
// DeployStreamDeployStreamDeployErrorEvent
// DeployStreamDeployStreamDeployFinishedEvent
// DeployStreamDeployStreamDeployLogEvent
// DeployStreamDeployStreamDeployStateEvent
type DeployStreamDeployStreamDeployEvent interface {
	implementsGraphQLInterfaceDeployStreamDeployStreamDeployEvent()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *DeployStreamDeployStreamDeployErrorEvent) implementsGraphQLInterfaceDeployStreamDeployStreamDeployEvent() {
}
func (v *DeployStreamDeployStreamDeployFinishedEvent) implementsGraphQLInterfaceDeployStreamDeployStreamDeployEvent() {
}
func (v *DeployStreamDeployStreamDeployLogEvent) implementsGraphQLInterfaceDeployStreamDeployStreamDeployEvent() {
}
func (v *DeployStreamDeployStreamDeployStateEvent) implementsGraphQLInterfaceDeployStreamDeployStreamDeployEvent() {
}

func __unmarshalDeployStreamDeployStreamDeployEvent(b []byte, v *DeployStreamDeployStreamDeployEvent) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "DeployErrorEvent":
		*v = new(DeployStreamDeployStreamDeployErrorEvent)
		return json.Unmarshal(b, *v)
	case "DeployFinishedEvent":
		*v = new(DeployStreamDeployStreamDeployFinishedEvent)
		return json.Unmarshal(b, *v)
	case "DeployLogEvent":
		*v = new(DeployStreamDeployStreamDeployLogEvent)
		return json.Unmarshal(b, *v)
	case "DeployStateEvent":
		*v = new(DeployStreamDeployStreamDeployStateEvent)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing DeployEvent.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for DeployStreamDeployStreamDeployEvent: "%v"`, tn.TypeName)
	}
}

func __marshalDeployStreamDeployStreamDeployEvent(v *DeployStreamDeployStreamDeployEvent) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *DeployStreamDeployStreamDeployErrorEvent:
		typename = "DeployErrorEvent"

		result := struct {
			TypeName string `json:"__typename"`
			*DeployStreamDeployStreamDeployErrorEvent
		}{typename, v}
		return json.Marshal(result)
	case *DeployStreamDeployStreamDeployFinishedEvent:
		typename = "DeployFinishedEvent"

		result := struct {
			TypeName string `json:"__typename"`
			*DeployStreamDeployStreamDeployFinishedEvent
		}{typename, v}
		return json.Marshal(result)
	case *DeployStreamDeployStreamDeployLogEvent:
		typename = "DeployLogEvent"

		result := struct {
			TypeName string `json:"__typename"`
			*DeployStreamDeployStreamDeployLogEvent
		}{typename, v}
		return json.Marshal(result)
	case *DeployStreamDeployStreamDeployStateEvent:
		typename = "DeployStateEvent"

		result := struct {
			TypeName string `json:"__typename"`
			*DeployStreamDeployStreamDeployStateEvent
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for DeployStreamDeployStreamDeployEvent: "%T"`, v)
	}
}

// DeployStreamDeployStreamDeployFinishedEvent includes the requested fields of the GraphQL type DeployFinishedEvent.
type DeployStreamDeployStreamDeployFinishedEvent struct {
	Typename   string       `json:"__typename"`
	DeployId   string       `json:"deployId"`
	Status     DeployStatus `json:"status"`
	Url        string       `json:"url"`
	DurationMs int          `json:"durationMs"`
}

// GetTypename returns DeployStreamDeployStreamDeployFinishedEvent.Typename, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployFinishedEvent) GetTypename() string { return v.Typename }

// GetDeployId returns DeployStreamDeployStreamDeployFinishedEvent.DeployId, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployFinishedEvent) GetDeployId() string { return v.DeployId }

// GetStatus returns DeployStreamDeployStreamDeployFinishedEvent.Status, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployFinishedEvent) GetStatus() DeployStatus { return v.Status }

// GetUrl returns DeployStreamDeployStreamDeployFinishedEvent.Url, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployFinishedEvent) GetUrl() string { return v.Url }

// GetDurationMs returns DeployStreamDeployStreamDeployFinishedEvent.DurationMs, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployFinishedEvent) GetDurationMs() int { return v.DurationMs }

// DeployStreamDeployStreamDeployLogEvent includes the requested fields of the GraphQL type DeployLogEvent.
type DeployStreamDeployStreamDeployLogEvent struct {
	Typename string                                                  `json:"__typename"`
	DeployId string                                                  `json:"deployId"`
	Line     DeployStreamDeployStreamDeployLogEventLineDeployLogLine `json:"line"`
}

// GetTypename returns DeployStreamDeployStreamDeployLogEvent.Typename, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployLogEvent) GetTypename() string { return v.Typename }

// GetDeployId returns DeployStreamDeployStreamDeployLogEvent.DeployId, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployLogEvent) GetDeployId() string { return v.DeployId }

// GetLine returns DeployStreamDeployStreamDeployLogEvent.Line, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployLogEvent) GetLine() DeployStreamDeployStreamDeployLogEventLineDeployLogLine {
	return v.Line
}

// DeployStreamDeployStreamDeployLogEventLineDeployLogLine includes the requested fields of the GraphQL type DeployLogLine.
type DeployStreamDeployStreamDeployLogEventLineDeployLogLine struct {
	Ts      time.Time `json:"ts"`
	Level   string    `json:"level"`
	Message string    `json:"message"`
}

// GetTs returns DeployStreamDeployStreamDeployLogEventLineDeployLogLine.Ts, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployLogEventLineDeployLogLine) GetTs() time.Time { return v.Ts }

// GetLevel returns DeployStreamDeployStreamDeployLogEventLineDeployLogLine.Level, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployLogEventLineDeployLogLine) GetLevel() string { return v.Level }

// GetMessage returns DeployStreamDeployStreamDeployLogEventLineDeployLogLine.Message, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployLogEventLineDeployLogLine) GetMessage() string {
	return v.Message
}

// DeployStreamDeployStreamDeployStateEvent includes the requested fields of the GraphQL type DeployStateEvent.
type DeployStreamDeployStreamDeployStateEvent struct {
	Typename string       `json:"__typename"`
	DeployId string       `json:"deployId"`
	Status   DeployStatus `json:"status"`
	Ts       time.Time    `json:"ts"`
}

// GetTypename returns DeployStreamDeployStreamDeployStateEvent.Typename, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployStateEvent) GetTypename() string { return v.Typename }

// GetDeployId returns DeployStreamDeployStreamDeployStateEvent.DeployId, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployStateEvent) GetDeployId() string { return v.DeployId }

// GetStatus returns DeployStreamDeployStreamDeployStateEvent.Status, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployStateEvent) GetStatus() DeployStatus { return v.Status }

// GetTs returns DeployStreamDeployStreamDeployStateEvent.Ts, and is useful for accessing the field via an interface.
func (v *DeployStreamDeployStreamDeployStateEvent) GetTs() time.Time { return v.Ts }

// DeployStreamResponse is returned by DeployStream on success.
type DeployStreamResponse struct {
	DeployStream DeployStreamDeployStreamDeployEvent `json:"-"`
}

// GetDeployStream returns DeployStreamResponse.DeployStream, and is useful for accessing the field via an interface.
func (v *DeployStreamResponse) GetDeployStream() DeployStreamDeployStreamDeployEvent {
	return v.DeployStream
}

func (v *DeployStreamResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*DeployStreamResponse
		DeployStream json.RawMessage `json:"deployStream"`
		graphql.NoUnmarshalJSON
	}
	firstPass.DeployStreamResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.DeployStream
		src := firstPass.DeployStream
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalDeployStreamDeployStreamDeployEvent(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal DeployStreamResponse.DeployStream: %w", err)
			}
		}
	}
	return nil
}

type __premarshalDeployStreamResponse struct {
	DeployStream json.RawMessage `json:"deployStream"`
}

func (v *DeployStreamResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *DeployStreamResponse) __premarshalJSON() (*__premarshalDeployStreamResponse, error) {
	var retval __premarshalDeployStreamResponse

	{

		dst := &retval.DeployStream
		src := v.DeployStream
		var err error
		*dst, err = __marshalDeployStreamDeployStreamDeployEvent(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal DeployStreamResponse.DeployStream: %w", err)
		}
	}
	return &retval, nil
}

// ExportGithubExportGithubOperationResult includes the requested fields of the GraphQL type OperationResult.
type ExportGithubExportGithubOperationResult struct {
	Ok      bool   `json:"ok"`
	Message string `json:"message"`
}

// GetOk returns ExportGithubExportGithubOperationResult.Ok, and is useful for accessing the field via an interface.
func (v *ExportGithubExportGithubOperationResult) GetOk() bool { return v.Ok }

// GetMessage returns ExportGithubExportGithubOperationResult.Message, and is useful for accessing the field via an interface.
func (v *ExportGithubExportGithubOperationResult) GetMessage() string { return v.Message }

// ExportGithubResponse is returned by ExportGithub on success.
type ExportGithubResponse struct {
	ExportGithub ExportGithubExportGithubOperationResult `json:"exportGithub"`
}

// GetExportGithub returns ExportGithubResponse.ExportGithub, and is useful for accessing the field via an interface.
func (v *ExportGithubResponse) GetExportGithub() ExportGithubExportGithubOperationResult {
	return v.ExportGithub
}

// ExportZipUrlResponse is returned by ExportZipUrl on success.
type ExportZipUrlResponse struct {
	ExportZipUrl string `json:"exportZipUrl"`
}

// GetExportZipUrl returns ExportZipUrlResponse.ExportZipUrl, and is useful for accessing the field via an interface.
func (v *ExportZipUrlResponse) GetExportZipUrl() string { return v.ExportZipUrl }

// GetProjectGraphProjectGraph includes the requested fields of the GraphQL type ProjectGraph.
type GetProjectGraphProjectGraph struct {
	Nodes []GetProjectGraphProjectGraphNodesProjectGraphNode `json:"nodes"`
	Edges []GetProjectGraphProjectGraphEdgesProjectGraphEdge `json:"edges"`
}

// GetNodes returns GetProjectGraphProjectGraph.Nodes, and is useful for accessing the field via an interface.
func (v *GetProjectGraphProjectGraph) GetNodes() []GetProjectGraphProjectGraphNodesProjectGraphNode {
	return v.Nodes
}

// GetEdges returns GetProjectGraphProjectGraph.Edges, and is useful for accessing the field via an interface.
func (v *GetProjectGraphProjectGraph) GetEdges() []GetProjectGraphProjectGraphEdgesProjectGraphEdge {
	return v.Edges
}

// GetProjectGraphProjectGraphEdgesProjectGraphEdge includes the requested fields of the GraphQL type ProjectGraphEdge.
type GetProjectGraphProjectGraphEdgesProjectGraphEdge struct {
	From string `json:"from"`
	To   string `json:"to"`
	Kind string `json:"kind"`
}

// GetFrom returns GetProjectGraphProjectGraphEdgesProjectGraphEdge.From, and is useful for accessing the field via an interface.
func (v *GetProjectGraphProjectGraphEdgesProjectGraphEdge) GetFrom() string { return v.From }

// GetTo returns GetProjectGraphProjectGraphEdgesProjectGraphEdge.To, and is useful for accessing the field via an interface.
func (v *GetProjectGraphProjectGraphEdgesProjectGraphEdge) GetTo() string { return v.To }

// GetKind returns GetProjectGraphProjectGraphEdgesProjectGraphEdge.Kind, and is useful for accessing the field via an interface.
func (v *GetProjectGraphProjectGraphEdgesProjectGraphEdge) GetKind() string { return v.Kind }

// GetProjectGraphProjectGraphNodesProjectGraphNode includes the requested fields of the GraphQL type ProjectGraphNode.
type GetProjectGraphProjectGraphNodesProjectGraphNode struct {
	Id       string `json:"id"`
	Path     string `json:"path"`
	Language string `json:"language"`
	Size     int    `json:"size"`
}

// GetId returns GetProjectGraphProjectGraphNodesProjectGraphNode.Id, and is useful for accessing the field via an interface.
func (v *GetProjectGraphProjectGraphNodesProjectGraphNode) GetId() string { return v.Id }

// GetPath returns GetProjectGraphProjectGraphNodesProjectGraphNode.Path, and is useful for accessing the field via an interface.
func (v *GetProjectGraphProjectGraphNodesProjectGraphNode) GetPath() string { return v.Path }

// GetLanguage returns GetProjectGraphProjectGraphNodesProjectGraphNode.Language, and is useful for accessing the field via an interface.
func (v *GetProjectGraphProjectGraphNodesProjectGraphNode) GetLanguage() string { return v.Language }

// GetSize returns GetProjectGraphProjectGraphNodesProjectGraphNode.Size, and is useful for accessing the field via an interface.
func (v *GetProjectGraphProjectGraphNodesProjectGraphNode) GetSize() int { return v.Size }

// GetProjectGraphResponse is returned by GetProjectGraph on success.
type GetProjectGraphResponse struct {
	ProjectGraph GetProjectGraphProjectGraph `json:"projectGraph"`
}

// GetProjectGraph returns GetProjectGraphResponse.ProjectGraph, and is useful for accessing the field via an interface.
func (v *GetProjectGraphResponse) GetProjectGraph() GetProjectGraphProjectGraph {
	return v.ProjectGraph
}

// GetProjectProject includes the requested fields of the GraphQL type Project.
type GetProjectProject struct {
	Id          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	OwnerId     string    `json:"ownerId"`
	IsPublic    bool      `json:"isPublic"`
	Idea        string    `json:"idea"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// GetId returns GetProjectProject.Id, and is useful for accessing the field via an interface.
func (v *GetProjectProject) GetId() string { return v.Id }

// GetName returns GetProjectProject.Name, and is useful for accessing the field via an interface.
func (v *GetProjectProject) GetName() string { return v.Name }

// GetDescription returns GetProjectProject.Description, and is useful for accessing the field via an interface.
func (v *GetProjectProject) GetDescription() string { return v.Description }

// GetStatus returns GetProjectProject.Status, and is useful for accessing the field via an interface.
func (v *GetProjectProject) GetStatus() string { return v.Status }

// GetOwnerId returns GetProjectProject.OwnerId, and is useful for accessing the field via an interface.
func (v *GetProjectProject) GetOwnerId() string { return v.OwnerId }

// GetIsPublic returns GetProjectProject.IsPublic, and is useful for accessing the field via an interface.
func (v *GetProjectProject) GetIsPublic() bool { return v.IsPublic }

// GetIdea returns GetProjectProject.Idea, and is useful for accessing the field via an interface.
func (v *GetProjectProject) GetIdea() string { return v.Idea }

// GetCreatedAt returns GetProjectProject.CreatedAt, and is useful for accessing the field via an interface.
func (v *GetProjectProject) GetCreatedAt() time.Time { return v.CreatedAt }

// GetUpdatedAt returns GetProjectProject.UpdatedAt, and is useful for accessing the field via an interface.
func (v *GetProjectProject) GetUpdatedAt() time.Time { return v.UpdatedAt }

// GetProjectResponse is returned by GetProject on success.
type GetProjectResponse struct {
	Project GetProjectProject `json:"project"`
}

// GetProject returns GetProjectResponse.Project, and is useful for accessing the field via an interface.
func (v *GetProjectResponse) GetProject() GetProjectProject { return v.Project }

// ListAuditAuditAuditEntry includes the requested fields of the GraphQL type AuditEntry.
type ListAuditAuditAuditEntry struct {
	Id        string          `json:"id"`
	Ts        time.Time       `json:"ts"`
	UserId    string          `json:"userId"`
	ProjectId string          `json:"projectId"`
	Action    string          `json:"action"`
	Outcome   AuditOutcome    `json:"outcome"`
	Hash      string          `json:"hash"`
	PrevHash  string          `json:"prevHash"`
	Payload   json.RawMessage `json:"payload"`
}

// GetId returns ListAuditAuditAuditEntry.Id, and is useful for accessing the field via an interface.
func (v *ListAuditAuditAuditEntry) GetId() string { return v.Id }

// GetTs returns ListAuditAuditAuditEntry.Ts, and is useful for accessing the field via an interface.
func (v *ListAuditAuditAuditEntry) GetTs() time.Time { return v.Ts }

// GetUserId returns ListAuditAuditAuditEntry.UserId, and is useful for accessing the field via an interface.
func (v *ListAuditAuditAuditEntry) GetUserId() string { return v.UserId }

// GetProjectId returns ListAuditAuditAuditEntry.ProjectId, and is useful for accessing the field via an interface.
func (v *ListAuditAuditAuditEntry) GetProjectId() string { return v.ProjectId }

// GetAction returns ListAuditAuditAuditEntry.Action, and is useful for accessing the field via an interface.
func (v *ListAuditAuditAuditEntry) GetAction() string { return v.Action }

// GetOutcome returns ListAuditAuditAuditEntry.Outcome, and is useful for accessing the field via an interface.
func (v *ListAuditAuditAuditEntry) GetOutcome() AuditOutcome { return v.Outcome }

// GetHash returns ListAuditAuditAuditEntry.Hash, and is useful for accessing the field via an interface.
func (v *ListAuditAuditAuditEntry) GetHash() string { return v.Hash }

// GetPrevHash returns ListAuditAuditAuditEntry.PrevHash, and is useful for accessing the field via an interface.
func (v *ListAuditAuditAuditEntry) GetPrevHash() string { return v.PrevHash }

// GetPayload returns ListAuditAuditAuditEntry.Payload, and is useful for accessing the field via an interface.
func (v *ListAuditAuditAuditEntry) GetPayload() json.RawMessage { return v.Payload }

// ListAuditResponse is returned by ListAudit on success.
type ListAuditResponse struct {
	Audit []ListAuditAuditAuditEntry `json:"audit"`
}

// GetAudit returns ListAuditResponse.Audit, and is useful for accessing the field via an interface.
func (v *ListAuditResponse) GetAudit() []ListAuditAuditAuditEntry { return v.Audit }

// ListMemoryMemoryMemoryRecord includes the requested fields of the GraphQL type MemoryRecord.
type ListMemoryMemoryMemoryRecord struct {
	Id        string     `json:"id"`
	Kind      MemoryKind `json:"kind"`
	UserId    string     `json:"userId"`
	ProjectId string     `json:"projectId"`
	StoryId   string     `json:"storyId"`
	GateName  string     `json:"gateName"`
	Title     string     `json:"title"`
	Body      string     `json:"body"`
	Tags      []string   `json:"tags"`
	CreatedAt time.Time  `json:"createdAt"`
}

// GetId returns ListMemoryMemoryMemoryRecord.Id, and is useful for accessing the field via an interface.
func (v *ListMemoryMemoryMemoryRecord) GetId() string { return v.Id }

// GetKind returns ListMemoryMemoryMemoryRecord.Kind, and is useful for accessing the field via an interface.
func (v *ListMemoryMemoryMemoryRecord) GetKind() MemoryKind { return v.Kind }

// GetUserId returns ListMemoryMemoryMemoryRecord.UserId, and is useful for accessing the field via an interface.
func (v *ListMemoryMemoryMemoryRecord) GetUserId() string { return v.UserId }

// GetProjectId returns ListMemoryMemoryMemoryRecord.ProjectId, and is useful for accessing the field via an interface.
func (v *ListMemoryMemoryMemoryRecord) GetProjectId() string { return v.ProjectId }

// GetStoryId returns ListMemoryMemoryMemoryRecord.StoryId, and is useful for accessing the field via an interface.
func (v *ListMemoryMemoryMemoryRecord) GetStoryId() string { return v.StoryId }

// GetGateName returns ListMemoryMemoryMemoryRecord.GateName, and is useful for accessing the field via an interface.
func (v *ListMemoryMemoryMemoryRecord) GetGateName() string { return v.GateName }

// GetTitle returns ListMemoryMemoryMemoryRecord.Title, and is useful for accessing the field via an interface.
func (v *ListMemoryMemoryMemoryRecord) GetTitle() string { return v.Title }

// GetBody returns ListMemoryMemoryMemoryRecord.Body, and is useful for accessing the field via an interface.
func (v *ListMemoryMemoryMemoryRecord) GetBody() string { return v.Body }

// GetTags returns ListMemoryMemoryMemoryRecord.Tags, and is useful for accessing the field via an interface.
func (v *ListMemoryMemoryMemoryRecord) GetTags() []string { return v.Tags }

// GetCreatedAt returns ListMemoryMemoryMemoryRecord.CreatedAt, and is useful for accessing the field via an interface.
func (v *ListMemoryMemoryMemoryRecord) GetCreatedAt() time.Time { return v.CreatedAt }

// ListMemoryResponse is returned by ListMemory on success.
type ListMemoryResponse struct {
	Memory []ListMemoryMemoryMemoryRecord `json:"memory"`
}

// GetMemory returns ListMemoryResponse.Memory, and is useful for accessing the field via an interface.
func (v *ListMemoryResponse) GetMemory() []ListMemoryMemoryMemoryRecord { return v.Memory }

// ListPatchesPatchesPatch includes the requested fields of the GraphQL type Patch.
type ListPatchesPatchesPatch struct {
	Id        string      `json:"id"`
	ProjectId string      `json:"projectId"`
	Title     string      `json:"title"`
	Summary   string      `json:"summary"`
	Author    string      `json:"author"`
	Status    PatchStatus `json:"status"`
	CreatedAt time.Time   `json:"createdAt"`
	AppliedAt time.Time   `json:"appliedAt"`
}

// GetId returns ListPatchesPatchesPatch.Id, and is useful for accessing the field via an interface.
func (v *ListPatchesPatchesPatch) GetId() string { return v.Id }

// GetProjectId returns ListPatchesPatchesPatch.ProjectId, and is useful for accessing the field via an interface.
func (v *ListPatchesPatchesPatch) GetProjectId() string { return v.ProjectId }

// GetTitle returns ListPatchesPatchesPatch.Title, and is useful for accessing the field via an interface.
func (v *ListPatchesPatchesPatch) GetTitle() string { return v.Title }

// GetSummary returns ListPatchesPatchesPatch.Summary, and is useful for accessing the field via an interface.
func (v *ListPatchesPatchesPatch) GetSummary() string { return v.Summary }

// GetAuthor returns ListPatchesPatchesPatch.Author, and is useful for accessing the field via an interface.
func (v *ListPatchesPatchesPatch) GetAuthor() string { return v.Author }

// GetStatus returns ListPatchesPatchesPatch.Status, and is useful for accessing the field via an interface.
func (v *ListPatchesPatchesPatch) GetStatus() PatchStatus { return v.Status }

// GetCreatedAt returns ListPatchesPatchesPatch.CreatedAt, and is useful for accessing the field via an interface.
func (v *ListPatchesPatchesPatch) GetCreatedAt() time.Time { return v.CreatedAt }

// GetAppliedAt returns ListPatchesPatchesPatch.AppliedAt, and is useful for accessing the field via an interface.
func (v *ListPatchesPatchesPatch) GetAppliedAt() time.Time { return v.AppliedAt }

// ListPatchesResponse is returned by ListPatches on success.
type ListPatchesResponse struct {
	Patches []ListPatchesPatchesPatch `json:"patches"`
}

// GetPatches returns ListPatchesResponse.Patches, and is useful for accessing the field via an interface.
func (v *ListPatchesResponse) GetPatches() []ListPatchesPatchesPatch { return v.Patches }

// ListProjectsProjectsProject includes the requested fields of the GraphQL type Project.
type ListProjectsProjectsProject struct {
	Id          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	IsPublic    bool      `json:"isPublic"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// GetId returns ListProjectsProjectsProject.Id, and is useful for accessing the field via an interface.
func (v *ListProjectsProjectsProject) GetId() string { return v.Id }

// GetName returns ListProjectsProjectsProject.Name, and is useful for accessing the field via an interface.
func (v *ListProjectsProjectsProject) GetName() string { return v.Name }

// GetDescription returns ListProjectsProjectsProject.Description, and is useful for accessing the field via an interface.
func (v *ListProjectsProjectsProject) GetDescription() string { return v.Description }

// GetStatus returns ListProjectsProjectsProject.Status, and is useful for accessing the field via an interface.
func (v *ListProjectsProjectsProject) GetStatus() string { return v.Status }

// GetIsPublic returns ListProjectsProjectsProject.IsPublic, and is useful for accessing the field via an interface.
func (v *ListProjectsProjectsProject) GetIsPublic() bool { return v.IsPublic }

// GetUpdatedAt returns ListProjectsProjectsProject.UpdatedAt, and is useful for accessing the field via an interface.
func (v *ListProjectsProjectsProject) GetUpdatedAt() time.Time { return v.UpdatedAt }

// ListProjectsResponse is returned by ListProjects on success.
type ListProjectsResponse struct {
	Projects []ListProjectsProjectsProject `json:"projects"`
}

// GetProjects returns ListProjectsResponse.Projects, and is useful for accessing the field via an interface.
func (v *ListProjectsResponse) GetProjects() []ListProjectsProjectsProject { return v.Projects }

// MeMeUser includes the requested fields of the GraphQL type User.
type MeMeUser struct {
	Id        string    `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Plan      string    `json:"plan"`
	CreatedAt time.Time `json:"createdAt"`
}

// GetId returns MeMeUser.Id, and is useful for accessing the field via an interface.
func (v *MeMeUser) GetId() string { return v.Id }

// GetEmail returns MeMeUser.Email, and is useful for accessing the field via an interface.
func (v *MeMeUser) GetEmail() string { return v.Email }

// GetName returns MeMeUser.Name, and is useful for accessing the field via an interface.
func (v *MeMeUser) GetName() string { return v.Name }

// GetPlan returns MeMeUser.Plan, and is useful for accessing the field via an interface.
func (v *MeMeUser) GetPlan() string { return v.Plan }

// GetCreatedAt returns MeMeUser.CreatedAt, and is useful for accessing the field via an interface.
func (v *MeMeUser) GetCreatedAt() time.Time { return v.CreatedAt }

// MeResponse is returned by Me on success.
type MeResponse struct {
	Me MeMeUser `json:"me"`
}

// GetMe returns MeResponse.Me, and is useful for accessing the field via an interface.
func (v *MeResponse) GetMe() MeMeUser { return v.Me }

type MemoryKind string

const (
	MemoryKindProject   MemoryKind = "PROJECT"
	MemoryKindExecution MemoryKind = "EXECUTION"
	MemoryKindUser      MemoryKind = "USER"
	MemoryKindBusiness  MemoryKind = "BUSINESS"
)

var AllMemoryKind = []MemoryKind{
	MemoryKindProject,
	MemoryKindExecution,
	MemoryKindUser,
	MemoryKindBusiness,
}

type MemoryQueryInput struct {
	Kind      MemoryKind `json:"kind"`
	ProjectId string     `json:"projectId"`
	UserId    string     `json:"userId"`
	StoryId   string     `json:"storyId"`
	GateName  string     `json:"gateName"`
	Tag       string     `json:"tag"`
	Q         string     `json:"q"`
	Limit     int        `json:"limit"`
	Federated bool       `json:"federated"`
}

// GetKind returns MemoryQueryInput.Kind, and is useful for accessing the field via an interface.
func (v *MemoryQueryInput) GetKind() MemoryKind { return v.Kind }

// GetProjectId returns MemoryQueryInput.ProjectId, and is useful for accessing the field via an interface.
func (v *MemoryQueryInput) GetProjectId() string { return v.ProjectId }

// GetUserId returns MemoryQueryInput.UserId, and is useful for accessing the field via an interface.
func (v *MemoryQueryInput) GetUserId() string { return v.UserId }

// GetStoryId returns MemoryQueryInput.StoryId, and is useful for accessing the field via an interface.
func (v *MemoryQueryInput) GetStoryId() string { return v.StoryId }

// GetGateName returns MemoryQueryInput.GateName, and is useful for accessing the field via an interface.
func (v *MemoryQueryInput) GetGateName() string { return v.GateName }

// GetTag returns MemoryQueryInput.Tag, and is useful for accessing the field via an interface.
func (v *MemoryQueryInput) GetTag() string { return v.Tag }

// GetQ returns MemoryQueryInput.Q, and is useful for accessing the field via an interface.
func (v *MemoryQueryInput) GetQ() string { return v.Q }

// GetLimit returns MemoryQueryInput.Limit, and is useful for accessing the field via an interface.
func (v *MemoryQueryInput) GetLimit() int { return v.Limit }

// GetFederated returns MemoryQueryInput.Federated, and is useful for accessing the field via an interface.
func (v *MemoryQueryInput) GetFederated() bool { return v.Federated }

type PatchStatus string

const (
	PatchStatusProposed   PatchStatus = "PROPOSED"
	PatchStatusApproved   PatchStatus = "APPROVED"
	PatchStatusApplied    PatchStatus = "APPLIED"
	PatchStatusRejected   PatchStatus = "REJECTED"
	PatchStatusRolledBack PatchStatus = "ROLLED_BACK"
)

var AllPatchStatus = []PatchStatus{
	PatchStatusProposed,
	PatchStatusApproved,
	PatchStatusApplied,
	PatchStatusRejected,
	PatchStatusRolledBack,
}

// RunFinisherResponse is returned by RunFinisher on success.
type RunFinisherResponse struct {
	RunFinisher json.RawMessage `json:"runFinisher"`
}

// GetRunFinisher returns RunFinisherResponse.RunFinisher, and is useful for accessing the field via an interface.
func (v *RunFinisherResponse) GetRunFinisher() json.RawMessage { return v.RunFinisher }

// RunProjectResponse is returned by RunProject on success.
type RunProjectResponse struct {
	RunProject RunProjectRunProjectRunEvent `json:"-"`
}

// GetRunProject returns RunProjectResponse.RunProject, and is useful for accessing the field via an interface.
func (v *RunProjectResponse) GetRunProject() RunProjectRunProjectRunEvent { return v.RunProject }

func (v *RunProjectResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*RunProjectResponse
		RunProject json.RawMessage `json:"runProject"`
		graphql.NoUnmarshalJSON
	}
	firstPass.RunProjectResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.RunProject
		src := firstPass.RunProject
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalRunProjectRunProjectRunEvent(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal RunProjectResponse.RunProject: %w", err)
			}
		}
	}
	return nil
}

type __premarshalRunProjectResponse struct {
	RunProject json.RawMessage `json:"runProject"`
}

func (v *RunProjectResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *RunProjectResponse) __premarshalJSON() (*__premarshalRunProjectResponse, error) {
	var retval __premarshalRunProjectResponse

	{

		dst := &retval.RunProject
		src := v.RunProject
		var err error
		*dst, err = __marshalRunProjectRunProjectRunEvent(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal RunProjectResponse.RunProject: %w", err)
		}
	}
	return &retval, nil
}

// RunProjectRunProjectRunDoneEvent includes the requested fields of the GraphQL type RunDoneEvent.
type RunProjectRunProjectRunDoneEvent struct {
	Typename string          `json:"__typename"`
	Ts       time.Time       `json:"ts"`
	Ok       bool            `json:"ok"`
	Summary  json.RawMessage `json:"summary"`
}

// GetTypename returns RunProjectRunProjectRunDoneEvent.Typename, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunDoneEvent) GetTypename() string { return v.Typename }

// GetTs returns RunProjectRunProjectRunDoneEvent.Ts, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunDoneEvent) GetTs() time.Time { return v.Ts }

// GetOk returns RunProjectRunProjectRunDoneEvent.Ok, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunDoneEvent) GetOk() bool { return v.Ok }

// GetSummary returns RunProjectRunProjectRunDoneEvent.Summary, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunDoneEvent) GetSummary() json.RawMessage { return v.Summary }

// RunProjectRunProjectRunErrorEvent includes the requested fields of the GraphQL type RunErrorEvent.
type RunProjectRunProjectRunErrorEvent struct {
	Typename     string    `json:"__typename"`
	Ts           time.Time `json:"ts"`
	Code         string    `json:"code"`
	ErrorMessage string    `json:"errorMessage"`
}

// GetTypename returns RunProjectRunProjectRunErrorEvent.Typename, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunErrorEvent) GetTypename() string { return v.Typename }

// GetTs returns RunProjectRunProjectRunErrorEvent.Ts, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunErrorEvent) GetTs() time.Time { return v.Ts }

// GetCode returns RunProjectRunProjectRunErrorEvent.Code, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunErrorEvent) GetCode() string { return v.Code }

// GetErrorMessage returns RunProjectRunProjectRunErrorEvent.ErrorMessage, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunErrorEvent) GetErrorMessage() string { return v.ErrorMessage }

// RunProjectRunProjectRunEvent includes the requested fields of the GraphQL interface RunEvent.
//
// RunProjectRunProjectRunEvent is implemented by the following types:
// RunProjectRunProjectRunDoneEvent
// RunProjectRunProjectRunErrorEvent
// RunProjectRunProjectRunExecutionEvent
// RunProjectRunProjectRunGateEvent
type RunProjectRunProjectRunEvent interface {
	implementsGraphQLInterfaceRunProjectRunProjectRunEvent()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *RunProjectRunProjectRunDoneEvent) implementsGraphQLInterfaceRunProjectRunProjectRunEvent() {}
func (v *RunProjectRunProjectRunErrorEvent) implementsGraphQLInterfaceRunProjectRunProjectRunEvent() {
}
func (v *RunProjectRunProjectRunExecutionEvent) implementsGraphQLInterfaceRunProjectRunProjectRunEvent() {
}
func (v *RunProjectRunProjectRunGateEvent) implementsGraphQLInterfaceRunProjectRunProjectRunEvent() {}

func __unmarshalRunProjectRunProjectRunEvent(b []byte, v *RunProjectRunProjectRunEvent) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "RunDoneEvent":
		*v = new(RunProjectRunProjectRunDoneEvent)
		return json.Unmarshal(b, *v)
	case "RunErrorEvent":
		*v = new(RunProjectRunProjectRunErrorEvent)
		return json.Unmarshal(b, *v)
	case "RunExecutionEvent":
		*v = new(RunProjectRunProjectRunExecutionEvent)
		return json.Unmarshal(b, *v)
	case "RunGateEvent":
		*v = new(RunProjectRunProjectRunGateEvent)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing RunEvent.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for RunProjectRunProjectRunEvent: "%v"`, tn.TypeName)
	}
}

func __marshalRunProjectRunProjectRunEvent(v *RunProjectRunProjectRunEvent) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *RunProjectRunProjectRunDoneEvent:
		typename = "RunDoneEvent"

		result := struct {
			TypeName string `json:"__typename"`
			*RunProjectRunProjectRunDoneEvent
		}{typename, v}
		return json.Marshal(result)
	case *RunProjectRunProjectRunErrorEvent:
		typename = "RunErrorEvent"

		result := struct {
			TypeName string `json:"__typename"`
			*RunProjectRunProjectRunErrorEvent
		}{typename, v}
		return json.Marshal(result)
	case *RunProjectRunProjectRunExecutionEvent:
		typename = "RunExecutionEvent"

		result := struct {
			TypeName string `json:"__typename"`
			*RunProjectRunProjectRunExecutionEvent
		}{typename, v}
		return json.Marshal(result)
	case *RunProjectRunProjectRunGateEvent:
		typename = "RunGateEvent"

		result := struct {
			TypeName string `json:"__typename"`
			*RunProjectRunProjectRunGateEvent
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for RunProjectRunProjectRunEvent: "%T"`, v)
	}
}

// RunProjectRunProjectRunExecutionEvent includes the requested fields of the GraphQL type RunExecutionEvent.
type RunProjectRunProjectRunExecutionEvent struct {
	Typename string          `json:"__typename"`
	Ts       time.Time       `json:"ts"`
	Payload  json.RawMessage `json:"payload"`
}

// GetTypename returns RunProjectRunProjectRunExecutionEvent.Typename, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunExecutionEvent) GetTypename() string { return v.Typename }

// GetTs returns RunProjectRunProjectRunExecutionEvent.Ts, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunExecutionEvent) GetTs() time.Time { return v.Ts }

// GetPayload returns RunProjectRunProjectRunExecutionEvent.Payload, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunExecutionEvent) GetPayload() json.RawMessage { return v.Payload }

// RunProjectRunProjectRunGateEvent includes the requested fields of the GraphQL type RunGateEvent.
type RunProjectRunProjectRunGateEvent struct {
	Typename    string    `json:"__typename"`
	Ts          time.Time `json:"ts"`
	Gate        string    `json:"gate"`
	Status      string    `json:"status"`
	GateMessage string    `json:"gateMessage"`
}

// GetTypename returns RunProjectRunProjectRunGateEvent.Typename, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunGateEvent) GetTypename() string { return v.Typename }

// GetTs returns RunProjectRunProjectRunGateEvent.Ts, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunGateEvent) GetTs() time.Time { return v.Ts }

// GetGate returns RunProjectRunProjectRunGateEvent.Gate, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunGateEvent) GetGate() string { return v.Gate }

// GetStatus returns RunProjectRunProjectRunGateEvent.Status, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunGateEvent) GetStatus() string { return v.Status }

// GetGateMessage returns RunProjectRunProjectRunGateEvent.GateMessage, and is useful for accessing the field via an interface.
func (v *RunProjectRunProjectRunGateEvent) GetGateMessage() string { return v.GateMessage }

// SignInResponse is returned by SignIn on success.
type SignInResponse struct {
	SignIn SignInSignInSession `json:"signIn"`
}

// GetSignIn returns SignInResponse.SignIn, and is useful for accessing the field via an interface.
func (v *SignInResponse) GetSignIn() SignInSignInSession { return v.SignIn }

// SignInSignInSession includes the requested fields of the GraphQL type Session.
type SignInSignInSession struct {
	Token string                  `json:"token"`
	User  SignInSignInSessionUser `json:"user"`
}

// GetToken returns SignInSignInSession.Token, and is useful for accessing the field via an interface.
func (v *SignInSignInSession) GetToken() string { return v.Token }

// GetUser returns SignInSignInSession.User, and is useful for accessing the field via an interface.
func (v *SignInSignInSession) GetUser() SignInSignInSessionUser { return v.User }

// SignInSignInSessionUser includes the requested fields of the GraphQL type User.
type SignInSignInSessionUser struct {
	Id    string `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
	Plan  string `json:"plan"`
}

// GetId returns SignInSignInSessionUser.Id, and is useful for accessing the field via an interface.
func (v *SignInSignInSessionUser) GetId() string { return v.Id }

// GetEmail returns SignInSignInSessionUser.Email, and is useful for accessing the field via an interface.
func (v *SignInSignInSessionUser) GetEmail() string { return v.Email }

// GetName returns SignInSignInSessionUser.Name, and is useful for accessing the field via an interface.
func (v *SignInSignInSessionUser) GetName() string { return v.Name }

// GetPlan returns SignInSignInSessionUser.Plan, and is useful for accessing the field via an interface.
func (v *SignInSignInSessionUser) GetPlan() string { return v.Plan }

// StartDeployResponse is returned by StartDeploy on success.
type StartDeployResponse struct {
	StartDeploy StartDeployStartDeploy `json:"startDeploy"`
}

// GetStartDeploy returns StartDeployResponse.StartDeploy, and is useful for accessing the field via an interface.
func (v *StartDeployResponse) GetStartDeploy() StartDeployStartDeploy { return v.StartDeploy }

// StartDeployStartDeploy includes the requested fields of the GraphQL type Deploy.
type StartDeployStartDeploy struct {
	Id        string       `json:"id"`
	ProjectId string       `json:"projectId"`
	Target    string       `json:"target"`
	Status    DeployStatus `json:"status"`
	Url       string       `json:"url"`
	StartedAt time.Time    `json:"startedAt"`
}

// GetId returns StartDeployStartDeploy.Id, and is useful for accessing the field via an interface.
func (v *StartDeployStartDeploy) GetId() string { return v.Id }

// GetProjectId returns StartDeployStartDeploy.ProjectId, and is useful for accessing the field via an interface.
func (v *StartDeployStartDeploy) GetProjectId() string { return v.ProjectId }

// GetTarget returns StartDeployStartDeploy.Target, and is useful for accessing the field via an interface.
func (v *StartDeployStartDeploy) GetTarget() string { return v.Target }

// GetStatus returns StartDeployStartDeploy.Status, and is useful for accessing the field via an interface.
func (v *StartDeployStartDeploy) GetStatus() DeployStatus { return v.Status }

// GetUrl returns StartDeployStartDeploy.Url, and is useful for accessing the field via an interface.
func (v *StartDeployStartDeploy) GetUrl() string { return v.Url }

// GetStartedAt returns StartDeployStartDeploy.StartedAt, and is useful for accessing the field via an interface.
func (v *StartDeployStartDeploy) GetStartedAt() time.Time { return v.StartedAt }

// VerifyAuditResponse is returned by VerifyAudit on success.
type VerifyAuditResponse struct {
	VerifyAudit VerifyAuditVerifyAuditAuditVerifyResult `json:"verifyAudit"`
}

// GetVerifyAudit returns VerifyAuditResponse.VerifyAudit, and is useful for accessing the field via an interface.
func (v *VerifyAuditResponse) GetVerifyAudit() VerifyAuditVerifyAuditAuditVerifyResult {
	return v.VerifyAudit
}

// VerifyAuditVerifyAuditAuditVerifyResult includes the requested fields of the GraphQL type AuditVerifyResult.
type VerifyAuditVerifyAuditAuditVerifyResult struct {
	Intact        bool `json:"intact"`
	FirstBadIndex int  `json:"firstBadIndex"`
}

// GetIntact returns VerifyAuditVerifyAuditAuditVerifyResult.Intact, and is useful for accessing the field via an interface.
func (v *VerifyAuditVerifyAuditAuditVerifyResult) GetIntact() bool { return v.Intact }

// GetFirstBadIndex returns VerifyAuditVerifyAuditAuditVerifyResult.FirstBadIndex, and is useful for accessing the field via an interface.
func (v *VerifyAuditVerifyAuditAuditVerifyResult) GetFirstBadIndex() int { return v.FirstBadIndex }

// VersionResponse is returned by Version on success.
type VersionResponse struct {
	Ping    string                    `json:"ping"`
	Version VersionVersionVersionInfo `json:"version"`
}

// GetPing returns VersionResponse.Ping, and is useful for accessing the field via an interface.
func (v *VersionResponse) GetPing() string { return v.Ping }

// GetVersion returns VersionResponse.Version, and is useful for accessing the field via an interface.
func (v *VersionResponse) GetVersion() VersionVersionVersionInfo { return v.Version }

// VersionVersionVersionInfo includes the requested fields of the GraphQL type VersionInfo.
type VersionVersionVersionInfo struct {
	Version   string `json:"version"`
	Commit    string `json:"commit"`
	BuildTime string `json:"buildTime"`
	Service   string `json:"service"`
}

// GetVersion returns VersionVersionVersionInfo.Version, and is useful for accessing the field via an interface.
func (v *VersionVersionVersionInfo) GetVersion() string { return v.Version }

// GetCommit returns VersionVersionVersionInfo.Commit, and is useful for accessing the field via an interface.
func (v *VersionVersionVersionInfo) GetCommit() string { return v.Commit }

// GetBuildTime returns VersionVersionVersionInfo.BuildTime, and is useful for accessing the field via an interface.
func (v *VersionVersionVersionInfo) GetBuildTime() string { return v.BuildTime }

// GetService returns VersionVersionVersionInfo.Service, and is useful for accessing the field via an interface.
func (v *VersionVersionVersionInfo) GetService() string { return v.Service }

// __AddMemoryInput is used internally by genqlient
type __AddMemoryInput struct {
	Input AddMemoryInput `json:"input"`
}

// GetInput returns __AddMemoryInput.Input, and is useful for accessing the field via an interface.
func (v *__AddMemoryInput) GetInput() AddMemoryInput { return v.Input }

// __AgentTelemetryInput is used internally by genqlient
type __AgentTelemetryInput struct {
	Limit    int    `json:"limit"`
	Role     string `json:"role"`
	Provider string `json:"provider"`
	Model    string `json:"model"`
}

// GetLimit returns __AgentTelemetryInput.Limit, and is useful for accessing the field via an interface.
func (v *__AgentTelemetryInput) GetLimit() int { return v.Limit }

// GetRole returns __AgentTelemetryInput.Role, and is useful for accessing the field via an interface.
func (v *__AgentTelemetryInput) GetRole() string { return v.Role }

// GetProvider returns __AgentTelemetryInput.Provider, and is useful for accessing the field via an interface.
func (v *__AgentTelemetryInput) GetProvider() string { return v.Provider }

// GetModel returns __AgentTelemetryInput.Model, and is useful for accessing the field via an interface.
func (v *__AgentTelemetryInput) GetModel() string { return v.Model }

// __ApplyPatchInput is used internally by genqlient
type __ApplyPatchInput struct {
	PatchId string `json:"patchId"`
}

// GetPatchId returns __ApplyPatchInput.PatchId, and is useful for accessing the field via an interface.
func (v *__ApplyPatchInput) GetPatchId() string { return v.PatchId }

// __BulkDeleteProjectsInput is used internally by genqlient
type __BulkDeleteProjectsInput struct {
	Ids []string `json:"ids"`
}

// GetIds returns __BulkDeleteProjectsInput.Ids, and is useful for accessing the field via an interface.
func (v *__BulkDeleteProjectsInput) GetIds() []string { return v.Ids }

// __CreateProjectInput is used internally by genqlient
type __CreateProjectInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Idea        string `json:"idea"`
}

// GetName returns __CreateProjectInput.Name, and is useful for accessing the field via an interface.
func (v *__CreateProjectInput) GetName() string { return v.Name }

// GetDescription returns __CreateProjectInput.Description, and is useful for accessing the field via an interface.
func (v *__CreateProjectInput) GetDescription() string { return v.Description }

// GetIdea returns __CreateProjectInput.Idea, and is useful for accessing the field via an interface.
func (v *__CreateProjectInput) GetIdea() string { return v.Idea }

// __DeleteMemoryInput is used internally by genqlient
type __DeleteMemoryInput struct {
	Id string `json:"id"`
}

// GetId returns __DeleteMemoryInput.Id, and is useful for accessing the field via an interface.
func (v *__DeleteMemoryInput) GetId() string { return v.Id }

// __DeployStreamInput is used internally by genqlient
type __DeployStreamInput struct {
	DeployId string `json:"deployId"`
}

// GetDeployId returns __DeployStreamInput.DeployId, and is useful for accessing the field via an interface.
func (v *__DeployStreamInput) GetDeployId() string { return v.DeployId }

// __ExportGithubInput is used internally by genqlient
type __ExportGithubInput struct {
	ProjectId string `json:"projectId"`
	Owner     string `json:"owner"`
	Repo      string `json:"repo"`
}

// GetProjectId returns __ExportGithubInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__ExportGithubInput) GetProjectId() string { return v.ProjectId }

// GetOwner returns __ExportGithubInput.Owner, and is useful for accessing the field via an interface.
func (v *__ExportGithubInput) GetOwner() string { return v.Owner }

// GetRepo returns __ExportGithubInput.Repo, and is useful for accessing the field via an interface.
func (v *__ExportGithubInput) GetRepo() string { return v.Repo }

// __ExportZipUrlInput is used internally by genqlient
type __ExportZipUrlInput struct {
	ProjectId string `json:"projectId"`
}

// GetProjectId returns __ExportZipUrlInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__ExportZipUrlInput) GetProjectId() string { return v.ProjectId }

// __GetProjectGraphInput is used internally by genqlient
type __GetProjectGraphInput struct {
	Id string `json:"id"`
}

// GetId returns __GetProjectGraphInput.Id, and is useful for accessing the field via an interface.
func (v *__GetProjectGraphInput) GetId() string { return v.Id }

// __GetProjectInput is used internally by genqlient
type __GetProjectInput struct {
	Id string `json:"id"`
}

// GetId returns __GetProjectInput.Id, and is useful for accessing the field via an interface.
func (v *__GetProjectInput) GetId() string { return v.Id }

// __ListAuditInput is used internally by genqlient
type __ListAuditInput struct {
	Query AuditQueryInput `json:"query"`
}

// GetQuery returns __ListAuditInput.Query, and is useful for accessing the field via an interface.
func (v *__ListAuditInput) GetQuery() AuditQueryInput { return v.Query }

// __ListMemoryInput is used internally by genqlient
type __ListMemoryInput struct {
	Query MemoryQueryInput `json:"query"`
}

// GetQuery returns __ListMemoryInput.Query, and is useful for accessing the field via an interface.
func (v *__ListMemoryInput) GetQuery() MemoryQueryInput { return v.Query }

// __ListPatchesInput is used internally by genqlient
type __ListPatchesInput struct {
	ProjectId string `json:"projectId"`
}

// GetProjectId returns __ListPatchesInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__ListPatchesInput) GetProjectId() string { return v.ProjectId }

// __RunFinisherInput is used internally by genqlient
type __RunFinisherInput struct {
	Id string `json:"id"`
}

// GetId returns __RunFinisherInput.Id, and is useful for accessing the field via an interface.
func (v *__RunFinisherInput) GetId() string { return v.Id }

// __RunProjectInput is used internally by genqlient
type __RunProjectInput struct {
	ProjectId string `json:"projectId"`
}

// GetProjectId returns __RunProjectInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__RunProjectInput) GetProjectId() string { return v.ProjectId }

// __SignInInput is used internally by genqlient
type __SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns __SignInInput.Email, and is useful for accessing the field via an interface.
func (v *__SignInInput) GetEmail() string { return v.Email }

// GetPassword returns __SignInInput.Password, and is useful for accessing the field via an interface.
func (v *__SignInInput) GetPassword() string { return v.Password }

// __StartDeployInput is used internally by genqlient
type __StartDeployInput struct {
	ProjectId string          `json:"projectId"`
	Target    string          `json:"target"`
	Ref       string          `json:"ref"`
	Env       json.RawMessage `json:"env"`
}

// GetProjectId returns __StartDeployInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__StartDeployInput) GetProjectId() string { return v.ProjectId }

// GetTarget returns __StartDeployInput.Target, and is useful for accessing the field via an interface.
func (v *__StartDeployInput) GetTarget() string { return v.Target }

// GetRef returns __StartDeployInput.Ref, and is useful for accessing the field via an interface.
func (v *__StartDeployInput) GetRef() string { return v.Ref }

// GetEnv returns __StartDeployInput.Env, and is useful for accessing the field via an interface.
func (v *__StartDeployInput) GetEnv() json.RawMessage { return v.Env }

// The mutation executed by AddMemory.
const AddMemory_Operation = `
mutation AddMemory ($input: AddMemoryInput!) {
	addMemory(input: $input) {
		id
		kind
		userId
		projectId
		gateName
		title
		body
		tags
		createdAt
	}
}
`

func AddMemory(
	ctx_ context.Context,
	client_ graphql.Client,
	input AddMemoryInput,
) (data_ *AddMemoryResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "AddMemory",
		Query:  AddMemory_Operation,
		Variables: &__AddMemoryInput{
			Input: input,
		},
	}

	data_ = &AddMemoryResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by AgentTelemetry.
const AgentTelemetry_Operation = `
query AgentTelemetry ($limit: Int, $role: String, $provider: String, $model: String) {
	agentTelemetry(limit: $limit, role: $role, provider: $provider, model: $model) {
		id
		ts
		role
		provider
		model
		promptTokens
		completionTokens
		costUsd
		durationMs
		error
	}
}
`

func AgentTelemetry(
	ctx_ context.Context,
	client_ graphql.Client,
	limit int,
	role string,
	provider string,
	model string,
) (data_ *AgentTelemetryResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "AgentTelemetry",
		Query:  AgentTelemetry_Operation,
		Variables: &__AgentTelemetryInput{
			Limit:    limit,
			Role:     role,
			Provider: provider,
			Model:    model,
		},
	}

	data_ = &AgentTelemetryResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by ApplyPatch.
const ApplyPatch_Operation = `
mutation ApplyPatch ($patchId: ID!) {
	applyPatch(patchId: $patchId) {
		id
		status
		appliedAt
	}
}
`

func ApplyPatch(
	ctx_ context.Context,
	client_ graphql.Client,
	patchId string,
) (data_ *ApplyPatchResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ApplyPatch",
		Query:  ApplyPatch_Operation,
		Variables: &__ApplyPatchInput{
			PatchId: patchId,
		},
	}

	data_ = &ApplyPatchResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by BulkDeleteProjects.
const BulkDeleteProjects_Operation = `
mutation BulkDeleteProjects ($ids: [ID!]!) {
	bulkDeleteProjects(ids: $ids) {
		ok
		message
	}
}
`

func BulkDeleteProjects(
	ctx_ context.Context,
	client_ graphql.Client,
	ids []string,
) (data_ *BulkDeleteProjectsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "BulkDeleteProjects",
		Query:  BulkDeleteProjects_Operation,
		Variables: &__BulkDeleteProjectsInput{
			Ids: ids,
		},
	}

	data_ = &BulkDeleteProjectsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateProject.
const CreateProject_Operation = `
mutation CreateProject ($name: String!, $description: String, $idea: String) {
	createProject(input: {name:$name,description:$description,idea:$idea}) {
		id
		name
		description
		status
		createdAt
	}
}
`

func CreateProject(
	ctx_ context.Context,
	client_ graphql.Client,
	name string,
	description string,
	idea string,
) (data_ *CreateProjectResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateProject",
		Query:  CreateProject_Operation,
		Variables: &__CreateProjectInput{
			Name:        name,
			Description: description,
			Idea:        idea,
		},
	}

	data_ = &CreateProjectResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by DeleteMemory.
const DeleteMemory_Operation = `
mutation DeleteMemory ($id: ID!) {
	deleteMemory(id: $id) {
		ok
		message
	}
}
`

func DeleteMemory(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *DeleteMemoryResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "DeleteMemory",
		Query:  DeleteMemory_Operation,
		Variables: &__DeleteMemoryInput{
			Id: id,
		},
	}

	data_ = &DeleteMemoryResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The subscription executed by DeployStream.
const DeployStream_Operation = `
subscription DeployStream ($deployId: ID!) {
	deployStream(deployId: $deployId) {
		__typename
		... on DeployStateEvent {
			deployId
			status
			ts
		}
		... on DeployLogEvent {
			deployId
			line {
				ts
				level
				message
			}
		}
		... on DeployFinishedEvent {
			deployId
			status
			url
			durationMs
		}
		... on DeployErrorEvent {
			deployId
			code
			message
		}
	}
}
`

// To unsubscribe, use [graphql.WebSocketClient.Unsubscribe]
func DeployStream(
	ctx_ context.Context,
	client_ graphql.WebSocketClient,
	deployId string,
) (dataChan_ chan DeployStreamWsResponse, subscriptionID_ string, err_ error) {
	req_ := &graphql.Request{
		OpName: "DeployStream",
		Query:  DeployStream_Operation,
		Variables: &__DeployStreamInput{
			DeployId: deployId,
		},
	}

	dataChan_ = make(chan DeployStreamWsResponse)
	subscriptionID_, err_ = client_.Subscribe(req_, dataChan_, DeployStreamForwardData)

	return dataChan_, subscriptionID_, err_
}

type DeployStreamWsResponse graphql.BaseResponse[*DeployStreamResponse]

func DeployStreamForwardData(interfaceChan interface{}, jsonRawMsg json.RawMessage) error {
	var gqlResp graphql.Response
	var wsResp DeployStreamWsResponse
	err := json.Unmarshal(jsonRawMsg, &gqlResp)
	if err != nil {
		return err
	}
	if len(gqlResp.Errors) == 0 {
		err = json.Unmarshal(jsonRawMsg, &wsResp)
		if err != nil {
			return err
		}
	} else {
		wsResp.Errors = gqlResp.Errors
	}
	dataChan_, ok := interfaceChan.(chan DeployStreamWsResponse)
	if !ok {
		return errors.New("failed to cast interface into 'chan DeployStreamWsResponse'")
	}
	dataChan_ <- wsResp
	return nil
}

// The mutation executed by ExportGithub.
const ExportGithub_Operation = `
mutation ExportGithub ($projectId: ID!, $owner: String!, $repo: String!) {
	exportGithub(projectId: $projectId, owner: $owner, repo: $repo) {
		ok
		message
	}
}
`

func ExportGithub(
	ctx_ context.Context,
	client_ graphql.Client,
	projectId string,
	owner string,
	repo string,
) (data_ *ExportGithubResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ExportGithub",
		Query:  ExportGithub_Operation,
		Variables: &__ExportGithubInput{
			ProjectId: projectId,
			Owner:     owner,
			Repo:      repo,
		},
	}

	data_ = &ExportGithubResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by ExportZipUrl.
const ExportZipUrl_Operation = `
mutation ExportZipUrl ($projectId: ID!) {
	exportZipUrl(projectId: $projectId)
}
`

func ExportZipUrl(
	ctx_ context.Context,
	client_ graphql.Client,
	projectId string,
) (data_ *ExportZipUrlResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ExportZipUrl",
		Query:  ExportZipUrl_Operation,
		Variables: &__ExportZipUrlInput{
			ProjectId: projectId,
		},
	}

	data_ = &ExportZipUrlResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetProject.
const GetProject_Operation = `
query GetProject ($id: ID!) {
	project(id: $id) {
		id
		name
		description
		status
		ownerId
		isPublic
		idea
		createdAt
		updatedAt
	}
}
`

func GetProject(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *GetProjectResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetProject",
		Query:  GetProject_Operation,
		Variables: &__GetProjectInput{
			Id: id,
		},
	}

	data_ = &GetProjectResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetProjectGraph.
const GetProjectGraph_Operation = `
query GetProjectGraph ($id: ID!) {
	projectGraph(id: $id) {
		nodes {
			id
			path
			language
			size
		}
		edges {
			from
			to
			kind
		}
	}
}
`

func GetProjectGraph(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *GetProjectGraphResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetProjectGraph",
		Query:  GetProjectGraph_Operation,
		Variables: &__GetProjectGraphInput{
			Id: id,
		},
	}

	data_ = &GetProjectGraphResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListAudit.
const ListAudit_Operation = `
query ListAudit ($query: AuditQueryInput) {
	audit(query: $query) {
		id
		ts
		userId
		projectId
		action
		outcome
		hash
		prevHash
		payload
	}
}
`

func ListAudit(
	ctx_ context.Context,
	client_ graphql.Client,
	query AuditQueryInput,
) (data_ *ListAuditResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListAudit",
		Query:  ListAudit_Operation,
		Variables: &__ListAuditInput{
			Query: query,
		},
	}

	data_ = &ListAuditResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListMemory.
const ListMemory_Operation = `
query ListMemory ($query: MemoryQueryInput) {
	memory(query: $query) {
		id
		kind
		userId
		projectId
		storyId
		gateName
		title
		body
		tags
		createdAt
	}
}
`

func ListMemory(
	ctx_ context.Context,
	client_ graphql.Client,
	query MemoryQueryInput,
) (data_ *ListMemoryResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListMemory",
		Query:  ListMemory_Operation,
		Variables: &__ListMemoryInput{
			Query: query,
		},
	}

	data_ = &ListMemoryResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListPatches.
const ListPatches_Operation = `
query ListPatches ($projectId: ID!) {
	patches(projectId: $projectId) {
		id
		projectId
		title
		summary
		author
		status
		createdAt
		appliedAt
	}
}
`

func ListPatches(
	ctx_ context.Context,
	client_ graphql.Client,
	projectId string,
) (data_ *ListPatchesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListPatches",
		Query:  ListPatches_Operation,
		Variables: &__ListPatchesInput{
			ProjectId: projectId,
		},
	}

	data_ = &ListPatchesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListProjects.
const ListProjects_Operation = `
query ListProjects {
	projects {
		id
		name
		description
		status
		isPublic
		updatedAt
	}
}
`

func ListProjects(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *ListProjectsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListProjects",
		Query:  ListProjects_Operation,
	}

	data_ = &ListProjectsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by Me.
const Me_Operation = `
query Me {
	me {
		id
		email
		name
		plan
		createdAt
	}
}
`

func Me(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *MeResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Me",
		Query:  Me_Operation,
	}

	data_ = &MeResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by RunFinisher.
const RunFinisher_Operation = `
mutation RunFinisher ($id: ID!) {
	runFinisher(id: $id)
}
`

func RunFinisher(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *RunFinisherResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "RunFinisher",
		Query:  RunFinisher_Operation,
		Variables: &__RunFinisherInput{
			Id: id,
		},
	}

	data_ = &RunFinisherResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The subscription executed by RunProject.
const RunProject_Operation = `
subscription RunProject ($projectId: ID!) {
	runProject(projectId: $projectId) {
		__typename
		... on RunExecutionEvent {
			ts
			payload
		}
		... on RunGateEvent {
			ts
			gate
			status
			gateMessage: message
		}
		... on RunDoneEvent {
			ts
			ok
			summary
		}
		... on RunErrorEvent {
			ts
			code
			errorMessage: message
		}
	}
}
`

// To unsubscribe, use [graphql.WebSocketClient.Unsubscribe]
func RunProject(
	ctx_ context.Context,
	client_ graphql.WebSocketClient,
	projectId string,
) (dataChan_ chan RunProjectWsResponse, subscriptionID_ string, err_ error) {
	req_ := &graphql.Request{
		OpName: "RunProject",
		Query:  RunProject_Operation,
		Variables: &__RunProjectInput{
			ProjectId: projectId,
		},
	}

	dataChan_ = make(chan RunProjectWsResponse)
	subscriptionID_, err_ = client_.Subscribe(req_, dataChan_, RunProjectForwardData)

	return dataChan_, subscriptionID_, err_
}

type RunProjectWsResponse graphql.BaseResponse[*RunProjectResponse]

func RunProjectForwardData(interfaceChan interface{}, jsonRawMsg json.RawMessage) error {
	var gqlResp graphql.Response
	var wsResp RunProjectWsResponse
	err := json.Unmarshal(jsonRawMsg, &gqlResp)
	if err != nil {
		return err
	}
	if len(gqlResp.Errors) == 0 {
		err = json.Unmarshal(jsonRawMsg, &wsResp)
		if err != nil {
			return err
		}
	} else {
		wsResp.Errors = gqlResp.Errors
	}
	dataChan_, ok := interfaceChan.(chan RunProjectWsResponse)
	if !ok {
		return errors.New("failed to cast interface into 'chan RunProjectWsResponse'")
	}
	dataChan_ <- wsResp
	return nil
}

// The mutation executed by SignIn.
const SignIn_Operation = `
mutation SignIn ($email: String!, $password: String!) {
	signIn(input: {email:$email,password:$password}) {
		token
		user {
			id
			email
			name
			plan
		}
	}
}
`

func SignIn(
	ctx_ context.Context,
	client_ graphql.Client,
	email string,
	password string,
) (data_ *SignInResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "SignIn",
		Query:  SignIn_Operation,
		Variables: &__SignInInput{
			Email:    email,
			Password: password,
		},
	}

	data_ = &SignInResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by StartDeploy.
const StartDeploy_Operation = `
mutation StartDeploy ($projectId: ID!, $target: String!, $ref: String, $env: JSON) {
	startDeploy(input: {projectId:$projectId,target:$target,ref:$ref,env:$env}) {
		id
		projectId
		target
		status
		url
		startedAt
	}
}
`

func StartDeploy(
	ctx_ context.Context,
	client_ graphql.Client,
	projectId string,
	target string,
	ref string,
	env json.RawMessage,
) (data_ *StartDeployResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "StartDeploy",
		Query:  StartDeploy_Operation,
		Variables: &__StartDeployInput{
			ProjectId: projectId,
			Target:    target,
			Ref:       ref,
			Env:       env,
		},
	}

	data_ = &StartDeployResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by VerifyAudit.
const VerifyAudit_Operation = `
query VerifyAudit {
	verifyAudit {
		intact
		firstBadIndex
	}
}
`

func VerifyAudit(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *VerifyAuditResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "VerifyAudit",
		Query:  VerifyAudit_Operation,
	}

	data_ = &VerifyAuditResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by Version.
const Version_Operation = `
query Version {
	ping
	version {
		version
		commit
		buildTime
		service
	}
}
`

func Version(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *VersionResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Version",
		Query:  Version_Operation,
	}

	data_ = &VersionResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
