package appetize

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"ironflyer/apps/orchestrator/internal/domain"
)

// UploadIntent is the cleaned-up input the resolver passes to
// Service.UploadFromProjectBuild after parsing AppetizeUploadInput from
// the GraphQL request. Decoupled from the gqlgen model so the resolver
// (regenerated by codegen) doesn't have to import this package.
type UploadIntent struct {
	ProjectID     string
	BuildID       string
	DeviceProfile string
	// ArtifactPath is the resolved on-disk path of the build artifact
	// inside the user's workspace. The resolver picks this from the
	// project's ArtifactMobileBuild report when buildId matches.
	ArtifactPath string
	// Platform is "ios" | "android" — derived from the build report
	// platform field. Appetize requires this even though it can be
	// inferred from the filename.
	Platform string
	// FileName is the basename Appetize stores. Must end in .ipa for
	// iOS, .apk / .aab for Android.
	FileName string
	// ArtifactReader streams the artifact bytes. Caller owns the
	// underlying source (usually a runtime FS handle).
	ArtifactReader interface {
		Read(p []byte) (n int, err error)
	}
}

// AppResult is the resolver-facing return shape — a thin projection of
// App + the precomputed embed URL so the resolver doesn't double-call
// EmbedURL.
type AppResult struct {
	PublicKey string
	EmbedURL  string
	Platform  string
	CreatedAt time.Time
}

// Service is the resolver-facing façade. Keeps the GraphQL resolver
// free of multipart / HTTP plumbing — it just calls UploadFromProjectBuild
// and renders the result.
type Service struct {
	client *MeteredClient
}

// NewService constructs the resolver façade.
func NewService(c *MeteredClient) *Service { return &Service{client: c} }

// UploadFromProjectBuild uploads the build artifact to Appetize and
// returns the embed-ready result. Caller passes the resolved artifact
// stream; this layer doesn't know anything about workspace I/O.
func (s *Service) UploadFromProjectBuild(ctx context.Context, intent UploadIntent) (*AppResult, error) {
	if s == nil || s.client == nil {
		return nil, errors.New("appetize: service not configured")
	}
	if strings.TrimSpace(intent.ProjectID) == "" {
		return nil, errors.New("appetize: missing project id")
	}
	if intent.ArtifactReader == nil {
		return nil, errors.New("appetize: missing artifact reader")
	}
	platform := strings.ToLower(strings.TrimSpace(intent.Platform))
	if platform == "" {
		// Fallback inference from filename — Appetize will reject a
		// mismatch but the orchestrator should still try.
		switch {
		case strings.HasSuffix(strings.ToLower(intent.FileName), ".ipa"):
			platform = "ios"
		case strings.HasSuffix(strings.ToLower(intent.FileName), ".apk"),
			strings.HasSuffix(strings.ToLower(intent.FileName), ".aab"):
			platform = "android"
		}
	}
	if platform != "ios" && platform != "android" {
		return nil, fmt.Errorf("appetize: cannot infer platform for %q", intent.FileName)
	}
	app, err := s.client.UploadApp(ctx, UploadRequest{
		ArtifactReader: intent.ArtifactReader,
		FileName:       intent.FileName,
		Platform:       platform,
		BuildName:      intent.BuildID,
		Note:           "ironflyer:" + intent.ProjectID,
	})
	if err != nil {
		return nil, err
	}
	embed := s.client.EmbedURL(app.PublicKey, EmbedOptions{
		Device:   defaultDeviceFor(platform, intent.DeviceProfile),
		Centered: true,
		AutoPlay: true,
	})
	return &AppResult{
		PublicKey: app.PublicKey,
		EmbedURL:  embed,
		Platform:  app.Platform,
		CreatedAt: app.Created,
	}, nil
}

// Delete proxies to the underlying REST client.
func (s *Service) Delete(ctx context.Context, publicKey string) error {
	if s == nil || s.client == nil {
		return errors.New("appetize: service not configured")
	}
	return s.client.DeleteApp(ctx, publicKey)
}

func defaultDeviceFor(platform, override string) string {
	if strings.TrimSpace(override) != "" {
		return override
	}
	if platform == "ios" {
		return "iphone15pro"
	}
	return "pixel8"
}

// ResolveForProject hands back an *AppetizeApp shaped struct based on
// the project's most recent build artifact + an existing
// publicKey. Used by the studio so the mobile pane can decide whether
// to render the iframe or the "upload to Appetize" CTA without
// reaching into the appetize package internals.
func ResolveForProject(p *domain.Project) (publicKey string, ok bool) {
	if p == nil {
		return "", false
	}
	raw, ok := p.GetArtifact("appetize_app")
	if !ok || len(raw) == 0 {
		return "", false
	}
	// Stored shape: {"publicKey":"...","platform":"ios|android"}.
	idx := strings.Index(string(raw), `"publicKey"`)
	if idx < 0 {
		return "", false
	}
	rest := string(raw)[idx:]
	open := strings.IndexByte(rest, ':')
	if open < 0 {
		return "", false
	}
	rest = rest[open+1:]
	q := strings.IndexByte(rest, '"')
	if q < 0 {
		return "", false
	}
	rest = rest[q+1:]
	q2 := strings.IndexByte(rest, '"')
	if q2 <= 0 {
		return "", false
	}
	return rest[:q2], true
}
