// Package verifier — playwright.go materialises one criterion's
// action plan as a Playwright TypeScript file inside the workspace
// sandbox, then drives a headless chromium run against it. The
// orchestrator process never owns the browser — every command runs
// through runtime.Exec so per-user isolation is preserved.
//
// We do NOT ship a Playwright spec file in the Ironflyer repo (the
// repo-wide "no tests, ever" rule is constitutional). The TS file
// the verifier writes lives in `.ironflyer/verify/<criterion-id>.ts`
// under the user's sandbox — it's an ephemeral artifact, not a
// committed test.

package verifier

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"ironflyer/core/orchestrator/internal/operations/runtime"
)

// PlaywrightResult is the outcome of one chromium drive. Success is
// the boolean the gate cares about; Stdout/Stderr are the raw bytes
// for the agent's fallback evidence hint.
type PlaywrightResult struct {
	Success    bool
	ExitCode   int
	Stdout     string
	Stderr     string
	DurationMS int64
	TimedOut   bool
}

// RunPlaywright writes the script, runs it, and returns a parsed
// result. criterionID is folded into the file name so concurrent
// runs do not collide; the runtime cleans the .ironflyer/verify
// directory at the end of the workspace lifecycle.
//
// All commands run with a generous 90-second timeout — chromium cold
// starts on first run inside a fresh container can take 20+ seconds.
func RunPlaywright(ctx context.Context, rt *runtime.Client, bearer, workspaceID, previewURL, criterionID string, actions []Action) (PlaywrightResult, error) {
	if rt == nil || !rt.Enabled() {
		return PlaywrightResult{}, errors.New("verifier: runtime not configured")
	}
	if workspaceID == "" {
		return PlaywrightResult{}, errors.New("verifier: workspace required")
	}
	if strings.TrimSpace(previewURL) == "" {
		return PlaywrightResult{}, errors.New("verifier: preview URL required")
	}
	script, err := renderPlaywrightScript(previewURL, criterionID, actions)
	if err != nil {
		return PlaywrightResult{}, err
	}
	safeID := sanitiseCriterionID(criterionID)
	scriptPath := ".ironflyer/verify/" + safeID + ".ts"
	// Write the script via a `cat <<EOF > path` heredoc so we never
	// have to fight quoting through doJSON. The runtime already gives
	// us a bash via ExecOpts.Shell.
	writeCmd := "mkdir -p .ironflyer/verify && cat > " + shellQuote(scriptPath) + " <<'IF_VERIFIER_EOF'\n" + script + "\nIF_VERIFIER_EOF"
	if _, err := rt.Exec(ctx, bearer, workspaceID, runtime.ExecOpts{
		Shell: writeCmd, TimeoutSeconds: 30,
	}); err != nil {
		return PlaywrightResult{}, fmt.Errorf("write script: %w", err)
	}
	// Drive Playwright. We invoke `npx playwright test` with a single
	// test file (the script we just wrote) and JSON reporter so we
	// can extract a structured pass/fail. `--retries=0` keeps the
	// run deterministic; `--workers=1` keeps the headless chromium
	// single-tab so screenshot artifacts land at a predictable path.
	runCmd := "npx --yes playwright test " + shellQuote(scriptPath) +
		" --reporter=list --retries=0 --workers=1 --timeout=60000"
	start := time.Now()
	exec, err := rt.Exec(ctx, bearer, workspaceID, runtime.ExecOpts{
		Shell: runCmd, TimeoutSeconds: 120,
	})
	dur := time.Since(start).Milliseconds()
	if err != nil {
		return PlaywrightResult{}, fmt.Errorf("playwright exec: %w", err)
	}
	return PlaywrightResult{
		Success:    !exec.TimedOut && exec.ExitCode == 0,
		ExitCode:   exec.ExitCode,
		Stdout:     exec.Stdout,
		Stderr:     exec.Stderr,
		DurationMS: dur,
		TimedOut:   exec.TimedOut,
	}, nil
}

// renderPlaywrightScript emits a single-test file that walks the
// action sequence. We use Playwright's test runner (rather than a
// raw chromium.launch) so reporters give us a structured pass/fail
// without ad-hoc parsing.
//
// The script is intentionally defensive: every selector wait is
// bounded by a 10s timeout, screenshots use fullPage to capture the
// route end-to-end, and the test refuses to run when previewURL is
// empty (it will pass the empty-string guard above but a defensive
// `if (!base) throw` keeps the script honest if someone edits it by
// hand later).
func renderPlaywrightScript(previewURL, criterionID string, actions []Action) (string, error) {
	stepsJSON, err := json.Marshal(actions)
	if err != nil {
		return "", err
	}
	// Use a const for the previewURL so the heredoc never has to
	// quote it; encoding/json handles the actions slice cleanly.
	var b strings.Builder
	b.WriteString("// Generated by ironflyer verifier — DO NOT EDIT.\n")
	b.WriteString("// Criterion ID: ")
	b.WriteString(criterionID)
	b.WriteString("\n")
	b.WriteString("import { test, expect } from '@playwright/test';\n\n")
	b.WriteString("const BASE = ")
	bts, _ := json.Marshal(previewURL)
	b.Write(bts)
	b.WriteString(";\n")
	b.WriteString("const STEPS = ")
	b.Write(stepsJSON)
	b.WriteString(";\n\n")
	b.WriteString("test('criterion ")
	b.WriteString(jsString(criterionID))
	b.WriteString("', async ({ page }) => {\n")
	b.WriteString("  if (!BASE) throw new Error('preview URL missing');\n")
	b.WriteString("  for (const step of STEPS) {\n")
	b.WriteString("    switch (step.type) {\n")
	b.WriteString("      case 'goto': {\n")
	b.WriteString("        const target = step.url && /^https?:/i.test(step.url) ? step.url : (BASE + (step.url || '/'));\n")
	b.WriteString("        await page.goto(target, { waitUntil: 'domcontentloaded', timeout: 30000 });\n")
	b.WriteString("        break;\n")
	b.WriteString("      }\n")
	b.WriteString("      case 'waitForSelector':\n")
	b.WriteString("        await page.waitForSelector(step.selector, { timeout: 10000 });\n")
	b.WriteString("        break;\n")
	b.WriteString("      case 'fill':\n")
	b.WriteString("        await page.fill(step.selector, step.value || '');\n")
	b.WriteString("        break;\n")
	b.WriteString("      case 'click':\n")
	b.WriteString("        await page.click(step.selector, { timeout: 10000 });\n")
	b.WriteString("        break;\n")
	b.WriteString("      case 'screenshot': {\n")
	b.WriteString("        const name = step.name || 'shot';\n")
	b.WriteString("        await page.screenshot({ path: `.ironflyer/verify/")
	b.WriteString(sanitiseCriterionID(criterionID))
	b.WriteString("-${name}.png`, fullPage: true });\n")
	b.WriteString("        break;\n")
	b.WriteString("      }\n")
	b.WriteString("      default:\n")
	b.WriteString("        // Unknown step types are ignored — the gate's repair loop\n")
	b.WriteString("        // will re-plan if the verdict comes back as fail.\n")
	b.WriteString("        break;\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("  // Implicit pass: every step completed without throwing.\n")
	b.WriteString("  expect(true).toBe(true);\n")
	b.WriteString("});\n")
	return b.String(), nil
}

// sanitiseCriterionID keeps only alphanumerics, dashes, and
// underscores. Used in both the workspace path and the screenshot
// file name so anything pathological the model emits (slashes,
// dots, quotes) cannot escape the .ironflyer/verify directory.
func sanitiseCriterionID(id string) string {
	var b strings.Builder
	for _, r := range id {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	out := b.String()
	if out == "" {
		return "criterion"
	}
	if len(out) > 80 {
		out = out[:80]
	}
	return out
}

// jsString escapes a string for inclusion inside JS single-quoted
// literal contexts. Sufficient for the test name; we never embed
// untrusted bytes into shell or HTML through this path.
func jsString(s string) string {
	return strings.NewReplacer(`\`, `\\`, `'`, `\'`, "\n", `\n`).Replace(s)
}

// shellQuote wraps a value in single quotes for safe shell embed.
// Mirrors the helper in finisher/gates.go; duplicated here so the
// verifier package does not import finisher (avoids a cycle).
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
