config:
  aws:region: eu-west-1
  infra:vpcCidr: 10.10.0.0/16
  infra:singleNatGateway: "true"
  infra:k8sVersion: "1.30"
  infra:publicApiCidrs:
    - 0.0.0.0/0
  infra:orchestratorInstanceType: t3.medium
  infra:runtimeInstanceType: t3.large
  infra:useKarpenter: "false"
  infra:rootDomain: dev.ironflyer.dev
  infra:regionSubdomain: ""
  infra:webSpaBucketName: ""
  infra:allowlistedIps: ""
  infra:dataStackName: ""
  ironflyer:vercelEnabled: "false"
  ironflyer:vercelTeamId: ironflyer
  ironflyer:vercelDomain: app.dev.ironflyer.dev
  ironflyer:vercelBranch: main
  ironflyer:vercelFramework: nextjs
  ironflyer:vercelGitRepoOwner: ""
  ironflyer:vercelGitRepoName: ""
