config:
  aws:region: eu-west-1
  infra:vpcCidr: 10.20.0.0/16
  infra:singleNatGateway: "false"
  infra:k8sVersion: "1.30"
  infra:publicApiCidrs:
    - 0.0.0.0/0
  infra:orchestratorInstanceType: m6i.large
  infra:runtimeInstanceType: m6i.large
  infra:useKarpenter: "false"
  infra:rootDomain: staging.ironflyer.dev
  infra:regionSubdomain: ""
  infra:webSpaBucketName: ""
  infra:allowlistedIps: ""
  infra:dataStackName: ""
  ironflyer:vercelEnabled: "true"
  ironflyer:vercelTeamId: ironflyer
  ironflyer:vercelDomain: app.staging.ironflyer.dev
  ironflyer:vercelBranch: staging
  ironflyer:vercelFramework: nextjs
  ironflyer:vercelGitRepoOwner: ironflyer
  ironflyer:vercelGitRepoName: ironflyer-copilot
