// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type InlineDelta interface {
	IsInlineDelta()
}

type PatchOp interface {
	IsPatchOp()
}

type RunEvent interface {
	IsRunEvent()
}

type AbuseScoreResult struct {
	TenantID string `json:"tenantID"`
	UserID   string `json:"userID"`
	Score    int    `json:"score"`
	Tier     string `json:"tier"`
}

type Agent struct {
	Role           string   `json:"role"`
	System         *string  `json:"system,omitempty"`
	Capabilities   []string `json:"capabilities"`
	EnableThinking bool     `json:"enableThinking"`
}

type AgentCall struct {
	ID               string    `json:"id"`
	Ts               time.Time `json:"ts"`
	Role             *string   `json:"role,omitempty"`
	Provider         string    `json:"provider"`
	Model            *string   `json:"model,omitempty"`
	PromptTokens     int       `json:"promptTokens"`
	CompletionTokens int       `json:"completionTokens"`
	CacheReadTokens  int       `json:"cacheReadTokens"`
	CacheWriteTokens int       `json:"cacheWriteTokens"`
	CostUsd          Decimal   `json:"costUsd"`
	DurationMs       int       `json:"durationMs"`
	Error            *string   `json:"error,omitempty"`
	Capabilities     []string  `json:"capabilities,omitempty"`
	UserID           *string   `json:"userId,omitempty"`
	ProjectID        *string   `json:"projectId,omitempty"`
}

type AppetizeApp struct {
	PublicKey string    `json:"publicKey"`
	EmbedURL  string    `json:"embedUrl"`
	Platform  string    `json:"platform"`
	CreatedAt time.Time `json:"createdAt"`
}

type AppetizeUploadInput struct {
	ProjectID     string  `json:"projectId"`
	BuildID       string  `json:"buildId"`
	DeviceProfile *string `json:"deviceProfile,omitempty"`
}

type ArchRule struct {
	From  string `json:"from"`
	To    string `json:"to"`
	Allow bool   `json:"allow"`
}

type Architecture struct {
	Layers []string   `json:"layers"`
	Rules  []ArchRule `json:"rules"`
	Cycles string     `json:"cycles"`
}

type AuditChainProof struct {
	WindowStart time.Time         `json:"windowStart"`
	WindowEnd   time.Time         `json:"windowEnd"`
	EntryCount  int               `json:"entryCount"`
	StartHash   string            `json:"startHash"`
	EndHash     string            `json:"endHash"`
	Verified    bool              `json:"verified"`
	BrokenLinks []BrokenAuditLink `json:"brokenLinks"`
}

type AuditEntry struct {
	ID         string       `json:"id"`
	Ts         time.Time    `json:"ts"`
	UserID     *string      `json:"userId,omitempty"`
	ProjectID  *string      `json:"projectId,omitempty"`
	Action     string       `json:"action"`
	Outcome    AuditOutcome `json:"outcome"`
	Hash       string       `json:"hash"`
	PrevHash   *string      `json:"prevHash,omitempty"`
	Payload    JSON         `json:"payload,omitempty"`
	Actor      *string      `json:"actor,omitempty"`
	Resource   *string      `json:"resource,omitempty"`
	StoryID    *string      `json:"storyId,omitempty"`
	GateName   *string      `json:"gateName,omitempty"`
	AgentRole  *string      `json:"agentRole,omitempty"`
	Summary    *string      `json:"summary,omitempty"`
	InputHash  *string      `json:"inputHash,omitempty"`
	OutputHash *string      `json:"outputHash,omitempty"`
	Ok         bool         `json:"ok"`
}

type AuditExportFilter struct {
	TenantID     string    `json:"tenantId"`
	Since        time.Time `json:"since"`
	Until        time.Time `json:"until"`
	EventTypes   []string  `json:"eventTypes,omitempty"`
	Format       *string   `json:"format,omitempty"`
	IncludeAttrs *bool     `json:"includeAttrs,omitempty"`
}

type AuditExportPreview struct {
	EstimatedEntryCount int        `json:"estimatedEntryCount"`
	EstimatedBytes      int        `json:"estimatedBytes"`
	Format              string     `json:"format"`
	SignedURL           *string    `json:"signedURL,omitempty"`
	ExpiresAt           *time.Time `json:"expiresAt,omitempty"`
}

type AuditQueryInput struct {
	UserID    *string       `json:"userId,omitempty"`
	ProjectID *string       `json:"projectId,omitempty"`
	Action    *string       `json:"action,omitempty"`
	Outcome   *AuditOutcome `json:"outcome,omitempty"`
	Since     *time.Time    `json:"since,omitempty"`
	Until     *time.Time    `json:"until,omitempty"`
	Limit     *int          `json:"limit,omitempty"`
}

type AuditVerifyResult struct {
	Intact        bool `json:"intact"`
	FirstBadIndex int  `json:"firstBadIndex"`
}

type BanditCapability struct {
	Capability string         `json:"capability"`
	Total      int            `json:"total"`
	Winners    []BanditWinner `json:"winners"`
}

type BanditRanking struct {
	Capabilities   []BanditCapability `json:"capabilities"`
	Lookback       int                `json:"lookback"`
	Sampled        int                `json:"sampled"`
	Strategy       string             `json:"strategy"`
	LastConfidence *float64           `json:"lastConfidence,omitempty"`
}

type BanditWinner struct {
	Provider   string     `json:"provider"`
	Model      *string    `json:"model,omitempty"`
	Share      float64    `json:"share"`
	MeanReward float64    `json:"meanReward"`
	AvgCostUsd float64    `json:"avgCostUsd"`
	Calls      int        `json:"calls"`
	Errors     int        `json:"errors"`
	LastUsed   *time.Time `json:"lastUsed,omitempty"`
	IsLeader   bool       `json:"isLeader"`
}

type Blueprint struct {
	ID                       string   `json:"id"`
	Name                     string   `json:"name"`
	Description              string   `json:"description"`
	Category                 string   `json:"category"`
	CostPriorUsd             float64  `json:"costPriorUSD"`
	ExpectedTimeToPreviewSec int      `json:"expectedTimeToPreviewSec"`
	SupportedGates           []string `json:"supportedGates"`
	FileCount                int      `json:"fileCount"`
}

type BlueprintDashboard struct {
	Blueprints []DashboardBlueprintStats `json:"blueprints"`
}

type BlueprintStats struct {
	BlueprintID         string  `json:"blueprintID"`
	Executions          int     `json:"executions"`
	PreviewSuccess      int     `json:"previewSuccess"`
	Refunds             int     `json:"refunds"`
	RepairCount         int     `json:"repairCount"`
	AvgRevenueUsd       float64 `json:"avgRevenueUSD"`
	AvgCostUsd          float64 `json:"avgCostUSD"`
	GrossMarginPct      float64 `json:"grossMarginPct"`
	AvgCompletionScore  float64 `json:"avgCompletionScore"`
	AvgTimeToPreviewSec float64 `json:"avgTimeToPreviewSec"`
}

type BlueprintSuccessRate struct {
	BlueprintID   string  `json:"blueprintID"`
	BlueprintName string  `json:"blueprintName"`
	SuccessRate   float64 `json:"successRate"`
	AvgMargin     float64 `json:"avgMargin"`
}

type BrokenAuditLink struct {
	AtEntryID        string `json:"atEntryID"`
	ExpectedPrevHash string `json:"expectedPrevHash"`
	ActualPrevHash   string `json:"actualPrevHash"`
}

type BudgetSummary struct {
	UserID   string        `json:"userId"`
	Email    string        `json:"email"`
	Tier     string        `json:"tier"`
	SpentUsd Decimal       `json:"spentUsd"`
	Entries  []LedgerEntry `json:"entries"`
}

type ChannelPref struct {
	Email bool `json:"email"`
	InApp bool `json:"inApp"`
}

type ChannelPrefInput struct {
	Email bool `json:"email"`
	InApp bool `json:"inApp"`
}

type Cohort struct {
	Month                 time.Time `json:"month"`
	NewPayingUsers        int       `json:"newPayingUsers"`
	SecondExecutionUsers  int       `json:"secondExecutionUsers"`
	Day7RepeatUsers       int       `json:"day7RepeatUsers"`
	Day30RepeatUsers      int       `json:"day30RepeatUsers"`
	AvgSpendUsd           float64   `json:"avgSpendUSD"`
	GrossMarginPct        float64   `json:"grossMarginPct"`
	CompletionRate        float64   `json:"completionRate"`
	RefundRate            float64   `json:"refundRate"`
	SupportTicketsPerExec float64   `json:"supportTicketsPerExec"`
}

type CohortDashboard struct {
	Cohorts []Cohort `json:"cohorts"`
}

type ComplexityBucket struct {
	Range string `json:"range"`
	Count int    `json:"count"`
}

type ConnectDeployDomainInput struct {
	ProjectID string  `json:"projectID"`
	DeployID  *string `json:"deployID,omitempty"`
	Hostname  string  `json:"hostname"`
	Provider  *string `json:"provider,omitempty"`
	Primary   *bool   `json:"primary,omitempty"`
	Metadata  JSON    `json:"metadata,omitempty"`
}

type CostDelta struct {
	Ts         time.Time `json:"ts"`
	UsdSpent   Decimal   `json:"usdSpent"`
	Model      *string   `json:"model,omitempty"`
	Provider   *string   `json:"provider,omitempty"`
	Agent      *string   `json:"agent,omitempty"`
	DurationMs *int      `json:"durationMs,omitempty"`
}

type CostEstimate struct {
	LowUsd      float64 `json:"lowUSD"`
	MedianUsd   float64 `json:"medianUSD"`
	HighUsd     float64 `json:"highUSD"`
	P95usd      float64 `json:"p95USD"`
	Breakdown   JSON    `json:"breakdown"`
	Confidence  float64 `json:"confidence"`
	BasedOnRuns int     `json:"basedOnRuns"`
	Caveat      *string `json:"caveat,omitempty"`
}

type CostReport struct {
	RevenueUsd        float64 `json:"revenueUSD"`
	ProviderCostUsd   float64 `json:"providerCostUSD"`
	SandboxCostUsd    float64 `json:"sandboxCostUSD"`
	StorageCostUsd    float64 `json:"storageCostUSD"`
	DeploymentCostUsd float64 `json:"deploymentCostUSD"`
	GrossMarginPct    float64 `json:"grossMarginPct"`
}

type CreatePaidExecutionInput struct {
	ProjectID     *string  `json:"projectID,omitempty"`
	BlueprintID   *string  `json:"blueprintID,omitempty"`
	BudgetUsd     float64  `json:"budgetUSD"`
	StopLossUsd   *float64 `json:"stopLossUSD,omitempty"`
	PromptSummary *string  `json:"promptSummary,omitempty"`
	Metadata      JSON     `json:"metadata,omitempty"`
}

type CreateProjectInput struct {
	ID          *string `json:"id,omitempty"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Idea        *string `json:"idea,omitempty"`
}

type CreateStageInput struct {
	ProjectID   string   `json:"projectId"`
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	PatchIds    []string `json:"patchIds"`
}

type DNSRecord struct {
	Type  string `json:"type"`
	Name  string `json:"name"`
	Value string `json:"value"`
	TTL   *int   `json:"ttl,omitempty"`
}

type DashboardBlueprintStats struct {
	BlueprintID        string  `json:"blueprintID"`
	Executions         int     `json:"executions"`
	AvgRevenueUsd      float64 `json:"avgRevenueUSD"`
	AvgCostUsd         float64 `json:"avgCostUSD"`
	GrossMarginPct     float64 `json:"grossMarginPct"`
	PreviewSuccess     int     `json:"previewSuccess"`
	Refunds            int     `json:"refunds"`
	RepairCount        int     `json:"repairCount"`
	AvgCompletionScore float64 `json:"avgCompletionScore"`
}

type Deploy struct {
	ID                   string     `json:"id"`
	TenantID             string     `json:"tenantID"`
	ProjectID            string     `json:"projectID"`
	ExecutionID          *string    `json:"executionID,omitempty"`
	BlueprintID          *string    `json:"blueprintID,omitempty"`
	Target               string     `json:"target"`
	Environment          string     `json:"environment"`
	Status               string     `json:"status"`
	ProviderDeploymentID *string    `json:"providerDeploymentID,omitempty"`
	PreviewURL           *string    `json:"previewURL,omitempty"`
	ProductionURL        *string    `json:"productionURL,omitempty"`
	DiffHash             *string    `json:"diffHash,omitempty"`
	ArtifactHash         *string    `json:"artifactHash,omitempty"`
	GateSummary          JSON       `json:"gateSummary"`
	CostUsd              float64    `json:"costUSD"`
	CreatedAt            time.Time  `json:"createdAt"`
	PreviewReadyAt       *time.Time `json:"previewReadyAt,omitempty"`
	PromotedAt           *time.Time `json:"promotedAt,omitempty"`
	RolledBackAt         *time.Time `json:"rolledBackAt,omitempty"`
}

type DeployApproval struct {
	ID            string     `json:"id"`
	DeployID      string     `json:"deployID"`
	TenantID      string     `json:"tenantID"`
	Status        string     `json:"status"`
	DiffHash      string     `json:"diffHash"`
	ArtifactHash  string     `json:"artifactHash"`
	GateSummary   JSON       `json:"gateSummary"`
	CostImpactUsd float64    `json:"costImpactUSD"`
	ExpiresAt     time.Time  `json:"expiresAt"`
	DecisionNote  *string    `json:"decisionNote,omitempty"`
	RequestedAt   time.Time  `json:"requestedAt"`
	DecidedAt     *time.Time `json:"decidedAt,omitempty"`
}

type DeployDomain struct {
	ID                 string      `json:"id"`
	TenantID           string      `json:"tenantID"`
	ProjectID          string      `json:"projectID"`
	DeployID           *string     `json:"deployID,omitempty"`
	Hostname           string      `json:"hostname"`
	Kind               string      `json:"kind"`
	Status             string      `json:"status"`
	Provider           string      `json:"provider"`
	Registrar          *string     `json:"registrar,omitempty"`
	Primary            bool        `json:"primary"`
	DNSRecords         []DNSRecord `json:"dnsRecords"`
	VerificationStatus string      `json:"verificationStatus"`
	CertificateStatus  string      `json:"certificateStatus"`
	Instructions       string      `json:"instructions"`
	Metadata           JSON        `json:"metadata"`
	CreatedAt          time.Time   `json:"createdAt"`
	UpdatedAt          time.Time   `json:"updatedAt"`
	VerifiedAt         *time.Time  `json:"verifiedAt,omitempty"`
	LiveAt             *time.Time  `json:"liveAt,omitempty"`
}

type DeployEvent struct {
	DeployID  string    `json:"deployID"`
	EventType string    `json:"eventType"`
	Payload   JSON      `json:"payload"`
	CreatedAt time.Time `json:"createdAt"`
}

type DescribeIdeaInput struct {
	Text                string   `json:"text"`
	BudgetUSDOverride   *float64 `json:"budgetUSDOverride,omitempty"`
	StartImmediately    *bool    `json:"startImmediately,omitempty"`
	BlueprintIDOverride *string  `json:"blueprintIDOverride,omitempty"`
}

type DeviceCloudDevice struct {
	ID           string  `json:"id"`
	Provider     string  `json:"provider"`
	Platform     string  `json:"platform"`
	OsVersion    string  `json:"osVersion"`
	Model        string  `json:"model"`
	Manufacturer *string `json:"manufacturer,omitempty"`
	Real         bool    `json:"real"`
}

type DeviceCloudSession struct {
	ID                  string    `json:"id"`
	Provider            string    `json:"provider"`
	DeviceID            string    `json:"deviceId"`
	Status              string    `json:"status"`
	AppURL              *string   `json:"appUrl,omitempty"`
	SessionURL          *string   `json:"sessionUrl,omitempty"`
	StartedAt           time.Time `json:"startedAt"`
	ExpiresAt           time.Time `json:"expiresAt"`
	BillableMinutesUsed float64   `json:"billableMinutesUsed"`
}

type DeviceCloudStartInput struct {
	ProjectID            string `json:"projectId"`
	WorkspaceID          string `json:"workspaceId"`
	Provider             string `json:"provider"`
	DeviceID             string `json:"deviceId"`
	AppURL               string `json:"appUrl"`
	SessionLengthMinutes *int   `json:"sessionLengthMinutes,omitempty"`
}

type DirDup struct {
	Directory string  `json:"directory"`
	DupPct    float64 `json:"dupPct"`
	Files     int     `json:"files"`
}

type DomainAvailability struct {
	Domain       string    `json:"domain"`
	Available    bool      `json:"available"`
	Registrar    string    `json:"registrar"`
	PriceUsd     float64   `json:"priceUSD"`
	Currency     string    `json:"currency"`
	Premium      bool      `json:"premium"`
	CanPurchase  bool      `json:"canPurchase"`
	Reason       *string   `json:"reason,omitempty"`
	CheckedAt    time.Time `json:"checkedAt"`
	Requirements []string  `json:"requirements"`
}

type EmailChangeInput struct {
	NewEmail        string `json:"newEmail"`
	CurrentPassword string `json:"currentPassword"`
}

type ErrorAggregate struct {
	Class           string    `json:"class"`
	Count           int       `json:"count"`
	LastSeen        time.Time `json:"lastSeen"`
	LastMessage     string    `json:"lastMessage"`
	LastLevel       string    `json:"lastLevel"`
	SampleRequestID *string   `json:"sampleRequestID,omitempty"`
}

type EstimateInput struct {
	BlueprintID          *string  `json:"blueprintID,omitempty"`
	Capabilities         []string `json:"capabilities,omitempty"`
	EstimatedDurationSec *int     `json:"estimatedDurationSec,omitempty"`
	PromptSummary        *string  `json:"promptSummary,omitempty"`
}

type Execution struct {
	ID                      string     `json:"id"`
	TenantID                string     `json:"tenantID"`
	ProjectID               *string    `json:"projectID,omitempty"`
	BlueprintID             *string    `json:"blueprintID,omitempty"`
	WorkspaceID             *string    `json:"workspaceID,omitempty"`
	Status                  string     `json:"status"`
	BudgetUsd               float64    `json:"budgetUSD"`
	ReservedUsd             float64    `json:"reservedUSD"`
	SpentUsd                float64    `json:"spentUSD"`
	RefundedUsd             float64    `json:"refundedUSD"`
	RevenueUsd              float64    `json:"revenueUSD"`
	ProviderCostUsd         float64    `json:"providerCostUSD"`
	SandboxCostUsd          float64    `json:"sandboxCostUSD"`
	StorageCostUsd          float64    `json:"storageCostUSD"`
	DeploymentCostUsd       float64    `json:"deploymentCostUSD"`
	CompletionScore         float64    `json:"completionScore"`
	GrossMarginPct          *float64   `json:"grossMarginPct,omitempty"`
	ExpectedCompletionDelta *float64   `json:"expectedCompletionDelta,omitempty"`
	RiskScore               *float64   `json:"riskScore,omitempty"`
	StopLossUsd             *float64   `json:"stopLossUSD,omitempty"`
	PromptSummary           *string    `json:"promptSummary,omitempty"`
	FailureReason           *string    `json:"failureReason,omitempty"`
	Metadata                JSON       `json:"metadata"`
	CreatedAt               time.Time  `json:"createdAt"`
	AdmittedAt              *time.Time `json:"admittedAt,omitempty"`
	StartedAt               *time.Time `json:"startedAt,omitempty"`
	EndedAt                 *time.Time `json:"endedAt,omitempty"`
}

type ExecutionEvent struct {
	ExecutionID string    `json:"executionID"`
	EventType   string    `json:"eventType"`
	Payload     JSON      `json:"payload"`
	CreatedAt   time.Time `json:"createdAt"`
}

type GateFailureRate struct {
	Gate        string  `json:"gate"`
	FailureRate float64 `json:"failureRate"`
	SampleSize  int     `json:"sampleSize"`
}

type GateIssue struct {
	Path     *string `json:"path,omitempty"`
	Line     *int    `json:"line,omitempty"`
	Rule     *string `json:"rule,omitempty"`
	Severity *string `json:"severity,omitempty"`
	Message  string  `json:"message"`
}

type GateReport struct {
	Stages          []GateStage `json:"stages"`
	CompletionScore float64     `json:"completionScore"`
}

type GateStage struct {
	Name        string `json:"name"`
	Status      string `json:"status"`
	IssuesCount int    `json:"issuesCount"`
}

type GateVerdict struct {
	Gate       string      `json:"gate"`
	Status     GateStatus  `json:"status"`
	Issues     []GateIssue `json:"issues"`
	StartedAt  *time.Time  `json:"startedAt,omitempty"`
	FinishedAt *time.Time  `json:"finishedAt,omitempty"`
	DurationMs *int        `json:"durationMs,omitempty"`
	Notes      *string     `json:"notes,omitempty"`
}

type GenerateMobileAssetEntry struct {
	Path      string `json:"path"`
	Width     int    `json:"width"`
	Height    int    `json:"height"`
	SizeBytes int    `json:"sizeBytes"`
	Purpose   string `json:"purpose"`
}

type GenerateMobileAssetsInput struct {
	ProjectID             string   `json:"projectId"`
	LogoPngBase64         string   `json:"logoPngBase64"`
	BackgroundColor       string   `json:"backgroundColor"`
	SplashForegroundColor *string  `json:"splashForegroundColor,omitempty"`
	Platforms             []string `json:"platforms"`
}

type GenerateMobileAssetsResult struct {
	FilesCount  int                        `json:"filesCount"`
	TotalBytes  int                        `json:"totalBytes"`
	GeneratedAt time.Time                  `json:"generatedAt"`
	Entries     []GenerateMobileAssetEntry `json:"entries"`
}

type GqlError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Details JSON   `json:"details,omitempty"`
}

type HealthMetrics struct {
	ReuseRate            float64            `json:"reuseRate"`
	DedupRate            float64            `json:"dedupRate"`
	DeadCodeCount        int                `json:"deadCodeCount"`
	ComplexityHistogram  []ComplexityBucket `json:"complexityHistogram"`
	DependencyCycles     int                `json:"dependencyCycles"`
	LocPerCapability     float64            `json:"locPerCapability"`
	AtlasCapabilityCount int                `json:"atlasCapabilityCount"`
	LastIndexedAt        *time.Time         `json:"lastIndexedAt,omitempty"`
	DuplicationByDir     []DirDup           `json:"duplicationByDir"`
	BundleByRoute        []RouteBundle      `json:"bundleByRoute"`
	Architecture         Architecture       `json:"architecture"`
}

type HeartbeatEvent struct {
	Ts      time.Time `json:"ts"`
	Message *string   `json:"message,omitempty"`
}

type InlineCancelledDelta struct {
	RequestID string  `json:"requestId"`
	Reason    *string `json:"reason,omitempty"`
}

func (InlineCancelledDelta) IsInlineDelta() {}

type InlineCompletion struct {
	RequestID  string     `json:"requestId"`
	Text       string     `json:"text"`
	Provider   string     `json:"provider"`
	Model      string     `json:"model"`
	Cursor     int        `json:"cursor"`
	StartedAt  time.Time  `json:"startedAt"`
	FinishedAt *time.Time `json:"finishedAt,omitempty"`
	Accepted   bool       `json:"accepted"`
}

type InlineDoneDelta struct {
	RequestID string  `json:"requestId"`
	Provider  *string `json:"provider,omitempty"`
	Model     *string `json:"model,omitempty"`
	Usage     JSON    `json:"usage,omitempty"`
}

func (InlineDoneDelta) IsInlineDelta() {}

type InlineErrorDelta struct {
	RequestID *string `json:"requestId,omitempty"`
	Code      string  `json:"code"`
	Message   string  `json:"message"`
}

func (InlineErrorDelta) IsInlineDelta() {}

type InlineInput struct {
	RequestID   *string `json:"requestId,omitempty"`
	Language    *string `json:"language,omitempty"`
	Path        *string `json:"path,omitempty"`
	Prefix      string  `json:"prefix"`
	Suffix      *string `json:"suffix,omitempty"`
	Cursor      *int    `json:"cursor,omitempty"`
	WorkspaceID *string `json:"workspaceId,omitempty"`
	ProjectID   *string `json:"projectId,omitempty"`
	Effort      *string `json:"effort,omitempty"`
}

type InlineStartDelta struct {
	RequestID string `json:"requestId"`
	Provider  string `json:"provider"`
	Model     string `json:"model"`
}

func (InlineStartDelta) IsInlineDelta() {}

type InlineTextDelta struct {
	RequestID string `json:"requestId"`
	Text      string `json:"text"`
}

func (InlineTextDelta) IsInlineDelta() {}

type LearningDashboard struct {
	OutcomeEventsToday     int                    `json:"outcomeEventsToday"`
	OutcomeEventsAllTime   int                    `json:"outcomeEventsAllTime"`
	ReuseRateLast7d        float64                `json:"reuseRateLast7d"`
	RepairRecipeHitsLast7d int                    `json:"repairRecipeHitsLast7d"`
	BanditConfidence       float64                `json:"banditConfidence"`
	AverageCompletionScore float64                `json:"averageCompletionScore"`
	AverageMarginPctLast7d float64                `json:"averageMarginPctLast7d"`
	GateFailureRates       []GateFailureRate      `json:"gateFailureRates"`
	BlueprintSuccessRates  []BlueprintSuccessRate `json:"blueprintSuccessRates"`
	Weaknesses             []Weakness             `json:"weaknesses"`
	LastIndexedAt          *time.Time             `json:"lastIndexedAt,omitempty"`
}

type LedgerEntry struct {
	ID               string    `json:"id"`
	UserID           string    `json:"userId"`
	ProjectID        *string   `json:"projectId,omitempty"`
	Provider         *string   `json:"provider,omitempty"`
	Model            *string   `json:"model,omitempty"`
	PromptTokens     int       `json:"promptTokens"`
	CompletionTokens int       `json:"completionTokens"`
	CostUsd          Decimal   `json:"costUsd"`
	RevenueUsd       Decimal   `json:"revenueUsd"`
	Ts               time.Time `json:"ts"`
	Agent            *string   `json:"agent,omitempty"`
	DurationMs       *int      `json:"durationMs,omitempty"`
}

type LedgerFilter struct {
	Since       *time.Time `json:"since,omitempty"`
	Until       *time.Time `json:"until,omitempty"`
	Types       []string   `json:"types,omitempty"`
	ExecutionID *string    `json:"executionID,omitempty"`
	Limit       *int       `json:"limit,omitempty"`
	Offset      *int       `json:"offset,omitempty"`
}

type LedgerRollup struct {
	RevenueUsd              float64 `json:"revenueUSD"`
	ProviderCostUsd         float64 `json:"providerCostUSD"`
	SandboxCostUsd          float64 `json:"sandboxCostUSD"`
	StorageCostUsd          float64 `json:"storageCostUSD"`
	DeploymentCostUsd       float64 `json:"deploymentCostUSD"`
	PremiumReasoningCostUsd float64 `json:"premiumReasoningCostUSD"`
	RefundsUsd              float64 `json:"refundsUSD"`
	PlatformMarginUsd       float64 `json:"platformMarginUSD"`
	GrossMarginPct          float64 `json:"grossMarginPct"`
}

type LogEntry struct {
	Time        time.Time `json:"time"`
	Level       string    `json:"level"`
	Message     string    `json:"message"`
	RequestID   *string   `json:"requestID,omitempty"`
	TenantID    *string   `json:"tenantID,omitempty"`
	ExecutionID *string   `json:"executionID,omitempty"`
	Fields      JSON      `json:"fields"`
}

type MCPRunningServer struct {
	ID        string    `json:"id"`
	ServerID  string    `json:"serverId"`
	StartedAt time.Time `json:"startedAt"`
}

type MCPServerSpec struct {
	ID             string   `json:"id"`
	Name           string   `json:"name"`
	Description    string   `json:"description"`
	Vendor         string   `json:"vendor"`
	EnvKeys        []string `json:"envKeys"`
	Category       string   `json:"category"`
	RequiresSecret bool     `json:"requiresSecret"`
	IconURL        *string  `json:"iconUrl,omitempty"`
	Capabilities   []string `json:"capabilities"`
}

type MobileBuild struct {
	ID                string     `json:"id"`
	ProjectID         string     `json:"projectId"`
	Platform          string     `json:"platform"`
	Profile           string     `json:"profile"`
	Status            string     `json:"status"`
	Distribution      *string    `json:"distribution,omitempty"`
	ArtifactURL       *string    `json:"artifactUrl,omitempty"`
	ArtifactSizeBytes *int       `json:"artifactSizeBytes,omitempty"`
	LogURL            *string    `json:"logUrl,omitempty"`
	AppVersion        *string    `json:"appVersion,omitempty"`
	AppBuildVersion   *string    `json:"appBuildVersion,omitempty"`
	SdkVersion        *string    `json:"sdkVersion,omitempty"`
	Channel           *string    `json:"channel,omitempty"`
	Initiator         *string    `json:"initiator,omitempty"`
	ErrorMessage      *string    `json:"errorMessage,omitempty"`
	CreatedAt         time.Time  `json:"createdAt"`
	UpdatedAt         time.Time  `json:"updatedAt"`
	CompletedAt       *time.Time `json:"completedAt,omitempty"`
}

type MobilePublishUpdateInput struct {
	ProjectID      string  `json:"projectId"`
	Channel        string  `json:"channel"`
	Branch         *string `json:"branch,omitempty"`
	Message        *string `json:"message,omitempty"`
	RuntimeVersion string  `json:"runtimeVersion"`
	ManifestExtra  JSON    `json:"manifestExtra,omitempty"`
}

type MobileSubmission struct {
	ID           string     `json:"id"`
	ProjectID    string     `json:"projectId"`
	Platform     string     `json:"platform"`
	Target       string     `json:"target"`
	Status       string     `json:"status"`
	BuildID      *string    `json:"buildId,omitempty"`
	ArchiveURL   *string    `json:"archiveUrl,omitempty"`
	LogURL       *string    `json:"logUrl,omitempty"`
	ErrorMessage *string    `json:"errorMessage,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	CompletedAt  *time.Time `json:"completedAt,omitempty"`
}

type MobileSubmitInput struct {
	BuildID                  string  `json:"buildId"`
	ProjectID                string  `json:"projectId"`
	Platform                 string  `json:"platform"`
	IosAppleID               *string `json:"iosAppleId,omitempty"`
	IosAscAppID              *string `json:"iosAscAppId,omitempty"`
	IosAppleTeamID           *string `json:"iosAppleTeamId,omitempty"`
	IosSku                   *string `json:"iosSku,omitempty"`
	IosCompanyName           *string `json:"iosCompanyName,omitempty"`
	AndroidServiceAccountKey *string `json:"androidServiceAccountKey,omitempty"`
	AndroidTrack             *string `json:"androidTrack,omitempty"`
	AndroidReleaseStatus     *string `json:"androidReleaseStatus,omitempty"`
}

type MobileTriggerBuildInput struct {
	ProjectID string  `json:"projectId"`
	Platform  string  `json:"platform"`
	Profile   *string `json:"profile,omitempty"`
	Channel   *string `json:"channel,omitempty"`
	Message   *string `json:"message,omitempty"`
}

type MobileUpdate struct {
	ID             string    `json:"id"`
	Branch         string    `json:"branch"`
	Channel        string    `json:"channel"`
	RuntimeVersion string    `json:"runtimeVersion"`
	Platform       *string   `json:"platform,omitempty"`
	Message        *string   `json:"message,omitempty"`
	ManifestURL    *string   `json:"manifestUrl,omitempty"`
	GroupID        *string   `json:"groupId,omitempty"`
	CreatedAt      time.Time `json:"createdAt"`
}

type Mutation struct {
}

type NextAction struct {
	Kind   string  `json:"kind"`
	Title  string  `json:"title"`
	Reason string  `json:"reason"`
	Cta    *string `json:"cta,omitempty"`
}

type Notification struct {
	ID        string     `json:"id"`
	Kind      string     `json:"kind"`
	Title     string     `json:"title"`
	Body      string     `json:"body"`
	Link      *string    `json:"link,omitempty"`
	Severity  string     `json:"severity"`
	ReadAt    *time.Time `json:"readAt,omitempty"`
	CreatedAt time.Time  `json:"createdAt"`
}

type NotificationPreferences struct {
	UserID          string      `json:"userId"`
	PauseAll        bool        `json:"pauseAll"`
	OnRunComplete   ChannelPref `json:"onRunComplete"`
	OnGateFailed    ChannelPref `json:"onGateFailed"`
	OnDeployDone    ChannelPref `json:"onDeployDone"`
	OnBudgetWarning ChannelPref `json:"onBudgetWarning"`
	OnReceipt       ChannelPref `json:"onReceipt"`
	WeeklyDigest    bool        `json:"weeklyDigest"`
}

type NotificationPreferencesInput struct {
	PauseAll        *bool             `json:"pauseAll,omitempty"`
	OnRunComplete   *ChannelPrefInput `json:"onRunComplete,omitempty"`
	OnGateFailed    *ChannelPrefInput `json:"onGateFailed,omitempty"`
	OnDeployDone    *ChannelPrefInput `json:"onDeployDone,omitempty"`
	OnBudgetWarning *ChannelPrefInput `json:"onBudgetWarning,omitempty"`
	OnReceipt       *ChannelPrefInput `json:"onReceipt,omitempty"`
	WeeklyDigest    *bool             `json:"weeklyDigest,omitempty"`
}

type OperationResult struct {
	Ok      bool    `json:"ok"`
	Message *string `json:"message,omitempty"`
}

type OperatorAuditEntry struct {
	ID        string    `json:"id"`
	Timestamp time.Time `json:"timestamp"`
	Action    string    `json:"action"`
	Outcome   string    `json:"outcome"`
	Hash      string    `json:"hash"`
}

type OperatorScaleSnapshot struct {
	ActiveExecutions     int     `json:"activeExecutions"`
	QueuedExecutions     int     `json:"queuedExecutions"`
	SandboxCapacity      int     `json:"sandboxCapacity"`
	WorkerUtilizationPct float64 `json:"workerUtilizationPct"`
}

type OperatorWalletSnapshot struct {
	TenantID         string  `json:"tenantID"`
	BalanceUsd       float64 `json:"balanceUSD"`
	HoldUsd          float64 `json:"holdUSD"`
	LifetimeTopUpUsd float64 `json:"lifetimeTopUpUSD"`
	LifetimeSpendUsd float64 `json:"lifetimeSpendUSD"`
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
	TotalCount  *int    `json:"totalCount,omitempty"`
}

type ParsedIdea struct {
	Title              string   `json:"title"`
	Summary            string   `json:"summary"`
	BlueprintID        string   `json:"blueprintID"`
	BlueprintReason    string   `json:"blueprintReason"`
	SuggestedBudgetUsd float64  `json:"suggestedBudgetUSD"`
	Tags               []string `json:"tags"`
	StopLossUsd        float64  `json:"stopLossUSD"`
	Confidence         float64  `json:"confidence"`
}

type Patch struct {
	ID        string          `json:"id"`
	ProjectID string          `json:"projectId"`
	Title     *string         `json:"title,omitempty"`
	Summary   *string         `json:"summary,omitempty"`
	Author    *string         `json:"author,omitempty"`
	Status    PatchStatus     `json:"status"`
	CreatedAt time.Time       `json:"createdAt"`
	AppliedAt *time.Time      `json:"appliedAt,omitempty"`
	Changes   []PatchChange   `json:"changes"`
	StageID   *string         `json:"stageId,omitempty"`
	Stage     *PatchStage     `json:"stage,omitempty"`
	Conflicts []PatchConflict `json:"conflicts,omitempty"`
}

type PatchAnchorOp struct {
	Path        string `json:"path"`
	Anchor      string `json:"anchor"`
	Replacement string `json:"replacement"`
}

func (PatchAnchorOp) IsPatchOp() {}

type PatchChange struct {
	Op          PatchChangeOp `json:"op"`
	Path        string        `json:"path"`
	Content     *string       `json:"content,omitempty"`
	Anchor      *string       `json:"anchor,omitempty"`
	Replacement *string       `json:"replacement,omitempty"`
	Symbol      *string       `json:"symbol,omitempty"`
}

type PatchChangeInput struct {
	Op          PatchChangeOp `json:"op"`
	Path        string        `json:"path"`
	Content     *string       `json:"content,omitempty"`
	Anchor      *string       `json:"anchor,omitempty"`
	Replacement *string       `json:"replacement,omitempty"`
	Symbol      *string       `json:"symbol,omitempty"`
}

type PatchConflict struct {
	Path    string `json:"path"`
	Base    string `json:"base"`
	Ours    string `json:"ours"`
	Theirs  string `json:"theirs"`
	Markers string `json:"markers"`
}

type PatchStage struct {
	ID              string           `json:"id"`
	ProjectID       string           `json:"projectId"`
	Name            string           `json:"name"`
	Description     *string          `json:"description,omitempty"`
	PatchIds        []string         `json:"patchIds"`
	Status          PatchStageStatus `json:"status"`
	RejectionReason *string          `json:"rejectionReason,omitempty"`
	CreatedAt       time.Time        `json:"createdAt"`
	UpdatedAt       time.Time        `json:"updatedAt"`
}

type PatchSymbolOp struct {
	Path        string `json:"path"`
	Symbol      string `json:"symbol"`
	Replacement string `json:"replacement"`
}

func (PatchSymbolOp) IsPatchOp() {}

type Plan struct {
	Tier          string   `json:"tier"`
	Name          string   `json:"name"`
	PriceUsd      Decimal  `json:"priceUsd"`
	CostCapUsd    Decimal  `json:"costCapUsd"`
	Description   *string  `json:"description,omitempty"`
	Features      []string `json:"features"`
	StripePriceID *string  `json:"stripePriceId,omitempty"`
}

type PlanDeployInput struct {
	ProjectID   string  `json:"projectID"`
	ExecutionID *string `json:"executionID,omitempty"`
	BlueprintID *string `json:"blueprintID,omitempty"`
	Target      string  `json:"target"`
	Environment string  `json:"environment"`
	ArtifactRef string  `json:"artifactRef"`
	DiffHash    string  `json:"diffHash"`
	Metadata    JSON    `json:"metadata,omitempty"`
}

type ProfitDashboard struct {
	WindowStart       time.Time `json:"windowStart"`
	WindowEnd         time.Time `json:"windowEnd"`
	RevenueUsd        float64   `json:"revenueUSD"`
	ProviderCostUsd   float64   `json:"providerCostUSD"`
	SandboxCostUsd    float64   `json:"sandboxCostUSD"`
	OtherCostUsd      float64   `json:"otherCostUSD"`
	GrossProfitUsd    float64   `json:"grossProfitUSD"`
	GrossMarginPct    float64   `json:"grossMarginPct"`
	ActiveExecutions  int       `json:"activeExecutions"`
	BlockedExecutions int       `json:"blockedExecutions"`
	RefundCount       int       `json:"refundCount"`
	TopUpRate         float64   `json:"topUpRate"`
}

type ProfitGuardDecision struct {
	ID                      string    `json:"id"`
	ExecutionID             string    `json:"executionID"`
	EnforcementPoint        string    `json:"enforcementPoint"`
	Decision                string    `json:"decision"`
	Reason                  string    `json:"reason"`
	SpentUsd                float64   `json:"spentUSD"`
	ReservedUsd             float64   `json:"reservedUSD"`
	EstimatedStepCostUsd    float64   `json:"estimatedStepCostUSD"`
	ExpectedCompletionDelta float64   `json:"expectedCompletionDelta"`
	ExpectedMarginPct       *float64  `json:"expectedMarginPct,omitempty"`
	RiskScore               *float64  `json:"riskScore,omitempty"`
	RecommendedProvider     *string   `json:"recommendedProvider,omitempty"`
	CreatedAt               time.Time `json:"createdAt"`
}

type Project struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Description *string       `json:"description,omitempty"`
	Status      string        `json:"status"`
	OwnerID     string        `json:"ownerId"`
	IsPublic    bool          `json:"isPublic"`
	Idea        *string       `json:"idea,omitempty"`
	Files       []ProjectFile `json:"files"`
	Gates       []GateVerdict `json:"gates"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
}

type ProjectFile struct {
	Path      string     `json:"path"`
	Content   *string    `json:"content,omitempty"`
	Size      *int       `json:"size,omitempty"`
	Language  *string    `json:"language,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type ProposePatchInput struct {
	ProjectID string             `json:"projectId"`
	Title     *string            `json:"title,omitempty"`
	Summary   *string            `json:"summary,omitempty"`
	Author    *string            `json:"author,omitempty"`
	Changes   []PatchChangeInput `json:"changes"`
}

type PurchaseDeployDomainInput struct {
	ProjectID        string   `json:"projectID"`
	DeployID         *string  `json:"deployID,omitempty"`
	Domain           string   `json:"domain"`
	Provider         *string  `json:"provider,omitempty"`
	Registrar        *string  `json:"registrar,omitempty"`
	Years            *int     `json:"years,omitempty"`
	AutoRenew        *bool    `json:"autoRenew,omitempty"`
	ExpectedPriceUsd *float64 `json:"expectedPriceUSD,omitempty"`
	Contact          JSON     `json:"contact,omitempty"`
	Primary          *bool    `json:"primary,omitempty"`
	Metadata         JSON     `json:"metadata,omitempty"`
}

type Query struct {
}

type Rate struct {
	Provider          string  `json:"provider"`
	Model             string  `json:"model"`
	PromptPerMTok     Decimal `json:"promptPerMTok"`
	CompletionPerMTok Decimal `json:"completionPerMTok"`
}

type RenameSymbolInput struct {
	ProjectID string      `json:"projectId"`
	Kind      *SymbolKind `json:"kind,omitempty"`
	OldName   string      `json:"oldName"`
	NewName   string      `json:"newName"`
}

type RerunGateInput struct {
	ProjectID string `json:"projectId"`
	Gate      string `json:"gate"`
}

type ReserveDeploySubdomainInput struct {
	ProjectID string  `json:"projectID"`
	DeployID  *string `json:"deployID,omitempty"`
	Subdomain *string `json:"subdomain,omitempty"`
	Provider  *string `json:"provider,omitempty"`
	Primary   *bool   `json:"primary,omitempty"`
	Metadata  JSON    `json:"metadata,omitempty"`
}

type RouteBundle struct {
	Route       string  `json:"route"`
	TotalKb     float64 `json:"totalKB"`
	FirstLoadKb float64 `json:"firstLoadKB"`
}

type RunDoneEvent struct {
	Ts      time.Time `json:"ts"`
	Ok      bool      `json:"ok"`
	Summary JSON      `json:"summary,omitempty"`
}

func (RunDoneEvent) IsRunEvent() {}

type RunErrorEvent struct {
	Ts      time.Time `json:"ts"`
	Code    string    `json:"code"`
	Message string    `json:"message"`
}

func (RunErrorEvent) IsRunEvent() {}

type RunExecutionEvent struct {
	Ts      time.Time `json:"ts"`
	Payload JSON      `json:"payload"`
}

func (RunExecutionEvent) IsRunEvent() {}

type RunGateEvent struct {
	Ts      time.Time `json:"ts"`
	Gate    string    `json:"gate"`
	Status  string    `json:"status"`
	Message *string   `json:"message,omitempty"`
}

func (RunGateEvent) IsRunEvent() {}

type ScaleDashboard struct {
	ActiveExecutions     int     `json:"activeExecutions"`
	QueuedExecutions     int     `json:"queuedExecutions"`
	QueueWaitSec         float64 `json:"queueWaitSec"`
	SandboxCapacity      int     `json:"sandboxCapacity"`
	WorkerUtilizationPct float64 `json:"workerUtilizationPct"`
	ScaleHealth          float64 `json:"scaleHealth"`
}

type SecurityReport struct {
	ExecutionID   string                  `json:"executionID"`
	TenantID      string                  `json:"tenantID"`
	Status        string                  `json:"status"`
	OverallScore  float64                 `json:"overallScore"`
	Findings      []SecurityReportFinding `json:"findings"`
	SecretsFound  int                     `json:"secretsFound"`
	OutdatedDeps  int                     `json:"outdatedDeps"`
	OwaspCoverage JSON                    `json:"owaspCoverage"`
	GeneratedAt   time.Time               `json:"generatedAt"`
	BlockedDeploy bool                    `json:"blockedDeploy"`
}

type SecurityReportFinding struct {
	ID          string    `json:"id"`
	Severity    string    `json:"severity"`
	RuleID      string    `json:"ruleID"`
	Category    string    `json:"category"`
	Path        string    `json:"path"`
	Line        int       `json:"line"`
	Summary     string    `json:"summary"`
	Remediation string    `json:"remediation"`
	DetectedAt  time.Time `json:"detectedAt"`
}

type Session struct {
	User       User       `json:"user"`
	Token      string     `json:"token"`
	ExpiresAt  *time.Time `json:"expiresAt,omitempty"`
	Jti        *string    `json:"jti,omitempty"`
	IPAddress  *string    `json:"ipAddress,omitempty"`
	UserAgent  *string    `json:"userAgent,omitempty"`
	LastSeenAt *time.Time `json:"lastSeenAt,omitempty"`
	Current    *bool      `json:"current,omitempty"`
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignUpInput struct {
	Email    string  `json:"email"`
	Name     *string `json:"name,omitempty"`
	Password string  `json:"password"`
}

type StartCheckoutInput struct {
	Tier       string  `json:"tier"`
	SuccessURL *string `json:"successUrl,omitempty"`
	CancelURL  *string `json:"cancelUrl,omitempty"`
}

type StripeCheckoutSession struct {
	SessionID string `json:"sessionId"`
	URL       string `json:"url"`
}

type StudioBootstrap struct {
	Project      Project      `json:"project"`
	Execution    Execution    `json:"execution"`
	Idea         ParsedIdea   `json:"idea"`
	CostEstimate CostEstimate `json:"costEstimate"`
}

type Subscription struct {
}

type SupportBundle struct {
	ExecutionID    string                `json:"executionID"`
	TenantID       string                `json:"tenantID"`
	Status         string                `json:"status"`
	PreviewURL     *string               `json:"previewURL,omitempty"`
	ProductionURL  *string               `json:"productionURL,omitempty"`
	ChangedFiles   []string              `json:"changedFiles"`
	PatchCount     int                   `json:"patchCount"`
	GateReport     GateReport            `json:"gateReport"`
	SecurityReport SupportSecurityReport `json:"securityReport"`
	CostReport     CostReport            `json:"costReport"`
	NextBestAction NextAction            `json:"nextBestAction"`
	GeneratedAt    time.Time             `json:"generatedAt"`
}

type SupportSecurityFinding struct {
	Severity string `json:"severity"`
	RuleID   string `json:"ruleID"`
	Path     string `json:"path"`
	Line     int    `json:"line"`
	Summary  string `json:"summary"`
}

type SupportSecurityReport struct {
	Findings      []SupportSecurityFinding `json:"findings"`
	PassRate      float64                  `json:"passRate"`
	BlockedDeploy bool                     `json:"blockedDeploy"`
}

type SymbolPatchInput struct {
	ProjectID string       `json:"projectId"`
	Path      string       `json:"path"`
	Title     *string      `json:"title,omitempty"`
	Summary   *string      `json:"summary,omitempty"`
	Author    *string      `json:"author,omitempty"`
	Kind      SymbolKind   `json:"kind"`
	Name      string       `json:"name"`
	Receiver  *string      `json:"receiver,omitempty"`
	Action    SymbolAction `json:"action"`
	NewBody   *string      `json:"newBody,omitempty"`
	NewDecl   *string      `json:"newDecl,omitempty"`
	NewName   *string      `json:"newName,omitempty"`
}

type TelemetryPreferenceInput struct {
	OptOut bool `json:"optOut"`
}

type UpdateProjectInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Idea        *string `json:"idea,omitempty"`
	Status      *string `json:"status,omitempty"`
}

type User struct {
	ID              string     `json:"id"`
	Email           string     `json:"email"`
	Name            *string    `json:"name,omitempty"`
	Plan            *string    `json:"plan,omitempty"`
	OrgID           *string    `json:"orgId,omitempty"`
	CreatedAt       time.Time  `json:"createdAt"`
	TelemetryOptOut bool       `json:"telemetryOptOut"`
	EmailVerifiedAt *time.Time `json:"emailVerifiedAt,omitempty"`
}

type VaultSnapshot struct {
	RevenueUsd      Decimal   `json:"revenueUsd"`
	ProviderCostUsd Decimal   `json:"providerCostUsd"`
	MarginUsd       Decimal   `json:"marginUsd"`
	Entries         int       `json:"entries"`
	AsOf            time.Time `json:"asOf"`
}

type VersionInfo struct {
	Version   string `json:"version"`
	Commit    string `json:"commit"`
	BuildTime string `json:"buildTime"`
	Service   string `json:"service"`
}

type Wallet struct {
	TenantID         string    `json:"tenantID"`
	BalanceUsd       float64   `json:"balanceUSD"`
	HoldUsd          float64   `json:"holdUSD"`
	AvailableUsd     float64   `json:"availableUSD"`
	LifetimeTopUpUsd float64   `json:"lifetimeTopUpUSD"`
	LifetimeSpendUsd float64   `json:"lifetimeSpendUSD"`
	UpdatedAt        time.Time `json:"updatedAt"`
}

type WalletCheckoutSession struct {
	URL       string `json:"url"`
	SessionID string `json:"sessionID"`
}

type WalletLedgerEntry struct {
	ID             string    `json:"id"`
	TenantID       string    `json:"tenantID"`
	ExecutionID    *string   `json:"executionID,omitempty"`
	EntryType      string    `json:"entryType"`
	Direction      string    `json:"direction"`
	AmountUsd      float64   `json:"amountUSD"`
	Provider       *string   `json:"provider,omitempty"`
	Billable       bool      `json:"billable"`
	MarginRelevant bool      `json:"marginRelevant"`
	Metadata       JSON      `json:"metadata"`
	CreatedAt      time.Time `json:"createdAt"`
}

type WalletTopUp struct {
	ID          string     `json:"id"`
	AmountUsd   float64    `json:"amountUSD"`
	Status      string     `json:"status"`
	CreatedAt   time.Time  `json:"createdAt"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
}

type Weakness struct {
	Dimension       string `json:"dimension"`
	Description     string `json:"description"`
	Severity        string `json:"severity"`
	SuggestedAction string `json:"suggestedAction"`
}

type WriteProjectFileInput struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

type AuditOutcome string

const (
	AuditOutcomeSuccess AuditOutcome = "SUCCESS"
	AuditOutcomeFailure AuditOutcome = "FAILURE"
	AuditOutcomeBlocked AuditOutcome = "BLOCKED"
	AuditOutcomeSkipped AuditOutcome = "SKIPPED"
)

var AllAuditOutcome = []AuditOutcome{
	AuditOutcomeSuccess,
	AuditOutcomeFailure,
	AuditOutcomeBlocked,
	AuditOutcomeSkipped,
}

func (e AuditOutcome) IsValid() bool {
	switch e {
	case AuditOutcomeSuccess, AuditOutcomeFailure, AuditOutcomeBlocked, AuditOutcomeSkipped:
		return true
	}
	return false
}

func (e AuditOutcome) String() string {
	return string(e)
}

func (e *AuditOutcome) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuditOutcome(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuditOutcome", str)
	}
	return nil
}

func (e AuditOutcome) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AuditOutcome) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AuditOutcome) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GateStatus string

const (
	GateStatusPending GateStatus = "PENDING"
	GateStatusRunning GateStatus = "RUNNING"
	GateStatusPass    GateStatus = "PASS"
	GateStatusFail    GateStatus = "FAIL"
	GateStatusWarn    GateStatus = "WARN"
	GateStatusBlocked GateStatus = "BLOCKED"
	GateStatusSkipped GateStatus = "SKIPPED"
)

var AllGateStatus = []GateStatus{
	GateStatusPending,
	GateStatusRunning,
	GateStatusPass,
	GateStatusFail,
	GateStatusWarn,
	GateStatusBlocked,
	GateStatusSkipped,
}

func (e GateStatus) IsValid() bool {
	switch e {
	case GateStatusPending, GateStatusRunning, GateStatusPass, GateStatusFail, GateStatusWarn, GateStatusBlocked, GateStatusSkipped:
		return true
	}
	return false
}

func (e GateStatus) String() string {
	return string(e)
}

func (e *GateStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GateStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GateStatus", str)
	}
	return nil
}

func (e GateStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GateStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GateStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PatchChangeOp string

const (
	PatchChangeOpCreate        PatchChangeOp = "CREATE"
	PatchChangeOpReplace       PatchChangeOp = "REPLACE"
	PatchChangeOpDelete        PatchChangeOp = "DELETE"
	PatchChangeOpInsertBefore  PatchChangeOp = "INSERT_BEFORE"
	PatchChangeOpInsertAfter   PatchChangeOp = "INSERT_AFTER"
	PatchChangeOpAnchorReplace PatchChangeOp = "ANCHOR_REPLACE"
	PatchChangeOpSymbolReplace PatchChangeOp = "SYMBOL_REPLACE"
)

var AllPatchChangeOp = []PatchChangeOp{
	PatchChangeOpCreate,
	PatchChangeOpReplace,
	PatchChangeOpDelete,
	PatchChangeOpInsertBefore,
	PatchChangeOpInsertAfter,
	PatchChangeOpAnchorReplace,
	PatchChangeOpSymbolReplace,
}

func (e PatchChangeOp) IsValid() bool {
	switch e {
	case PatchChangeOpCreate, PatchChangeOpReplace, PatchChangeOpDelete, PatchChangeOpInsertBefore, PatchChangeOpInsertAfter, PatchChangeOpAnchorReplace, PatchChangeOpSymbolReplace:
		return true
	}
	return false
}

func (e PatchChangeOp) String() string {
	return string(e)
}

func (e *PatchChangeOp) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PatchChangeOp(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PatchChangeOp", str)
	}
	return nil
}

func (e PatchChangeOp) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PatchChangeOp) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PatchChangeOp) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PatchStageStatus string

const (
	PatchStageStatusOpen     PatchStageStatus = "OPEN"
	PatchStageStatusReviewed PatchStageStatus = "REVIEWED"
	PatchStageStatusApplied  PatchStageStatus = "APPLIED"
	PatchStageStatusRejected PatchStageStatus = "REJECTED"
)

var AllPatchStageStatus = []PatchStageStatus{
	PatchStageStatusOpen,
	PatchStageStatusReviewed,
	PatchStageStatusApplied,
	PatchStageStatusRejected,
}

func (e PatchStageStatus) IsValid() bool {
	switch e {
	case PatchStageStatusOpen, PatchStageStatusReviewed, PatchStageStatusApplied, PatchStageStatusRejected:
		return true
	}
	return false
}

func (e PatchStageStatus) String() string {
	return string(e)
}

func (e *PatchStageStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PatchStageStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PatchStageStatus", str)
	}
	return nil
}

func (e PatchStageStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PatchStageStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PatchStageStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PatchStatus string

const (
	PatchStatusProposed   PatchStatus = "PROPOSED"
	PatchStatusApproved   PatchStatus = "APPROVED"
	PatchStatusApplied    PatchStatus = "APPLIED"
	PatchStatusRejected   PatchStatus = "REJECTED"
	PatchStatusRolledBack PatchStatus = "ROLLED_BACK"
	PatchStatusConflicted PatchStatus = "CONFLICTED"
)

var AllPatchStatus = []PatchStatus{
	PatchStatusProposed,
	PatchStatusApproved,
	PatchStatusApplied,
	PatchStatusRejected,
	PatchStatusRolledBack,
	PatchStatusConflicted,
}

func (e PatchStatus) IsValid() bool {
	switch e {
	case PatchStatusProposed, PatchStatusApproved, PatchStatusApplied, PatchStatusRejected, PatchStatusRolledBack, PatchStatusConflicted:
		return true
	}
	return false
}

func (e PatchStatus) String() string {
	return string(e)
}

func (e *PatchStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PatchStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PatchStatus", str)
	}
	return nil
}

func (e PatchStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PatchStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PatchStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SymbolAction string

const (
	SymbolActionRename       SymbolAction = "RENAME"
	SymbolActionReplaceBody  SymbolAction = "REPLACE_BODY"
	SymbolActionInsertAfter  SymbolAction = "INSERT_AFTER"
	SymbolActionDeleteSymbol SymbolAction = "DELETE_SYMBOL"
)

var AllSymbolAction = []SymbolAction{
	SymbolActionRename,
	SymbolActionReplaceBody,
	SymbolActionInsertAfter,
	SymbolActionDeleteSymbol,
}

func (e SymbolAction) IsValid() bool {
	switch e {
	case SymbolActionRename, SymbolActionReplaceBody, SymbolActionInsertAfter, SymbolActionDeleteSymbol:
		return true
	}
	return false
}

func (e SymbolAction) String() string {
	return string(e)
}

func (e *SymbolAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SymbolAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SymbolAction", str)
	}
	return nil
}

func (e SymbolAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SymbolAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SymbolAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SymbolKind string

const (
	SymbolKindFunction  SymbolKind = "FUNCTION"
	SymbolKindMethod    SymbolKind = "METHOD"
	SymbolKindClass     SymbolKind = "CLASS"
	SymbolKindStruct    SymbolKind = "STRUCT"
	SymbolKindInterface SymbolKind = "INTERFACE"
	SymbolKindType      SymbolKind = "TYPE"
	SymbolKindVar       SymbolKind = "VAR"
	SymbolKindConst     SymbolKind = "CONST"
)

var AllSymbolKind = []SymbolKind{
	SymbolKindFunction,
	SymbolKindMethod,
	SymbolKindClass,
	SymbolKindStruct,
	SymbolKindInterface,
	SymbolKindType,
	SymbolKindVar,
	SymbolKindConst,
}

func (e SymbolKind) IsValid() bool {
	switch e {
	case SymbolKindFunction, SymbolKindMethod, SymbolKindClass, SymbolKindStruct, SymbolKindInterface, SymbolKindType, SymbolKindVar, SymbolKindConst:
		return true
	}
	return false
}

func (e SymbolKind) String() string {
	return string(e)
}

func (e *SymbolKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SymbolKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SymbolKind", str)
	}
	return nil
}

func (e SymbolKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SymbolKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SymbolKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
